// Capturas v2: splash, mapa, niveles (2x2, 3x3, batchim, oído), fallo, victoria, fin de barrio, noche, escritorio.
const puppeteer = require("puppeteer-core");
const path = require("path");
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
(async () => {
  const browser = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true, args: ["--no-sandbox", "--autoplay-policy=no-user-gesture-required"] });
  const page = await browser.newPage();
  const errors = []; page.on("pageerror", (e) => errors.push(e.message));
  const shot = (name) => page.screenshot({ path: path.join(__dirname, "t_" + name + ".png") });
  const abre = async (id) => { await page.evaluate((id) => { window.Dubu.abreNivel(window.Dubu.NIVELES.find((n) => n.id === id)); }, id); await wait(900); };
  const tap = async (...js) => { await page.evaluate((js) => { const D = window.Dubu; const idx = (j) => D.S().tiles.findIndex((t) => !t.usado && t.j === j); for (const j of js) D.tapTile(idx(j)); }, js); await wait(400); };
  await page.setViewport({ width: 375, height: 812, isMobile: true, hasTouch: true });
  await page.evaluateOnNewDocument(() => { localStorage.setItem("as-theme", "light"); localStorage.removeItem("dubu-progreso"); });
  await page.goto("http://localhost:3111/dubu?dev=1", { waitUntil: "networkidle2", timeout: 90000 });
  await wait(1500); await shot("splash"); await page.click("#btn-entrar"); await wait(1000); await shot("mapa");
  await abre("1-1"); await shot("1-1_inicio"); await tap("ㅇ"); await shot("1-1_consonante");
  await abre("1-3"); await shot("1-3_reconocer");
  await abre("2-1"); await tap("ㄱ", "ㅗ"); await shot("2-1_gogi_medio");
  await abre("3-1"); await tap("ㄱ", "ㅏ"); await shot("3-1_batchim_espera");
  await abre("2-4"); await tap("ㅂ", "ㅑ"); await shot("2-4_fallo");
  await abre("5-1"); await shot("5-1_oido"); await tap("ㅅ", "ㅏ", "ㄱ", "ㅘ"); await wait(900); await shot("5-1_victoria");
  await page.evaluate(() => { document.querySelectorAll(".velo.on").forEach((v) => v.classList.remove("on")); });
  await abre("6-5"); await shot("6-5_jefe");
  await page.evaluate(() => { const P = window.Dubu.P(); for (const id of ["1-1", "1-2", "1-3", "1-4"]) P.niveles[id] = { cubitos: 3, fallos: 0 }; P.oido = { "ㅓ/ㅗ": { ok: 4, total: 5 }, "batchim": { ok: 2, total: 4 } }; localStorage.setItem("dubu-progreso", JSON.stringify(P)); });
  await abre("1-5"); await tap("ㅇ", "ㅜ", "ㅇ", "ㅠ"); await wait(1200);
  await page.evaluate(() => { const b = [...document.querySelectorAll("#victoria .btn")].find((b) => /plato/.test(b.textContent)); if (b) b.click(); }); await wait(800); await shot("fin_barrio");
  await page.evaluate(() => { document.querySelectorAll(".velo.on").forEach((v) => v.classList.remove("on")); window.Dubu.muestraMapa(); }); await wait(500); await shot("mapa_progreso");
  await page.evaluate(() => { localStorage.setItem("as-theme", "dark"); }); await page.reload({ waitUntil: "networkidle2" }); await wait(1200); await page.click("#btn-entrar"); await wait(800);
  await abre("4-1"); await tap("ㅋ", "ㅓ"); await shot("dark_4-1");
  await page.setViewport({ width: 1024, height: 820 }); await page.evaluate(() => { localStorage.setItem("as-theme", "light"); }); await page.reload({ waitUntil: "networkidle2" }); await wait(1200); await page.click("#btn-entrar"); await wait(600);
  await abre("3-5"); await tap("ㅎ", "ㅏ", "ㄴ"); await shot("desktop_3-5");
  const dims = await page.evaluate(() => ({ sw: document.documentElement.scrollWidth, iw: innerWidth }));
  console.log("desktop overflow:", dims.sw > dims.iw, "errores:", errors.length, errors.slice(0, 3));
  await browser.close();
})();
