// Diccionario inglés: clave = texto en español (gettext). Generado con scratchpad/i18n_build_dict.js; edita i18n_en.json y regenera.
// Si falta una clave se muestra el español.
import type { Dict } from "../i18n";

export const EN: Dict = {
  // ── app/nivel-1/page.tsx
  "US${p} pago único": "US${p} one-time payment",
  "{n} cuotas de US${m}": "{n} payments of US${m}",
  "¿Qué curso tomo?": "Which course should I take?",
  "Las 8 semanas": "The 8 weeks",
  "Profesores": "Teachers",
  "Inscripción": "Enrollment",
  "Pago": "Payment",
  "Preguntas frecuentes": "FAQ",
  "nombre del niño/a": "child's name",
  "nombre": "name",
  "correo": "email",
  "edad": "age",
  "país": "country",
  "nivel": "level",
  "cómo nos conociste": "how you found us",
  "nombre del apoderado/a": "parent/guardian's name",
  "Falta: {campos}.": "Missing: {campos}.",
  "Hubo un problema al enviar. Intenta de nuevo o escríbenos por WhatsApp.": "Something went wrong while sending. Try again or message us on WhatsApp.",
  "Primero completa tus datos arriba para reservar tu cupo.": "First fill in your details above to reserve your spot.",
  "Hola Jay! Quiero pagar con tarjeta mi cupo en {curso} ({plan}) y el pago online no cargó.": "Hi Jay! I want to pay by card for my spot in {curso} ({plan}) and the online payment didn't load.",
  "inscribir a mi hijo/a": "enroll my child",
  "inscribirme": "enroll",
  "Hola Jay! Quiero {verbo} en {curso} ({dia} {hora} Chile) con {plan}. ¿Me pasas los datos para la transferencia?": "Hi Jay! I'd like to {verbo} in {curso} ({dia} {hora} Chile time) with {plan}. Could you send me the bank transfer details?",
  "Hola Jay! Estoy fuera de Chile y quiero pagar {curso} en {n} cuotas de US${m}. ¿Me envías el link de PayPal?": "Hi Jay! I'm outside Chile and I'd like to pay for {curso} in {n} payments of US${m}. Could you send me the PayPal link?",
  "${clp} CLP aprox.": "approx. ${clp} CLP",
  "¿Las clases son en vivo o grabadas?": "Are the classes live or recorded?",
  "En vivo por Zoom (60 min cada una). Si te pierdes alguna, recibes la grabación dentro de las 24 horas y puedes escribirnos para resolver dudas de esa clase.": "Live on Zoom (60 min each). If you miss one, you get the recording within 24 hours and you can message us with any questions about that class.",
  "¿Cuánto dura cada curso y cuándo empieza?": "How long is each course and when does it start?",
  "Todos los cursos duran 8 semanas (2 meses), con 1 clase en vivo por semana. La cohorte arranca {inicio} y termina la semana del 23 de noviembre. Matrícula abierta hasta el {cierre}.": "Every course runs 8 weeks (2 months), with 1 live class per week. The cohort starts {inicio} and ends the week of November 23. Enrollment open until {cierre}.",
  "¿Cuánto cuesta y cómo pago?": "How much does it cost and how do I pay?",
  "{precio} — mismo precio en todos los cursos. Aceptamos transferencia bancaria en Chile (sin comisión), tarjeta de crédito/débito vía Mercado Pago (se cobra en pesos chilenos) y PayPal en dólares (también con tarjeta, sin cuenta PayPal).": "{precio} — same price for every course. We accept bank transfer in Chile (no fees), credit/debit card via Mercado Pago (charged in Chilean pesos) and PayPal in US dollars (also by card, no PayPal account needed).",
  "¿Necesito experiencia previa?": "Do I need prior experience?",
  "Para Básico 1 (A1.1) y Coreano para Niños: cero, empezamos desde el alfabeto. Básico 2 (A1.2) requiere Básico 1 (o el Nivel 1 de julio). Conversacional 1 (A2.1) requiere Básico 2 o el test de nivel. TOPIK II es para nivel intermedio.": "For Basic 1 (A1.1) and Korean for Kids: none, we start with the alphabet. Basic 2 (A1.2) requires Basic 1 — or Level 1 (July). Conversational 1 (A2.1) requires Basic 2 or the placement test. TOPIK II is for intermediate level.",
  "Fui alumno/a del Nivel 1 en julio, ¿qué curso sigo?": "I took Level 1 in July — which course comes next?",
  "Ese curso hoy se llama Básico 1 (A1.1) y tu certificado equivale a A1.1. Tu siguiente paso es Básico 2 (A1.2) · miércoles 21:00 Chile · con Jay. Si lo que quieres es hablar, también puedes entrar a Conversacional 1 con test de nivel.": "That course is now called Basic 1 (A1.1) and your certificate is equivalent to A1.1. Your next step is Basic 2 (A1.2) · Wednesday 21:00 Chile time · with Jay. If what you really want is to speak, you can also join Conversational 1 with the placement test.",
  "¿Cuántas personas hay por clase?": "How many people are in each class?",
  "Máximo 15 alumnos por clase (8 en TOPIK II y 12 en Niños). Grupos chicos para que el profesor corrija tu pronunciación personalmente.": "Maximum 15 students per class (8 in TOPIK II and 12 in Kids). Small groups so the teacher can correct your pronunciation personally.",
  "¿Recibo certificado?": "Do I get a certificate?",
  "Sí, está incluido en todos los cursos. Al completar tu curso recibes el certificado de Academia Seúl del nivel correspondiente, en base a tu asistencia y participación.": "Yes, it's included in every course. When you complete your course you receive the Academia Seúl certificate for that level, based on your attendance and participation.",
  "¿Cómo es la clase de Niños?": "What is the Kids class like?",
  "60 minutos divididos en bloques de 10–15 min (canción · juego · lectura · dibujo) con un grupo de máximo 12. Las grabaciones son privadas, solo para las familias del grupo, y el apoderado recibe un grupo de WhatsApp propio. Tu hijo/a solo necesita un computador o tablet con cámara y ganas de jugar.": "60 minutes split into 10–15 min blocks (song · game · reading · drawing) with a group of up to 12. Recordings are private, only for the group's families, and parents get their own WhatsApp group. Your child just needs a computer or tablet with a camera and the desire to play.",
  "¿En qué hora llegan las clases a mi país?": "What time are the classes in my country?",
  "Elige tu país en la grilla de horarios de esta página y verás la hora exacta. Las clases de 20:00 y 21:00 Chile caen de madrugada en España; la de Niños (18:00 Chile) llega a las 23:00 / 22:00 en España.": "Pick your country in the schedule grid on this page and you'll see the exact time. The 20:00 and 21:00 Chile time classes fall in the early morning hours in Spain; the Kids class (18:00 Chile time) is at 23:00 / 22:00 in Spain.",
  "Cursos en vivo": "Live courses",
  "Esta cohorte ya está en marcha": "This cohort is already underway",
  "Anótate en la lista de espera y te avisamos apenas se abran los cupos de la próxima cohorte ({cohorte}) — con acceso prioritario a horarios y precio.": "Join the waitlist and we'll let you know as soon as spots open for the next cohort ({cohorte}) — with priority access to schedules and pricing.",
  "Anotarme en la lista de espera →": "Join the waitlist →",
  "✅ ¡Pago recibido! Tu cupo en {curso} está confirmado. Te escribimos por correo/WhatsApp con los siguientes pasos. 🎉": "✅ Payment received! Your spot in {curso} is confirmed. We'll email/WhatsApp you with the next steps. 🎉",
  "⏳ Tu pago quedó pendiente. Apenas se acredite, confirmamos tu cupo y te avisamos.": "⏳ Your payment is pending. As soon as it clears, we'll confirm your spot and let you know.",
  "No se completó el pago. Puedes intentar de nuevo abajo o escribirnos por WhatsApp.": "The payment wasn't completed. You can try again below or message us on WhatsApp.",
  "TODOS LOS NIVELES · COHORTE OCTUBRE 2026": "ALL LEVELS · OCTOBER 2026 COHORT",
  "Matrícula octubre 2026": "October 2026 enrollment",
  "De Básico 1 a TOPIK II, y Coreano para Niños de 8 a 12 — elige tu clase.": "From Basic 1 to TOPIK II, plus Korean for Kids ages 8 to 12 — pick your class.",
  "8 semanas desde {inicio} · 1 clase en vivo por semana · 60 min · {precio} · certificado incluido": "8 weeks starting {inicio} · 1 live class per week · 60 min · {precio} · certificate included",
  "⏰ LAS CLASES EMPIEZAN EN": "⏰ CLASSES START IN",
  "DÍAS": "DAYS",
  "HORAS": "HOURS",
  "MIN": "MIN",
  "SEG": "SEC",
  "Matrícula abierta hasta el {cierre}": "Enrollment open until {cierre}",
  "Elegir mi clase": "Choose my class",
  "Ver syllabus completo": "See full syllabus",
  "Inscribir a mi hijo/a →": "Enroll my child →",
  "Reservar mi cupo →": "Reserve my spot →",
  "Toca tu caso y te decimos tu peldaño — o elige directo en el horario.": "Tap your situation and we'll point you to your step — or pick straight from the schedule.",
  "Elige tu clase": "Choose your class",
  "5 cursos · 6 horarios (Básico 1 se dicta martes y jueves: elige uno)": "5 courses · 6 time slots (Basic 1 runs Tuesday and Thursday: pick one)",
  "Tu selección": "Your selection",
  "Requiere:": "Requires:",
  "Antes se llamaba:": "Formerly called:",
  "📄 Programa PDF": "📄 Program PDF",
  "Ver syllabus semana a semana": "See the week-by-week syllabus",
  "Las 8 semanas de {curso}": "The 8 weeks of {curso}",
  "Requiere {req}": "Requires {req}",
  "desde cero": "from scratch",
  "🧒 En Niños la hora se divide en bloques de 10–15 min (canción · juego · lectura · dibujo) y la tarea es breve, para hacer con el apoderado.": "🧒 In Kids, the hour is split into 10–15 min blocks (song · game · reading · drawing) and homework is short, meant to be done with a parent or guardian.",
  "Tu equipo de profesores": "Your teaching team",
  "Nativos y bilingües, con años de experiencia enseñando coreano a hispanohablantes.": "Native and bilingual, with years of experience teaching Korean to Spanish speakers.",
  "Regístrate": "Sign up",
  "Paga": "Pay",
  "Confirma tu pago": "Confirm your payment",
  "PASO 1 · FORMULARIO DE INSCRIPCIÓN": "STEP 1 · ENROLLMENT FORM",
  "Reserva el cupo de tu hijo/a": "Reserve your child's spot",
  "Reserva tu cupo": "Reserve your spot",
  "Datos del apoderado/a": "Parent/guardian details",
  "Nombre del apoderado/a *": "Parent/guardian's name *",
  "Tu nombre y apellido": "Your first and last name",
  "Correo *": "Email *",
  "tucorreo@email.com": "you@email.com",
  "+56 9 1234 5678 (con código de país)": "+56 9 1234 5678 (with country code)",
  "País y ciudad *": "Country and city *",
  "Ej: Chile, Santiago": "E.g. Chile, Santiago",
  "Ej: {pais}, ciudad": "E.g. {pais}, city",
  "Datos del alumno/a": "Student details",
  "Nombre del niño/a *": "Child's name *",
  "Nombre completo *": "Full name *",
  "Nombre y apellido del niño/a": "Child's first and last name",
  "Edad del niño/a *": "Child's age *",
  "Edad *": "Age *",
  "Ej: 10": "E.g. 10",
  "Ej: 24": "E.g. 24",
  "Documento de identidad": "ID document",
  "(opcional)": "(optional)",
  "RUT o ID — lo pediremos al emitir el certificado": "RUT or ID — we'll ask for it when issuing your certificate",
  "¿Qué nivel de coreano tiene tu hijo/a? *": "What's your child's Korean level? *",
  "¿Cuál es tu nivel de coreano? *": "What's your Korean level? *",
  "Selecciona un nivel": "Select a level",
  "Fui alumno/a del Nivel 1 (julio 2026) — quiero seguir con Básico 2": "I was a Level 1 student (July 2026) — I want to continue with Basic 2",
  "Desde cero (no sabe nada) 🐣": "From scratch (no Korean yet) 🐣",
  "Lee algo del alfabeto (한글)": "Can read some of the alphabet (한글)",
  "Terminó Básico 1 o equivalente (lee 한글 y se presenta)": "Finished Basic 1 or equivalent (reads 한글 and can introduce themselves)",
  "Intermedio — va por el TOPIK II": "Intermediate — aiming for TOPIK II",
  "¿Cómo nos conociste? *": "How did you hear about us? *",
  "Selecciona una opción": "Select an option",
  "El Lector de Hangul": "The Hangul Reader",
  "Recomendación de un amigo": "A friend's recommendation",
  "Google / búsqueda": "Google / search",
  "Ya fui alumno/a": "I'm a former student",
  "Otro": "Other",
  "¿Por qué quiere aprender coreano?": "Why does your child want to learn Korean?",
  "¿Por qué quieres aprender coreano?": "Why do you want to learn Korean?",
  "K-pop, K-drama, un viaje, trabajo, la cultura... ¡Nos ayuda a conocerte! 💜": "K-pop, K-drama, a trip, work, the culture... It helps us get to know you! 💜",
  "Enviando...": "Sending...",
  "Reservar cupo en {curso} →": "Reserve a spot in {curso} →",
  "🔒 Tus datos están protegidos y no se comparten.": "🔒 Your information is protected and never shared.",
  "¡Cupo reservado para {nombre}!": "Spot reserved for {nombre}!",
  "ti": "you",
  "Ir a pagar ↓": "Go to payment ↓",
  "PASO 2 · PAGO": "STEP 2 · PAYMENT",
  "Completa tu pago": "Complete your payment",
  "MISMO PRECIO EN TODOS LOS CURSOS": "SAME PRICE FOR EVERY COURSE",
  "PAGO ÚNICO": "ONE-TIME PAYMENT",
  "El curso completo de 8 semanas": "The full 8-week course",
  "✓ Seleccionado": "✓ Selected",
  "{n} CUOTAS": "{n} PAYMENTS",
  "Una al inscribirte y otra al inicio del mes 2": "One when you enroll and another at the start of month 2",
  "c/u": "each",
  "Fuera de Chile se coordina por WhatsApp": "Outside Chile, we arrange it via WhatsApp",
  "Incluye:": "Includes:",
  "8 clases en vivo por Zoom (60 min c/u)": "8 live classes on Zoom (60 min each)",
  "Certificado de Academia Seúl al terminar": "Academia Seúl certificate upon completion",
  "Grabaciones privadas, solo para las familias del grupo": "Private recordings, only for the group's families",
  "Grabaciones de cada clase (24 h después)": "Recordings of every class (available within 24 h)",
  "Slides + hojas de actividad por sesión": "Slides + activity sheets for every session",
  "Lector de Hangul con audio nativo (tarea gamificada)": "Hangul Reader with native audio (gamified homework)",
  "Pronunciación corregida personalmente": "Personal pronunciation correction",
  "Grupo chico (máx. {n})": "Small group (max {n})",
  "Grupo de WhatsApp solo para apoderados": "WhatsApp group just for parents",
  "Comunidad de alumnos por WhatsApp/Discord": "Student community on WhatsApp/Discord",
  "¿Desde dónde pagas?": "Where are you paying from?",
  "🇨🇱 Chile": "🇨🇱 Chile",
  "🌎 Otro país": "🌎 Another country",
  "ELIGE CÓMO PAGAR": "CHOOSE HOW TO PAY",
  "🏦 Transferencia bancaria · Chile": "🏦 Bank transfer · Chile",
  "RECOMENDADO · SIN COMISIÓN": "RECOMMENDED · NO FEES",
  "Sin comisión: el monto llega completo ({monto} — te confirmamos el monto exacto). Escríbenos y te enviamos los datos.": "No fees: the full amount comes through ({monto} — we'll confirm the exact amount). Message us and we'll send you the bank details.",
  "{clp} por cuota": "{clp} per payment",
  "📲 Pedir datos por WhatsApp": "📲 Request bank details on WhatsApp",
  "o paga al instante con": "or pay instantly with",
  "Abriendo pago seguro…": "Opening secure payment…",
  "💳 Tarjeta de crédito / débito · Mercado Pago ({plan})": "💳 Credit / debit card · Mercado Pago ({plan})",
  "Visa, Mastercard y débito · se cobra el equivalente en CLP. Reserva tu cupo arriba antes de pagar.": "Visa, Mastercard and debit · charged as the equivalent in CLP. Reserve your spot above before paying.",
  "🌐 Tarjeta en tu moneda (USD/EUR/local) · Hotmart": "🌐 Card in your currency (USD/EUR/local) · Hotmart",
  "💳 Mercado Pago ({plan})": "💳 Mercado Pago ({plan})",
  "Se cobra en pesos chilenos; tu banco puede cobrar comisión por cambio de moneda.": "Charged in Chilean pesos; your bank may charge a currency conversion fee.",
  "¿Prefieres transferencia internacional?": "Prefer an international transfer?",
  "Escríbenos por WhatsApp": "Message us on WhatsApp",
  "PASO 3 · CONFIRMA": "STEP 3 · CONFIRM",
  "¿Ya hiciste tu pago?": "Already made your payment?",
  "Mercado Pago (tarjeta)": "Mercado Pago (card)",
  "Transferencia bancaria": "Bank transfer",
  "Ya pagué con {metodo}": "I paid with {metodo}",
  "Enviando confirmación…": "Sending confirmation…",
  "¡Gracias, {nombre}! Registramos tu pago.": "Thanks, {nombre}! We've recorded your payment.",
  "¡Gracias! Registramos tu pago.": "Thanks! We've recorded your payment.",
  "Verificamos y te confirmamos el cupo por correo/WhatsApp en las próximas horas. 화이팅!": "We'll verify it and confirm your spot by email/WhatsApp within the next few hours. 화이팅!",
  "🔒 Certificado incluido · Grabaciones incluidas · Tu información está protegida": "🔒 Certificate included · Recordings included · Your information is protected",
  "¿Listo para empezar?": "Ready to get started?",
  "Las clases arrancan {inicio} — {precio}. Certificado incluido.": "Classes start {inicio} — {precio}. Certificate included.",
  "Hola Jay! Tengo una duda sobre los cursos de octubre.": "Hi Jay! I have a question about the October courses.",
  "💬 Hablar con Jay primero": "💬 Talk to Jay first",
  "화이팅 chingu! Nos vemos {inicio}.": "화이팅 chingu! See you {inicio}.",
  "🌍 PayPal · en dólares ({monto})": "🌍 PayPal · in US dollars ({monto})",
  "US${m} por cuota": "US${m} per payment",
  "🌍 PayPal en {n} cuotas · te enviamos el link por WhatsApp": "🌍 PayPal in {n} payments · we'll send you the link on WhatsApp",
  "{curso} · {dia} {hora} Chile. Te escribimos a **{correo}**. Ahora elige cómo pagar abajo para confirmar el lugar.": "{curso} · {dia} {hora} Chile time. We'll email you at **{correo}**. Now choose how to pay below to confirm your spot.",
  "Recomendado fuera de Chile · pagas en dólares con cualquier tarjeta, **sin cuenta PayPal** (opción “Pagar con tarjeta”).": "Recommended outside Chile · pay in US dollars with any card, **no PayPal account needed** (“Pay with card” option).",
  "Cuando termines en PayPal, vuelve a esta pestaña y toca **“Ya pagué con PayPal”** para que reservemos tu cupo.": "When you're done in PayPal, come back to this tab and tap **“I paid with PayPal”** so we can reserve your spot.",
  "Confírmalo aquí y reservamos el cupo en **{curso}**. Te escribimos por correo/WhatsApp para darte la bienvenida.": "Confirm it here and we'll reserve your spot in **{curso}**. We'll reach out by email/WhatsApp to welcome you.",
  // ── app/notificarme/page.tsx
  "Básico 1 (A1.1)": "Basic 1 (A1.1)",
  "Básico 2 (A1.2)": "Basic 2 (A1.2)",
  "Conversacional 1 (A2.1)": "Conversational 1 (A2.1)",
  "Coreano para Niños (8–12)": "Korean for Kids (8–12)",
  "TOPIK II (B1+)": "TOPIK II (B1+)",
  "Conversacional 2 (A2.2)": "Conversational 2 (A2.2)",
  "los próximos cursos": "the upcoming courses",
  "Argentina": "Argentina",
  "Bolivia": "Bolivia",
  "Chile": "Chile",
  "Colombia": "Colombia",
  "Costa Rica": "Costa Rica",
  "Cuba": "Cuba",
  "Ecuador": "Ecuador",
  "El Salvador": "El Salvador",
  "España": "Spain",
  "Estados Unidos": "United States",
  "Guatemala": "Guatemala",
  "Honduras": "Honduras",
  "México": "Mexico",
  "Nicaragua": "Nicaragua",
  "Panamá": "Panama",
  "Paraguay": "Paraguay",
  "Perú": "Peru",
  "Puerto Rico": "Puerto Rico",
  "República Dominicana": "Dominican Republic",
  "Uruguay": "Uruguay",
  "Venezuela": "Venezuela",
  "Cero, nunca estudié": "Zero, I've never studied",
  "Sé leer el alfabeto (한글)": "I can read the alphabet (한글)",
  "Nivel A1 básico": "A1 basic level",
  "Terminé Básico 1 o equivalente": "I finished Basic 1 or equivalent",
  "Nivel A2 o intermedio": "A2 or intermediate level",
  "Nivel B1 o superior": "B1 level or higher",
  "K-pop / K-dramas": "K-pop / K-dramas",
  "Viajar a Corea": "Traveling to Korea",
  "Trabajo o negocios": "Work or business",
  "Pareja o familia coreana": "Korean partner or family",
  "Cultura coreana en general": "Korean culture in general",
  "Estudiar en Corea (TOPIK)": "Studying in Korea (TOPIK)",
  "Hubo un problema al enviarte. Intenta nuevamente.": "There was a problem submitting your info. Please try again.",
  "¡Listo, {nombre}!": "All set, {nombre}!",
  "Te aviso apenas abramos cupos de": "I'll let you know as soon as we open spots for",
  "Recibirás un email con acceso prioritario a horarios y cupos.": "You'll get an email with priority access to schedules and spots.",
  "← Volver al inicio": "← Back to home",
  "🎓 ¡Buenas noticias! {curso} ya tiene matrícula abierta.": "🎓 Good news! Enrollment for {curso} is already open.",
  "Las clases empiezan {inicio} de 2026 — 8 semanas, certificado incluido, {precio}. No necesitas lista de espera: elige tu horario y reserva tu cupo.": "Classes start {inicio}, 2026 — 8 weeks, certificate included, {precio}. No waitlist needed: pick your schedule and reserve your spot.",
  "Inscribirme · Octubre 2026 →": "Enroll · October 2026 →",
  "¿Prefieres que te avisemos para una cohorte futura? Deja tus datos abajo.": "Would you rather be notified about a future cohort? Leave your details below.",
  "Lista de espera": "Waitlist",
  "Te avisamos cuando lance": "We'll let you know when it launches",
  "Sé el/la primer/a en saber cuando abramos cupos. Los miembros de la lista de espera tienen acceso prioritario a horarios y cupos.": "Be the first to know when we open spots. Waitlist members get priority access to schedules and spots.",
  "Tu nombre": "Your name",
  "Cómo te llamamos": "What should we call you",
  "Tu email": "Your email",
  "donde te avisamos": "where we'll notify you",
  "Tu teléfono / WhatsApp": "Your phone / WhatsApp",
  "Tu país": "Your country",
  "Selecciona tu país": "Select your country",
  "¿Cuál es tu nivel de coreano?": "What's your Korean level?",
  "Selecciona tu nivel": "Select your level",
  "Mensaje adicional": "Additional message",
  "Cuéntanos algo más, si quieres": "Tell us a bit more, if you'd like",
  "💌 Apúntame a la lista de espera": "💌 Add me to the waitlist",
  "Sin spam. Sin cargos. Solo te avisamos cuando lancemos.": "No spam. No charges. We'll only reach out when we launch.",
  "¿Prefieres hablar directo? Escríbele a Jay por WhatsApp:": "Prefer to talk directly? Message Jay on WhatsApp:",
  "Hola Jay! Quiero más información sobre {curso}.": "Hi Jay! I'd like more information about {curso}.",
  "💬 Hablar con Jay por WhatsApp": "💬 Chat with Jay on WhatsApp",
  "¿Quieres empezar YA? Aprende a leer coreano gratis con el Lector de Hangul:": "Want to start NOW? Learn to read Korean for free with the Hangul Reader:",
  "🐯 Lector de Hangul — gratis con audio nativo →": "🐯 Hangul Reader — free with native audio →",
  "Cargando...": "Loading...",
  // ── app/test-nivel/page.tsx
  "¿Puedes leer esto?": "Can you read this?",
  "Ni idea, son dibujitos para mí": "No idea, they're just squiggles to me",
  "Reconozco alguna letra": "I recognize a letter or two",
  "Sí, dice \"annyeong\"": "Yes, it says \"annyeong\"",
  "¿Sabes qué es el 한글 (hangul)?": "Do you know what 한글 (Hangul) is?",
  "No": "No",
  "He oído el término": "I've heard the term",
  "Es el alfabeto coreano, claro": "It's the Korean alphabet, of course",
  "¿Has estudiado coreano antes?": "Have you studied Korean before?",
  "Nunca, parto de cero": "Never, I'm starting from scratch",
  "Por mi cuenta (apps, videos)": "On my own (apps, videos)",
  "En clases o academia": "In classes or at a school",
  "La partícula 은/는, ¿para qué sirve?": "What is the particle 은/는 for?",
  "No tengo idea": "I have no idea",
  "Creo que marca el tema de la frase": "I think it marks the topic of the sentence",
  "Sí, marca el tema/sujeto": "Yes, it marks the topic/subject",
  "¿Puedes presentarte en coreano? (저는 ...이에요)": "Can you introduce yourself in Korean? (저는 ...이에요)",
  "Para nada": "Not at all",
  "Más o menos, con ayuda": "Sort of, with help",
  "Sí, sin problema": "Yes, no problem",
  "🎵 Entender K-pop y K-dramas": "🎵 Understand K-pop and K-dramas",
  "✈️ Viajar o vivir en Corea": "✈️ Travel to or live in Korea",
  "📜 Dar el examen TOPIK": "📜 Take the TOPIK exam",
  "💜 Hobby y cultura": "💜 Hobby and culture",
  "Principiante total": "Total beginner",
  "Estás partiendo desde cero — el lugar perfecto para empezar bien. Básico 1 (A1.1) te enseña a leer hangul en la primera semana y a construir tus primeras frases. Martes o jueves 20:00 (Chile), desde la semana del 5 de octubre.": "You're starting from scratch — the perfect place to start off right. Basic 1 (A1.1) teaches you to read Hangul in the first week and build your first sentences. Tuesday or Thursday at 20:00 (Chile time), starting the week of October 5.",
  "Básico 1 (A1.1) · desde cero": "Basic 1 (A1.1) · from scratch",
  "Falso principiante": "False beginner",
  "Ya tienes contacto con el idioma, pero te faltan bases ordenadas. Básico 1 te llena los huecos y te da estructura para avanzar de verdad — y si ya lees hangul con soltura, Básico 2 (miércoles 21:00) es tu curso.": "You've already had some contact with the language, but you're missing an organized foundation. Basic 1 fills in the gaps and gives you the structure to really move forward — and if you already read Hangul fluently, Basic 2 (Wednesday 21:00) is your course.",
  "Básico 1 (A1.1) · o Básico 2 si ya lees hangul": "Basic 1 (A1.1) · or Basic 2 if you already read Hangul",
  "Tienes bases": "You have a foundation",
  "Vas bien. Básico 2 (A1.2, miércoles 21:00) te lleva al pasado y al futuro; si ya conversas, Conversacional 1 (A2.1) con profesora nativa (martes 21:00) es para ti. ¿Vas por el examen? TOPIK II (B1+), jueves 21:00.": "You're doing well. Basic 2 (A1.2, Wednesday 21:00) takes you into the past and future tenses; if you can already hold a conversation, Conversational 1 (A2.1) with a native teacher (Tuesday 21:00) is for you. Going for the exam? TOPIK II (B1+), Thursday 21:00.",
  "Básico 2 (A1.2) · Conversacional 1 (A2.1) · o TOPIK II (B1+)": "Basic 2 (A1.2) · Conversational 1 (A2.1) · or TOPIK II (B1+)",
  "Test de nivel": "Placement test",
  "¿Qué nivel de coreano": "What's your Korean",
  "tienes": "level",
  "5 preguntas rápidas. Te decimos por dónde empezar (y te mandamos tu guía gratis).": "5 quick questions. We'll tell you where to start (and send you your free guide).",
  "Pregunta {n} de {total}": "Question {n} of {total}",
  "Última: ¿cuál es tu meta principal?": "Last one: what's your main goal?",
  "¡Listo! Tu resultado está calculado.": "Done! Your result is ready.",
  "Tu correo": "Your email",
  "Calculando…": "Calculating…",
  "Ver mi resultado →": "See my result →",
  "🔒 Sin spam. Solo tu resultado y tips de coreano.": "🔒 No spam. Just your result and Korean tips.",
  "Tu resultado · {score}/10": "Your result · {score}/10",
  "Recomendado para ti": "Recommended for you",
  "Tu meta: {goal}": "Your goal: {goal}",
  "Descargar mi guía": "Download my guide",
  "Déjanos dónde enviarte tu resultado + la **guía del alfabeto gratis** y lo ves al instante.": "Tell us where to send your result + the **free alphabet guide** and you'll see it instantly.",
  // ── components/About.tsx
  "Profesores coreanos nativos": "Native Korean teachers",
  "Bilingües coreano-español": "Bilingual in Korean and Spanish",
  "Años enseñando coreano": "Years teaching Korean",
  "Experiencia comprobada": "Proven experience",
  "Método propio": "Our own method",
  "Diseñado para hispanohablantes": "Designed for Spanish speakers",
  "Cursos diseñados": "Courses designed",
  "De A1.1 a TOPIK II (B1+) + Niños": "From A1.1 to TOPIK II (B1+) + Kids",
  "Sobre la academia": "About the school",
  "Donde el idioma": "Where the language",
  "encuentra su hogar": "finds its home",
  "Estudiantes aprendiendo en grupo (imagen ilustrativa)": "Students learning in a group (illustrative image)",
  "Nacimos del amor por la cultura coreana y la convicción de que aprender un idioma es una de las experiencias más transformadoras de la vida.": "We were born from a love of Korean culture and the conviction that learning a language is one of life's most transformative experiences.",
  "Una nueva forma de aprender coreano desde Latinoamérica: profesores coreanos nativos y bilingües, materiales creados para hispanohablantes y una metodología que combina conversación real, cultura contemporánea y preparación académica.": "A new way to learn Korean from Latin America: native, bilingual Korean teachers, materials created for Spanish speakers, and a methodology that combines real conversation, contemporary culture and academic preparation.",
  "Aquí no solo aprendes un idioma — descubres una cultura entera: K-dramas, K-pop, gastronomía, historia y la energía única de Corea del Sur.": "Here you don't just learn a language — you discover an entire culture: K-dramas, K-pop, food, history and the unique energy of South Korea.",
  "Profesores coreanos nativos y bilingües": "Native, bilingual Korean teachers",
  "Grupos reducidos: máximo 15 estudiantes": "Small groups: 15 students max",
  "Metodología comunicativa + cultural": "Communicative + cultural methodology",
  "Preparación oficial para el examen TOPIK": "Official TOPIK exam preparation",
  "Conoce nuestra historia": "Read our story",
  "años enseñando coreano\na hispanohablantes": "years teaching Korean\nto Spanish speakers",
  // ── components/Benefits.tsx
  "Aprende la pronunciación y el acento real desde el primer día. Nuestros profesores son coreanos nativos y bilingües, y traen la cultura viva al aula.": "Learn real pronunciation and accent from day one. Our teachers are native, bilingual Koreans who bring living culture into the classroom.",
  "Grupos reducidos": "Small groups",
  "Máximo 15 estudiantes por clase (8 en TOPIK II, 12 en Niños). Más tiempo de práctica oral, más feedback personalizado y un ambiente donde realmente puedes equivocarte y aprender.": "A maximum of 15 students per class (8 in TOPIK II, 12 in Kids). More speaking time, more personalized feedback, and a space where you can actually make mistakes and learn.",
  "Metodología innovadora": "Innovative methodology",
  "Combinamos comunicación oral, gramática funcional y cultura contemporánea. Sin aburrimiento. Sin memorizar tablas interminables.": "We combine spoken communication, functional grammar and contemporary culture. No boredom. No memorizing endless tables.",
  "TOPIK II (B1+): preparación oficial": "TOPIK II (B1+): official preparation",
  "Somos tu puerta al certificado internacional TOPIK I y TOPIK II. Te preparamos con simulacros, estrategias y material oficial.": "We're your gateway to the international TOPIK I and TOPIK II certificates. We prepare you with mock exams, strategies and official materials.",
  "Grabaciones incluidas": "Recordings included",
  "¿Te pierdes una clase? Recibes la grabación en 24 horas. Todas las clases son 100% online en vivo por Zoom.": "Miss a class? You get the recording within 24 hours. All classes are 100% online and live on Zoom.",
  "Materiales incluidos": "Materials included",
  "Slides, hojas de actividad y el Lector de Hangul con audio nativo, incluidos en cada curso. Sin comprar libros.": "Slides, activity sheets and the Hangul Reader with native audio, included in every course. No books to buy.",
  "Comunidad vibrante": "Vibrant community",
  "Sé parte de la comunidad Chingu: alumnos de toda Latinoamérica y España aprendiendo coreano juntos.": "Be part of the Chingu community: students from all over Latin America and Spain learning Korean together.",
  "Certificado por participación": "Certificate of participation",
  "Al completar tu curso recibes el certificado de Academia Seúl de tu nivel (A1.1, A1.2, A2.1, TOPIK II o Niños). Tu avance queda respaldado peldaño a peldaño.": "When you complete your course, you receive the Academia Seúl certificate for your level (A1.1, A1.2, A2.1, TOPIK II or Kids). Your progress is certified step by step.",
  "¿Por qué elegirnos?": "Why choose us?",
  "Todo lo que necesitas": "Everything you need",
  "para": "to",
  "hablar coreano": "speak Korean",
  "No somos una academia más. Una nueva forma de aprender coreano desde Latinoamérica, diseñada para hispanohablantes.": "We're not just another school. A new way to learn Korean from Latin America, designed for Spanish speakers.",
  // ── components/CTASection.tsx
  "¿Listo para hablar": "Ready to speak",
  "coreano de verdad?": "real Korean?",
  "La matrícula de octubre está abierta: clases en vivo desde la semana del 5 de octubre, 8 semanas, certificado incluido. US$150 el curso completo o 2 cuotas de US$75 — elige tu nivel y tu horario.": "October enrollment is open: live classes starting the week of October 5, 8 weeks, certificate included. US$150 for the full course or 2 payments of US$75 — pick your level and your schedule.",
  "Explorar cursos": "Explore courses",
  "✓ US$150 el curso · o 2 cuotas de US$75": "✓ US$150 per course · or 2 payments of US$75",
  "✓ Grabaciones incluidas": "✓ Recordings included",
  "✓ Máx. 15 alumnos (8 en TOPIK II · 12 en Niños)": "✓ Max 15 students (8 in TOPIK II · 12 in Kids)",
  "✓ Certificado incluido": "✓ Certificate included",
  // ── components/Contact.tsx
  "Desde cero (nunca estudié)": "From scratch (never studied)",
  "Leo Hangul y me presento (Básico 1 hecho)": "I read Hangul and can introduce myself (Basic 1 done)",
  "Fui alumno/a del Nivel 1 de julio": "I took Level 1 in July",
  "Converso algo (A2)": "I can hold a basic conversation (A2)",
  "Intermedio · voy por el TOPIK II": "Intermediate · going for TOPIK II",
  "No sé mi nivel": "I don't know my level",
  "K-pop / K-drama": "K-pop / K-drama",
  "Viaje a Corea": "Trip to Korea",
  "No sé, ayúdenme a elegir": "Not sure, help me choose",
  "Hola Jay! Vi academiaseul.com y quiero información sobre los cursos de coreano.": "Hi Jay! I saw academiaseul.com and I'd like more info about the Korean courses.",
  "Hubo un problema al enviar tu mensaje. Por favor intenta nuevamente.": "There was a problem sending your message. Please try again.",
  "Contáctanos": "Contact us",
  "¿Quieres hablar": "Want to talk",
  "con un profesor?": "to a teacher?",
  "¿Tienes dudas o quieres saber qué curso te conviene? Lo más rápido es escribirle a Jay por WhatsApp — o déjanos el formulario y te respondemos en menos de 24 h.": "Have questions or want to know which course is right for you? The fastest way is to message Jay on WhatsApp — or fill out the form and we'll get back to you in under 24 hours.",
  "¡Mensaje recibido!": "Message received!",
  "Te escribimos en las próximas 24 h con toda la información. ¡Hasta pronto!": "We'll write to you within the next 24 hours with all the details. See you soon!",
  "Ej. María González": "E.g. María González",
  "Teléfono / WhatsApp": "Phone / WhatsApp",
  "Correo electrónico *": "Email *",
  "Nivel actual": "Current level",
  "Me interesa": "I'm interested in",
  "Selecciona un interés": "Select an interest",
  "Mensaje (opcional)": "Message (optional)",
  "Cuéntanos sobre tus objetivos, disponibilidad o cualquier pregunta...": "Tell us about your goals, availability or any questions...",
  "Hablar con un profesor →": "Talk to a teacher →",
  "Al enviar aceptas ser contactado por Academia Seúl. No compartimos tus datos.": "By submitting, you agree to be contacted by Academia Seúl. We never share your data.",
  "Información de contacto": "Contact information",
  "Email": "Email",
  "Dirección": "Address",
  "Síguenos": "Follow us",
  "Horarios de atención": "Office hours",
  "Lunes – Viernes": "Monday – Friday",
  "Sábados": "Saturdays",
  "Domingos": "Sundays",
  "Cerrado": "Closed",
  "Escribirle a Jay por WhatsApp · +56 9 4211 5562": "Message Jay on WhatsApp · +56 9 4211 5562",
  // ── components/Courses.tsx
  "Niños 8–12": "Kids 8–12",
  "Paso {n} · {cefr}": "Step {n} · {cefr}",
  "Matrícula abierta": "Enrollment open",
  "antes: {alias}": "formerly: {alias}",
  "Horario": "Schedule",
  "Profe": "Teacher",
  "Duración": "Duration",
  "8 semanas · 60 min": "8 weeks · 60 min",
  "Precio": "Price",
  "Inscribir a mi hijo/a": "Enroll my child",
  "Inscribirme en {curso}": "Enroll in {curso}",
  "Cohorte octubre 2026": "October 2026 cohort",
  "Encuentra tu": "Find your",
  "peldaño": "step",
  "5 cursos · 6 horarios · 8 semanas desde la semana del 5 de octubre.": "5 courses · 6 time slots · 8 weeks starting the week of October 5.",
  "— mismo precio en todos los cursos.": "— same price for every course.",
  "Adultos · la escalera": "Adults · the ladder",
  "Niños 8–12 · ruta propia": "Kids 8–12 · their own track",
  "Próximamente · enero 2027": "Coming soon · January 2027",
  "La continuación de Conversacional 1: educación y suneung, la oficina coreana, mitos, Seollal y Chuseok, K-drama. Para quienes terminen A2.1 en noviembre.": "The follow-up to Conversational 1: education and the suneung, the Korean office, myths, Seollal and Chuseok, K-drama. For those who finish A2.1 in November.",
  "Avísame cuando abra": "Notify me when it opens",
  "Inscribirme en mi clase": "Enroll in my class",
  "Test de nivel gratuito": "Free placement test",
  "¿Nunca estudiaste coreano? Tu curso es **Básico 1**. ¿Ya sabes algo? Haz el test de nivel.": "Never studied Korean? Your course is **Basic 1**. Already know some? Take the placement test.",
  // ── components/EquipoProfes.tsx
  "tu profe": "your teacher",
  // ── components/Escalera.tsx
  "Nunca estudié coreano": "I've never studied Korean",
  "Tu curso es Básico 1 (A1.1): empiezas leyendo el alfabeto y terminas presentándote.": "Your course is Basic 1 (A1.1): you start by reading the alphabet and finish by introducing yourself.",
  "Ya leo Hangul": "I can read Hangul",
  "Si ya lees 한글 y te presentas, tu curso es Básico 2 (A1.2): del presente al pasado y al futuro.": "If you can already read 한글 and introduce yourself, your course is Basic 2 (A1.2): from the present to the past and the future.",
  "Terminé el Nivel 1 de julio": "I finished Level 1 (July)",
  "¿Fuiste alumno/a del Nivel 1 en julio? Ese curso hoy se llama Básico 1 (A1.1). Tu siguiente paso es Básico 2 (A1.2) · miércoles 21:00 Chile · con Jay.": "Were you a Level 1 student in July? That course is now called Basic 1 (A1.1). Your next step is Basic 2 (A1.2) · Wednesday 21:00 Chile time · with Jay.",
  "Quiero hablar": "I want to speak",
  "Con Básico 2 terminado (o test de nivel), Conversacional 1 (A2.1) con la Prof.ª Abby: puro hablar con una nativa.": "Once you've finished Basic 2 (or taken the placement test), it's Conversational 1 (A2.1) with teacher Abby: pure speaking practice with a native speaker.",
  "Voy por el TOPIK": "I'm going for TOPIK",
  "Grupo de máximo 8 enfocado 100% en el examen oficial: TOPIK II (B1+) · jueves 21:00 Chile · con Jay.": "A group of 8 max, 100% focused on the official exam: TOPIK II (B1+) · Thursday 21:00 Chile time · with Jay.",
  "Es para mi hijo/a": "It's for my child",
  "Coreano para Niños (8–12): lunes 18:00 Chile, juegos, canciones y un show final para la familia.": "Korean for Kids (8–12): Monday 18:00 Chile time, games, songs and a final show for the family.",
  "Abre en {cuando}": "Opens in {cuando}",
  "¿Cuál es tu caso?": "Which one sounds like you?",
  "Ir a {curso} →": "Go to {curso} →",
  "enero 2027": "January 2027",
  "paso {n}": "Step {n}",
  "tu curso": "your course",
  "carril propio para niños y niñas": "a track of their own for kids",
  // ── components/FAQ.tsx
  "¿Necesito saber algo de coreano para empezar?": "Do I need to know any Korean to start?",
  "No. Básico 1 (A1.1) y Coreano para Niños están pensados para empezar desde cero: lo primero que aprendes es a leer el alfabeto (한글). Si ya sabes algo, tienes Básico 2 (A1.2), Conversacional 1 (A2.1) y TOPIK II — haz el test de nivel gratuito o escríbenos y te ubicamos en 5 minutos.": "No. Basic 1 (A1.1) and Korean for Kids are designed for starting from scratch: the first thing you learn is how to read the alphabet (한글). If you already know some Korean, there's Basic 2 (A1.2), Conversational 1 (A2.1) and TOPIK II — take the free placement test or message us and we'll place you in 5 minutes.",
  "¿Cuánto cuesta y qué incluye?": "How much does it cost and what's included?",
  "Mismo precio en todos los cursos: US$150 el curso completo o 2 cuotas de US$75. Incluye las 8 clases en vivo (60 min), grabaciones, material de estudio, el Lector de Hangul, certificado de Academia Seúl y acceso a la comunidad. El programa completo está en /programa.": "Same price for every course: US$150 for the full course or 2 payments of US$75. It includes the 8 live classes (60 min), recordings, study materials, the Hangul Reader, an Academia Seúl certificate and access to the community. The full program is at /programa.",
  "¿Cómo puedo pagar?": "How can I pay?",
  "Transferencia bancaria en Chile (sin comisión), tarjeta de crédito/débito vía Mercado Pago (se cobra en pesos chilenos) o PayPal en dólares — también con tarjeta, sin tener cuenta PayPal. Puedes pagar los US$150 de una vez o en 2 cuotas de US$75. Te confirmamos por correo apenas registramos tu pago.": "Bank transfer in Chile (no fees), credit/debit card via Mercado Pago (charged in Chilean pesos) or PayPal in US dollars — also by card, no PayPal account needed. You can pay the US$150 all at once or in 2 payments of US$75. We'll confirm by email as soon as we register your payment.",
  "¿Qué horarios y fechas hay?": "What are the schedules and dates?",
  "La cohorte parte la semana del 5 de octubre de 2026 y dura 8 semanas (una clase por semana, hora de Chile): Coreano para Niños lunes 18:00 · Básico 1 martes 20:00 o jueves 20:00 · Conversacional 1 martes 21:00 · Básico 2 miércoles 21:00 · TOPIK II jueves 21:00. Conversión rápida: 20:00 Chile = 18:00 Colombia/Perú · 17:00 México · 20:00 Argentina · 19:00 EE.UU. Este · 01:00 España. En la página de inscripción eliges tu país y ves la hora exacta.": "The cohort starts the week of October 5, 2026 and runs for 8 weeks (one class per week, Chile time): Korean for Kids Monday 18:00 · Basic 1 Tuesday 20:00 or Thursday 20:00 · Conversational 1 Tuesday 21:00 · Basic 2 Wednesday 21:00 · TOPIK II Thursday 21:00. Quick conversion: 20:00 Chile = 18:00 Colombia/Peru · 17:00 Mexico · 20:00 Argentina · 19:00 USA Eastern · 01:00 Spain. On the enrollment page you pick your country and see the exact time.",
  "En vivo por Zoom, en grupos pequeños con cupos limitados. Así resolvemos dudas al momento y corregimos tu pronunciación en tiempo real. Si te pierdes alguna, recibes la grabación en 24 horas y puedes escribirnos para resolver dudas de esa clase.": "Live on Zoom, in small groups with limited spots. That way we answer your questions on the spot and correct your pronunciation in real time. If you miss a class, you get the recording within 24 hours and can message us with any questions about that class.",
  "Ese curso hoy se llama Básico 1 (A1.1) y tu certificado equivale a A1.1. Tu siguiente paso es Básico 2 (A1.2) · miércoles 21:00 Chile · con Jay. Si lo que quieres es hablar, también puedes entrar a Conversacional 1 (A2.1) con el test de nivel.": "That course is now called Basic 1 (A1.1), and your certificate is equivalent to A1.1. Your next step is Basic 2 (A1.2) · Wednesday 21:00 Chile time · with Jay. If what you really want is to speak, you can also join Conversational 1 (A2.1) via the placement test.",
  "¿Me sirve para el examen TOPIK?": "Will it help me with the TOPIK exam?",
  "Sí. Nuestra escalera está alineada con el marco CEFR y el TOPIK: Básico 1 y 2 te llevan al TOPIK I, y el grupo TOPIK II (jueves 21:00 Chile) está enfocado 100% en el examen oficial, con corrección de escritura y simulacros.": "Yes. Our ladder is aligned with the CEFR framework and TOPIK: Basic 1 and 2 take you to TOPIK I, and the TOPIK II group (Thursday 21:00 Chile time) is 100% focused on the official exam, with writing correction and mock exams.",
  "¿Desde qué países puedo tomar las clases?": "Which countries can I take the classes from?",
  "Desde toda Latinoamérica, España y EE.UU. Las clases son 100% online por Zoom; solo necesitas internet y ganas de aprender. Los horarios están en hora de Chile y en la página de inscripción los ves convertidos a tu país.": "From all of Latin America, Spain and the USA. Classes are 100% online on Zoom; all you need is an internet connection and the desire to learn. Schedules are in Chile time, and on the enrollment page you see them converted to your country.",
  "¿Recibo un certificado?": "Do I get a certificate?",
  "Sí, está incluido en todos los cursos. Al completar tu curso recibes el certificado de Academia Seúl del nivel correspondiente (Básico 1 · A1.1, Básico 2 · A1.2, Conversacional 1 · A2.1, TOPIK II o Niños), en base a tu asistencia y participación. Si tienes el certificado Nivel 1 (cohorte julio 2026), equivale a Básico 1 (A1.1) y te habilita directo para Básico 2.": "Yes, it's included in every course. When you complete your course you receive the Academia Seúl certificate for your level (Basic 1 · A1.1, Basic 2 · A1.2, Conversational 1 · A2.1, TOPIK II or Kids), based on your attendance and participation. If you have the Level 1 certificate (July 2026 cohort), it's equivalent to Basic 1 (A1.1) and qualifies you to go straight into Basic 2.",
  "FAQ · Preguntas frecuentes": "FAQ · Frequently asked questions",
  "Todo lo que": "Everything you",
  "quieres saber": "want to know",
  "Ver todas las preguntas →": "See all questions →",
  "Escríbenos por WhatsApp →": "Message us on WhatsApp →",
  // ── components/FaqContent.tsx
  "Hola Jay! Vi academiaseul.com y tengo una duda sobre los cursos de coreano.": "Hi Jay! I saw academiaseul.com and I have a question about the Korean courses.",
  "질문 · Preguntas frecuentes": "질문 · FAQ",
  "Si después de leer esto te queda alguna duda, escríbenos: te respondemos personalmente.": "If you still have questions after reading this, message us: we'll answer you personally.",
  "¿Tienes otra duda?": "Have another question?",
  // ── components/Footer.tsx
  "Cursos": "Courses",
  "Coreano para Niños": "Korean for Kids",
  "Inscripción octubre 2026": "October 2026 enrollment",
  "Academia": "Academy",
  "Sobre nosotros": "About us",
  "Nuestro método": "Our method",
  "Por qué Academia Seúl": "Why Academia Seúl",
  "Cultura coreana": "Korean culture",
  "Blog": "Blog",
  "Programa y syllabus": "Program & syllabus",
  "Legal": "Legal",
  "Política de privacidad": "Privacy policy",
  "Términos y condiciones": "Terms and conditions",
  "Aprende coreano con un": "Learn Korean with a",
  "Academia online de coreano para hispanohablantes. Profesores nativos, método Chingu y una comunidad apasionada por la cultura coreana.": "Online Korean school for Spanish speakers. Native teachers, the Chingu Method and a community passionate about Korean culture.",
  "Santiago, Chile · Clases online por Zoom": "Santiago, Chile · Online classes on Zoom",
  "© {y} Academia Seúl. Todos los derechos reservados.": "© {y} Academia Seúl. All rights reserved.",
  "El futuro de la enseñanza del coreano": "The future of Korean language teaching",
  // ── components/Hero.tsx
  "Puerta Gwanghwamun del palacio Gyeongbokgung, Seúl": "Gwanghwamun Gate at Gyeongbokgung Palace, Seoul",
  "Aprende coreano.": "Learn Korean.",
  "Entra en Corea.": "Step into Korea.",
  "Clases de coreano en vivo, diseñadas para hispanohablantes. Aprende a leer": "Live Korean classes designed for Spanish speakers. Learn to read",
  "desde cero, habla desde tus primeras clases y entiende la cultura detrás del idioma — con Jay y un equipo de profesoras coreanas nativas.": "from scratch, speak from your very first classes and understand the culture behind the language — with Jay and a team of native Korean teachers.",
  "Matrícula abierta · 8 semanas desde la semana del 5 de octubre · US$150 el curso completo o 2 cuotas de US$75 · certificado incluido.": "Enrollment open · 8 weeks starting the week of October 5 · US$150 for the full course or 2 payments of US$75 · certificate included.",
  "Inscribirme · Octubre 2026": "Enroll · October 2026",
  "Ver programa y horarios": "See program and schedule",
  "¿Nunca estudiaste coreano? Tu curso es": "Never studied Korean? Your course is",
  "Básico 1 (A1.1) →": "Basic 1 (A1.1) →",
  "martes o jueves, empiezas leyendo el alfabeto.": "Tuesday or Thursday, and you start by reading the alphabet.",
  "¿Quieres adelantar antes de octubre?": "Want a head start before October?",
  "Lector de Hangul gratis": "Free Hangul Reader",
  "Nunca estudié → Básico 1": "I've never studied → Basic 1",
  "Ya leo Hangul → Básico 2": "I can read Hangul → Basic 2",
  "Terminé el Nivel 1 → Básico 2": "I finished Level 1 → Basic 2",
  "Quiero hablar → Conversacional 1": "I want to speak → Conversational 1",
  "Voy por el TOPIK → TOPIK II": "I'm going for TOPIK → TOPIK II",
  "🧒 Niños 8–12 · lunes 18:00": "🧒 Kids 8–12 · Monday 18:00",
  "🇰🇷 Profesores coreanos nativos": "🇰🇷 Native Korean teachers",
  "🎥 En vivo por Zoom": "🎥 Live on Zoom",
  "👥 Grupos pequeños": "👥 Small groups",
  "🌎 LATAM y España": "🌎 LATAM and Spain",
  "Descubre más — desplazar hacia abajo": "Discover more — scroll down",
  "Descubre más": "Discover more",
  // ── components/HomeBanners.tsx
  "Guía del alfabeto coreano (한글) — gratis": "Korean alphabet (한글) guide — free",
  "Descárgala y aprende a leer desde cero, junto a más recursos gratuitos.": "Download it and learn to read from scratch, along with more free resources.",
  "Ver recursos gratis →": "See free resources →",
  "¿Tienes dudas? Hablemos.": "Have questions? Let's talk.",
  "💬 Escribir a Jay por WhatsApp →": "💬 Message Jay on WhatsApp →",
  // ── components/HorarioSemanal.tsx
  "Horarios en": "Class times in",
  "convertidos desde hora de Chile": "converted from Chile time",
  "Hora": "Time",
  "máx. {n}": "max {n}",
  "✓ Seleccionada": "✓ Selected",
  "5 cursos · 6 horarios (Básico 1 se dicta martes y jueves: elige uno) · todas las clases parten la semana del 5 de octubre · 8 semanas · 60 min.": "5 courses · 6 time slots (Basic 1 runs Tuesday and Thursday: pick one) · all classes start the week of October 5 · 8 weeks · 60 min.",
  // ── components/KoreanCulture.tsx
  "Entiende cada diálogo sin subtítulos.": "Understand every line of dialogue without subtitles.",
  "Canta en coreano real, no en fonética.": "Sing in real Korean, not in phonetics.",
  "Pide en coreano como un local.": "Order in Korean like a local.",
  "Seúl": "Seoul",
  "Viaja a Corea sin barreras.": "Travel to Korea without barriers.",
  "El idioma que abre": "The language that opens",
  "un mundo entero": "a whole world",
  "K-drama, K-pop, gastronomía y Seúl. Aprender coreano es entrar a un universo cultural completo — y en el blog lo exploramos contigo.": "K-drama, K-pop, food and Seoul. Learning Korean means stepping into an entire cultural universe — and on the blog we explore it with you.",
  "Lee el blog de cultura coreana": "Read the Korean culture blog",
  // ── components/MetodoChingu.tsx
  "Lee desde el principio": "Read from the start",
  "Nada de romanización eterna. Aprendes a leer 한글 desde tu primera semana, porque leer coreano de verdad cambia cómo aprendes todo lo demás.": "No endless romanization. You learn to read 한글 in your very first week, because reading real Korean changes how you learn everything else.",
  "Habla desde el día uno": "Speak from day one",
  "Cada clase tiene práctica oral real. Te equivocas, te corrigen, vuelves a intentar — así se aprende a hablar, no memorizando tablas.": "Every class includes real speaking practice. You make mistakes, get corrected, and try again — that's how you learn to speak, not by memorizing tables.",
  "Entiende Corea": "Understand Korea",
  "No solo qué se dice, sino por qué se dice así. Honoríficos, jerarquía, comida, K-drama: la cultura es parte de la gramática.": "Not just what is said, but why it's said that way. Honorifics, hierarchy, food, K-drama: culture is part of the grammar.",
  "Aprende con tus chingus": "Learn with your chingus",
  "Grupos reducidos y una comunidad que sigue después de clase. Aprender un idioma acompañado es más rápido — y mucho más divertido.": "Small groups and a community that keeps going after class. Learning a language with others is faster — and a lot more fun.",
  "No aprendas coreano como un libro.": "Don't learn Korean like a textbook.",
  "Aprende como un chingu.": "Learn like a chingu.",
  "Cuatro pilares, pensados desde el español — no un programa coreano traducido.": "Four pillars, designed from a Spanish speaker's perspective — not a translated Korean program.",
  // ── components/Navigation.tsx
  "Inicio": "Home",
  "Inscripción octubre": "October enrollment",
  "Programa": "Program",
  "Sobre Jay": "About Jay",
  "Recursos": "Resources",
  "Lector de Hangul 🐯 (nuevo)": "Hangul Reader 🐯 (new)",
  "Guías": "Guides",
  "Pronunciación coreana": "Korean pronunciation",
  "Tu nombre en coreano": "Your name in Korean",
  "Hangul-dle (juego diario)": "Hangul-dle (daily game)",
  "Preguntas (FAQ)": "FAQ",
  "Contacto": "Contact",
  "Abrir menú": "Open menu",
  "Contacto por WhatsApp": "Contact on WhatsApp",
  // ── components/PrefsControls.tsx
  "Idioma": "Language",
  "Modo día": "Light mode",
  "Modo noche": "Dark mode",
  // ── components/ProgramaContent.tsx
  "La escalera": "The ladder",
  "Horario semanal": "Weekly schedule",
  "Cómo es una clase": "What a class is like",
  "Equipo docente": "Teaching team",
  "Precio y pago": "Price and payment",
  "PROGRAMA OFICIAL · COHORTE OCTUBRE 2026": "OFFICIAL PROGRAM · OCTOBER 2026 COHORT",
  "5 cursos · 6 horarios · 8 semanas · 1 clase de 60 min por semana · certificado incluido": "5 courses · 6 time slots · 8 weeks · one 60-min class per week · certificate included",
  "Inscribirme →": "Enroll →",
  "📄 Descargar programa (PDF)": "📄 Download program (PDF)",
  "La escalera de Academia Seúl": "The Academia Seúl ladder",
  "Todos los cursos duran 8 semanas y cuestan lo mismo. Cada peldaño te deja listo para el siguiente. Toca tu caso y te decimos dónde entrar.": "Every course runs 8 weeks and costs the same. Each step gets you ready for the next one. Tap your situation and we'll tell you where to start.",
  "Todas las clases parten {inicio} · toca tu país para ver tu hora": "All classes start {inicio} · tap your country to see your local time",
  "CÓMO ES UNA CLASE": "WHAT A CLASS IS LIKE",
  "60 minutos que rinden": "60 minutes that really count",
  "El drilling pesado (leer sílabas, memorizar números) vive en el Lector de Hangul como tarea con audio nativo. La hora en vivo se reserva para lo que solo la clase en vivo da: hablar y ser corregido.": "The heavy drilling (reading syllables, memorizing numbers) lives in the Hangul Reader as homework with native audio. The live hour is saved for what only a live class can give you: speaking and getting corrected.",
  "Quiz de la clase anterior": "Quiz on the previous class",
  "Activar lo aprendido": "Activate what you learned",
  "Lección con el deck": "Lesson with the slide deck",
  "Gramática con dibujos y ejemplos reales": "Grammar with drawings and real examples",
  "Práctica oral en pares": "Speaking practice in pairs",
  "Role-play y corrección de pronunciación": "Role-play and pronunciation correction",
  "Cierre y tarea": "Wrap-up and homework",
  "Lector de Hangul + hoja de la sesión": "Hangul Reader + session worksheet",
  "Ruta Niños": "Kids track",
  "Paso {n} de la escalera": "Step {n} on the ladder",
  "{hora} Chile · primera clase {fecha}": "{hora} Chile time · first class {fecha}",
  "Profesor/a": "Teacher",
  "Requiere": "Requires",
  "Nada — desde cero": "Nothing — from scratch",
  "Material": "Materials",
  "US${p} · o {n} × US${m}": "US${p} · or {n} × US${m}",
  "Al terminar vas a poder:": "By the end you'll be able to:",
  "Inscribirme en {curso} →": "Enroll in {curso} →",
  "Semana a semana": "Week by week",
  "Un solo precio para todos los cursos": "One price for every course",
  "{precio} — sin importar el nivel.": "{precio} — no matter the level.",
  "Una al inscribirte, otra al inicio del mes 2": "One when you enroll, the other at the start of month 2",
  "8 clases en vivo por Zoom de 60 min": "8 live 60-min classes on Zoom",
  "Certificado de Academia Seúl incluido": "Academia Seúl certificate included",
  "Grabación de cada clase": "Recording of every class",
  "Slides + hojas de actividad": "Slides + activity sheets",
  "Lector de Hangul con audio nativo": "Hangul Reader with native audio",
  "Grupos chicos con corrección personal": "Small groups with personal correction",
  "Hola Jay! Vi el programa de octubre y tengo una duda sobre qué curso me conviene.": "Hi Jay! I saw the October program and I have a question about which course is right for me.",
  "💬 ¿Qué nivel me conviene?": "💬 Which level is right for me?",
  // ── components/PromoBar.tsx
  "clases desde el 5 de octubre": "classes start October 5",
  "clases desde la semana del 5 de octubre": "classes start the week of October 5",
  "US${p} el curso (o {n} × US${m}) · mismo precio en todos los niveles": "US${p} per course (or {n} × US${m}) · same price for every level",
  "Elegir mi clase →": "Choose my class →",
  "Cerrar": "Close",
  // ── components/RecursosContent.tsx
  "Lector de Hangul": "Hangul Reader",
  "Aprende a leer el alfabeto coreano con la lógica del 훈민정음: lecciones interactivas, constructor de sílabas y práctica con audio de voz nativa que cambia en cada ronda.": "Learn to read the Korean alphabet using the logic of 훈민정음: interactive lessons, a syllable builder and practice with native-voice audio that changes every round.",
  "Aprender a leer": "Learn to read",
  "Descarga gratis la Guía del Alfabeto (한글) y la Guía de Pronunciación coreana. PDFs listos para imprimir y estudiar.": "Download the Alphabet Guide (한글) and the Korean Pronunciation Guide for free. Print-ready PDFs to study from.",
  "Ver guías": "See guides",
  "Tablero interactivo: haz clic en cada consonante, vocal y palabra para escuchar su sonido en coreano. Gratis y desde el navegador.": "Interactive board: click on each consonant, vowel and word to hear how it sounds in Korean. Free, right in your browser.",
  "Practicar pronunciación": "Practice pronunciation",
  "Escribe tu nombre, míralo en hangul y escúchalo con voz coreana. Descárgalo como imagen para compartir.": "Type your name, see it in Hangul and hear it in a Korean voice. Download it as an image to share.",
  "Crear mi nombre": "Create my name",
  "Torpedo Coreano": "Korean Pop Quiz",
  "Un juego rápido de vocabulario y gramática de Básico 1 (A1.1): saludos, partículas, familia y más. Ocho preguntas para poner a prueba lo que ya sabes.": "A quick vocabulary and grammar game from Basic 1 (A1.1): greetings, particles, family and more. Eight questions to test what you already know.",
  "Jugar ahora": "Play now",
  "Nuestro Wordle coreano: adivina la palabra del día en 6 intentos. Una palabra nueva cada 24 horas, con racha incluida.": "Our Korean Wordle: guess the word of the day in 6 tries. A new word every 24 hours, streak included.",
  "Jugar hoy": "Play today",
  "Recursos gratis": "Free resources",
  "Aprende coreano": "Learn Korean",
  "Todo gratis para empezar hoy: guías descargables, pronunciación con audio y tu nombre en coreano.": "Everything free to get started today: downloadable guides, pronunciation with audio and your name in Korean.",
  // ── components/ResumenReserva.tsx
  "{dia} {hora} Chile": "{dia} {hora} Chile time",
  "{dia} {hora} {pais} ({horaChile} Chile)": "{dia} {hora} {pais} ({horaChile} Chile time)",
  "Cambiar": "Change",
  "Cambiar clase": "Change class",
  "primera clase **{fecha}**": "first class **{fecha}**",
  // ── components/SidebarCursos.tsx
  "Clases de octubre": "October classes",
  "En esta página": "On this page",
  "Navegación de cursos": "Course navigation",
  // ── components/SobreContent.tsx
  "이야기 · Mi historia": "이야기 · My story",
  "Hola, soy": "Hi, I'm",
  "Fundador y profesor · Academia Seúl": "Founder and teacher · Academia Seúl",
  "Nací como": "I was born as",
  "en Seúl, entre kimchi y una educación coreana de la dura — esa que te enseña a esforzarte y a no rendirte nunca.": "in Seoul, between kimchi and a tough Korean upbringing — the kind that teaches you to work hard and never give up.",
  "Tenía 10 años cuando crucé medio mundo y llegué a Chile. Fue increíble… y durísimo. En el colegio americano me tocaba hacer malabares con el español y el inglés al mismo tiempo, sin red. Aprender a": "I was 10 when I crossed half the world and landed in Chile. It was incredible… and brutally hard. At the American school I had to juggle Spanish and English at the same time, with no safety net. Learning to",
  "pertenecer": "belong",
  "fue mi primera gran lección — y nadie me dio un mapa.": "was my first big lesson — and nobody handed me a map.",
  "Pero Chile me adoptó. Me enamoré de los asados, las empanadas y los zapateos de norte a sur. Sin darme cuenta, me convertí en las dos cosas a la vez: coreano y latino.": "But Chile adopted me. I fell in love with the asados, the empanadas and the foot-stomping dances from north to south. Without realizing it, I became both things at once: Korean and Latino.",
  "Una conexión para el mundo. Un puente con piernas.": "A connection to the world. A bridge with legs.",
  "Después me fui a estudiar a Michigan y me hice economista. Pero si miro hacia atrás, toda mi vida hice lo mismo: enseñar y ayudar. Mi mamá fue profesora universitaria, y de ella heredé la fascinación por aprender. Estudiar no es mi obligación; es mi pasión.": "Later I went off to study in Michigan and became an economist. But looking back, I've done the same thing my whole life: teach and help. My mom was a university professor, and from her I inherited a fascination with learning. Studying isn't my obligation; it's my passion.",
  "De ahí nació Academia Seúl. Quiero compartir lo que amo —el idioma, la cultura, la música, el K-pop, la comida— con quienes lo aman desde lejos, igual que yo amé a Chile desde el primer asado.": "That's where Academia Seúl was born. I want to share what I love —the language, the culture, the music, K-pop, the food— with those who love it from afar, just like I loved Chile from the very first asado.",
  "Gracias por estar aquí, justo al inicio de este viaje. Este puente lo cruzamos juntos.": "Thank you for being here, right at the start of this journey. We cross this bridge together.",
  "Empieza desde cero conmigo y el equipo. Clases en vivo, grupos pequeños.": "Start from scratch with me and the team. Live classes, small groups.",
  "Ver cursos de octubre →": "See October courses →",
  "Y en el camino descubrí algo que me dolió: casi todo el material para aprender coreano está hecho **para nativos**, o **en inglés**. No existe contenido —ni un libro de verdad— pensado para hispanohablantes. Seré su **profesor Kim**, y un buen": "And along the way I discovered something that hurt: almost all the material for learning Korean is made **for native speakers**, or **in English**. There's no content —not a single real book— designed for Spanish speakers. I'll be your **Teacher Kim**, and a good",
  "Por eso voy a escribirlo junto al gran equipo de profesores que he formado — ya puedes conocerlos en el programa de octubre. **Para ustedes.**": "That's why I'm going to write it together with the great team of teachers I've built — you can already meet them in the October program. **For you.**",
  // ── components/Testimonials.tsx
  "Profesor nativo de Seúl": "Native teacher from Seoul",
  "Nací en Seúl en 1990 y llegué a Chile a los 10 años. No \"hablo coreano\" — lo viví desde pequeño. La pronunciación, los matices culturales y los modismos son parte de mi día a día.": "I was born in Seoul in 1990 and moved to Chile at age 10. I don't just \"speak Korean\" — I've lived it since I was a kid. Pronunciation, cultural nuances and idioms are part of my everyday life.",
  "Bilingüe perfecto coreano-español": "Perfectly bilingual in Korean and Spanish",
  "Crucé los dos idiomas durante 25+ años. Conozco exactamente dónde se traba un hispanohablante con el coreano — y cómo destrabarlo en minutos, no en años.": "I've moved between both languages for 25+ years. I know exactly where a Spanish speaker gets stuck with Korean — and how to get them unstuck in minutes, not years.",
  "8+ años enseñando coreano": "8+ years teaching Korean",
  "No es mi primer rodeo. Llevo años enseñando coreano formal e informalmente a estudiantes chilenos y latinoamericanos. Cada error que cometes, ya lo he visto antes.": "This isn't my first rodeo. I've spent years teaching Korean, formally and informally, to Chilean and Latin American students. Every mistake you make, I've seen before.",
  "Diseñado específicamente para hispanohablantes. No es un programa coreano traducido — es un enfoque pensado desde el español, con metáforas y referencias que sí entiendes.": "Designed specifically for Spanish speakers. It's not a translated Korean program — it's an approach built from Spanish, with metaphors and references you actually understand.",
  "Grupos con cupos limitados": "Groups with limited spots",
  "No saturamos las cohortes. Grupos pequeños para que cada Chingu reciba atención personal, dudas resueltas en vivo y feedback de pronunciación real.": "We don't overfill our cohorts. Small groups so every Chingu gets personal attention, questions answered live and real pronunciation feedback.",
  "Certificado incluido en todos los cursos. Al terminar recibes el certificado de Academia Seúl de tu nivel (Básico 1 · A1.1, Básico 2 · A1.2, Conversacional 1 · A2.1, TOPIK II o Niños), por asistencia y participación.": "Certificate included in every course. When you finish, you receive the Academia Seúl certificate for your level (Basic 1 · A1.1, Basic 2 · A1.2, Conversational 1 · A2.1, TOPIK II or Kids), based on attendance and participation.",
  "Nivel A1": "Level A1",
  "Coreano Básico": "Basic Korean",
  "Para mí fue un gran profesor. Le entendí muy bien y era bueno explicando. Si alguien no entendía, volvía a explicar. Sus clases eran muy divertidas y aprendimos muchas cosas sobre la cultura coreana.": "For me he was a great teacher. I understood him really well and he was good at explaining. If someone didn't get it, he'd explain it again. His classes were a lot of fun and we learned so much about Korean culture.",
  "Las clases son bastante entretenidas porque, más que pasar solo contenido, también nos enseña otras cosas. Cuando le preguntamos un concepto, nos cuenta una pequeña historia relacionada — así lo recuerdo más fácilmente.": "The classes are really engaging because, beyond just covering the material, he teaches us other things too. When we ask him about a concept, he tells us a little related story — that way I remember it more easily.",
  "Nivel B1": "Level B1",
  "Coreano Intermedio": "Intermediate Korean",
  "Excelente profesor. Siempre disponible para responder dudas dentro y fuera del horario de clases, además de explicar hasta que se entienda. Las clases son divertidas y entendibles. ¡Gracias, profesor!": "Excellent teacher. Always available to answer questions during and outside class hours, and he explains until you get it. The classes are fun and easy to follow. Thank you, teacher!",
  "Muy buen profesor, sus explicaciones son muy claras y siempre da distintos ejemplos. Además nos enseña sobre cultura y cosas típicas de Corea. También enseña con música, lo cual facilita mucho el oído y la pronunciación correcta.": "Very good teacher, his explanations are very clear and he always gives different examples. He also teaches us about Korean culture and everyday customs. He even teaches with music, which really helps with listening and correct pronunciation.",
  "Clases claras y didácticas, con entrega de material adecuado para el estudio. Se agradece el esfuerzo para fomentar la participación en clases y explicar reiteradamente en caso de dudas, además de la disposición para resolver dudas fuera del horario.": "Clear, well-taught classes, with the right study materials provided. I appreciate the effort to encourage participation in class and to explain things again whenever there are questions, as well as his willingness to answer questions outside class hours.",
  "Jae Hee tiene muy buena disposición cuando alguien tiene una duda, complementa sus clases con cultura general y se dan espacios de confianza donde se pueden compartir experiencias.": "Jae Hee is very approachable whenever someone has a question, he complements his classes with general culture, and there's a trusting atmosphere where you can share experiences.",
  "Fue entretenido y entendí muy bien las clases. Tiene mucha paciencia y hace agradable el aprender.": "It was fun and I understood the classes really well. He's very patient and makes learning enjoyable.",
  "Anterior": "Previous",
  "Siguiente": "Next",
  "Testimonio {n}": "Testimonial {n}",
  "Lo que nos hace": "What makes us",
  "diferentes": "different",
  "8+ años enseñando coreano, una metodología probada y la energía de una comunidad real.": "8+ years teaching Korean, a proven methodology and the energy of a real community.",
  "Fundador y profesor": "Founder and teacher",
  ", soy": ", I'm",
  "— mejor conocido como Jay. Nací en Seúl, llegué a Chile a los 10 años, y crecí entre kimchi y empanadas — entre": "— better known as Jay. I was born in Seoul, moved to Chile at 10, and grew up between kimchi and empanadas — between",
  "y español.": "and Spanish.",
  "De día soy gerente en una empresa coreana de genómica en Las Condes. De noche hago lo que más amo: enseñar mi idioma a quienes lo aprenden por amor a la cultura. Academia Seúl nació para construir el puente que yo no tuve a los 10.": "By day I'm a manager at a Korean genomics company in Las Condes. By night I do what I love most: teaching my language to people who learn it out of love for the culture. Academia Seúl was born to build the bridge I didn't have at 10.",
  "Nativo de Seúl": "Seoul native",
  "Bilingüe español": "Bilingual in Spanish",
  "8+ años enseñando": "8+ years teaching",
  "Lee mi historia →": "Read my story →",
  "La mejor forma de conocer nuestro método: una clase en vivo.": "The best way to get to know our method: a live class.",
  "Estudiantes reales": "Real students",
  "Lo que dicen": "Hear it from",
  "mis chingus": "my chingus",
  "Testimonios reales de estudiantes que tomé en mis clases anteriores. La misma energía y metodología llega ahora a Academia Seúl.": "Real testimonials from students I taught in my previous classes. The same energy and methodology now comes to Academia Seúl.",
  // ── components/VideoIntro.tsx
  "Conoce a tu chingu coreano": "Meet your Korean chingu",
  // ── components/WhatsAppFloat.tsx
  "Hola Jay! Vi tu sitio Academia Seul y tengo una consulta sobre tus cursos de coreano.": "Hi Jay! I saw your Academia Seúl website and I have a question about your Korean courses.",
  "Quiero inscribirme (clases desde la semana del 5 de octubre)": "I want to enroll (classes start the week of October 5)",
  "Hola Jay! Quiero inscribirme en la cohorte de octubre. ¿Me ayudas a elegir el curso y el método de pago?": "Hi Jay! I want to enroll in the October cohort. Can you help me choose the course and the payment method?",
  "¿Qué nivel me conviene?": "Which level is right for me?",
  "Hola Jay! No sé si me conviene Básico 1, Básico 2, Conversacional o TOPIK II. ¿Me orientas?": "Hi Jay! I'm not sure whether Basic 1, Basic 2, Conversational or TOPIK II is right for me. Can you point me in the right direction?",
  "Consulta personalizada": "Personal inquiry",
  "Hola Jay! Tengo una consulta sobre tus cursos de coreano.": "Hi Jay! I have a question about your Korean courses.",
  "Te respondo en horas": "I reply within hours",
  "Empieza la conversacion": "Start the conversation",
  "Abre WhatsApp con mensaje listo. 100% sin compromiso.": "Opens WhatsApp with a ready-to-send message. 100% no strings attached.",
  "Abrir WhatsApp": "Open WhatsApp",
  // ── components/WordGame.tsx
  "Básico": "Basic",
  "¿Qué significa este saludo?": "What does this greeting mean?",
  "Adiós": "Goodbye",
  "Hola": "Hello",
  "Gracias": "Thank you",
  "Lo siento": "I'm sorry",
  "¿Qué significa esta frase?": "What does this phrase mean?",
  "Por favor": "Please",
  "De nada": "You're welcome",
  "Perdón": "Excuse me",
  "Gramática: ¿qué partícula completa \"Yo soy estudiante\"?": "Grammar: which particle completes \"I am a student\"?",
  "¿Qué significa esta palabra?": "What does this word mean?",
  "Amigo": "Friend",
  "Familia": "Family",
  "Escuela": "School",
  "Trabajo": "Work",
  "Intermedio": "Intermediate",
  "\"¿No te gusta el café?\" — si es cierto que NO te gusta, ¿cómo respondes en coreano?": "\"Don't you like coffee?\" — if it's true that you DON'T like it, how do you answer in Korean?",
  "¿Qué significa esta pregunta?": "What does this question mean?",
  "¿Quién es?": "Who is it?",
  "¿Dónde está?": "Where is it?",
  "¿Qué es esto?": "What is this?",
  "¿Cómo estás?": "How are you?",
  "Gramática: ¿qué partícula completa \"Bebo café\"?": "Grammar: which particle completes \"I drink coffee\"?",
  "Un coreano dice esto para referirse a...": "A Korean person says this to refer to...",
  "Nuestra mamá (de todos)": "Our mom (everyone's)",
  "Mi mamá": "My mom",
  "La mamá de otro": "Someone else's mom",
  "Su abuela": "Their grandmother",
  "Pruébalo tú mismo": "Try it yourself",
  "¿Cuánto coreano": "How much Korean",
  "ya sabes?": "do you already know?",
  "8 preguntas rápidas de vocabulario y gramática, sacadas directo de nuestras clases de Básico 1 (A1.1).": "8 quick vocabulary and grammar questions, taken straight from our Basic 1 (A1.1) classes.",
  "Mezcla de vocabulario y partículas — nivel básico a intermedio.": "A mix of vocabulary and particles — basic to intermediate level.",
  "Empezar el juego": "Start the game",
  "Pregunta": "Question",
  "de {total}": "of {total}",
  "Puntaje:": "Score:",
  "Resultado": "Result",
  "¡Puntaje perfecto! Ya tienes una base sólida — Básico 2 (A1.2) o Conversacional 1 (A2.1) son tu siguiente paso.": "Perfect score! You already have a solid foundation — Basic 2 (A1.2) or Conversational 1 (A2.1) is your next step.",
  "Nada mal para una probadita. En Básico 1 vemos todo esto (y mucho más) con calma, paso a paso.": "Not bad for a first taste. In Basic 1 we cover all of this (and much more) at a comfortable pace, step by step.",
  "Así arrancamos todos. En Básico 1 (A1.1) empezamos desde cero, sin apuro y con clases en vivo.": "That's how we all start. In Basic 1 (A1.1) we begin from scratch, no rush, with live classes.",
  "Jugar de nuevo": "Play again",
  // ── lib/nivel1.ts
  "Jay Kim · 김재희": "Jay Kim · 김재희",
  "Fundador · Básico 2 y TOPIK II": "Founder · Basic 2 and TOPIK II",
  "Coreano nativo radicado en Chile. Creador del Método Chingu™ y del Lector de Hangul. 8+ años enseñando a hispanohablantes.": "Native Korean based in Chile. Creator of the Chingu Method™ and the Hangul Reader. 8+ years teaching Spanish speakers.",
  "Guiran · 기란": "Guiran · 기란",
  "Básico 1 (martes y jueves)": "Basic 1 (Tuesday and Thursday)",
  "Profesora coreana criada en Argentina — bilingüe perfecta. Años de experiencia enseñando coreano en español.": "Korean teacher raised in Argentina — perfectly bilingual. Years of experience teaching Korean in Spanish.",
  "Abby · 홍미영": "Abby · 홍미영",
  "Conversacional 1": "Conversational 1",
  "Profesora coreana nativa, pedagoga (MSU). Dicta el conversacional desde Corea — clases donde solo se habla.": "Native Korean teacher with a degree in education (MSU). Teaches the conversational course from Korea — classes where all you do is talk.",
  "Profesor/a de Niños": "Kids teacher",
  "por confirmar": "to be confirmed",
  "Docente con experiencia en clases para 8–12 años. Te lo presentamos por WhatsApp antes de que pagues.": "Teacher with experience teaching 8–12-year-olds. We'll introduce them to you on WhatsApp before you pay.",
  "Básico 1 (A1.1) · Martes 20:00 Chile · Guiran": "Basic 1 (A1.1) · Tuesday 20:00 Chile time · Guiran",
  "Martes": "Tuesday",
  "martes 6 de octubre": "Tuesday, October 6",
  "Básico 1 (A1.1) · Jueves 20:00 Chile · Guiran": "Basic 1 (A1.1) · Thursday 20:00 Chile time · Guiran",
  "Jueves": "Thursday",
  "jueves 8 de octubre": "Thursday, October 8",
  "Básico 2 (A1.2) · Miércoles 21:00 Chile · Jay": "Basic 2 (A1.2) · Wednesday 21:00 Chile time · Jay",
  "Miércoles": "Wednesday",
  "miércoles 7 de octubre": "Wednesday, October 7",
  "Conversacional 1 (A2.1) · Martes 21:00 Chile · Abby": "Conversational 1 (A2.1) · Tuesday 21:00 Chile time · Abby",
  "TOPIK II (B1+) · Jueves 21:00 Chile · Jay": "TOPIK II (B1+) · Thursday 21:00 Chile time · Jay",
  "Coreano para Niños (8–12) · Lunes 18:00 Chile": "Korean for Kids (8–12) · Monday 18:00 Chile time",
  "Lunes": "Monday",
  "lunes 5 de octubre": "Monday, October 5",
  "Argentina / Uruguay / Brasil": "Argentina / Uruguay / Brazil",
  "Colombia / Perú / Ecuador": "Colombia / Peru / Ecuador",
  "Col/Perú": "Col/Peru",
  "México (CDMX)": "Mexico (Mexico City)",
  "EE.UU. (hora del Este)": "USA (Eastern time)",
  "EE.UU. Este": "USA Eastern",
  "En EE.UU. la hora cambia el 1 de noviembre (se muestra antes → después).": "In the USA the time changes on November 1 (shown before → after).",
  "En España la hora cambia el 25 de octubre (se muestra antes → después).": "In Spain the time changes on October 25 (shown before → after).",
  "Corea": "Korea",
  "Para Corea, las clases caen a la mañana del día siguiente.": "For Korea, classes fall on the morning of the next day.",
  "Primeras Palabras": "First Words",
  "Nivel 1 · julio 2026": "Level 1 · July 2026",
  "Básico 1 · Primeras Palabras": "Basic 1 · First Words",
  "A1.1 · desde cero": "A1.1 · from scratch",
  "한글학교 한국어 1 + Lector de Hangul (tarea con audio nativo)": "한글학교 한국어 1 + Hangul Reader (homework with native audio)",
  "El punto de partida: aprender a leer el alfabeto coreano y decir tus primeras frases reales. El drilling de lectura vive en el Lector de Hangul como tarea gamificada, así la hora en vivo se usa para hablar y ser corregido.": "The starting point: learn to read the Korean alphabet and say your first real sentences. Reading drills live in the Hangul Reader as gamified homework, so the live hour is spent speaking and getting corrected.",
  "가나다라 I · La sílaba": "가나다라 I · The syllable",
  "Vocales y consonantes básicas — lees tus primeras sílabas en voz alta": "Basic vowels and consonants — you read your first syllables out loud",
  "Batchim y dobles · saludos · 저는 ~예요: te presentas con nombre y país": "Batchim and double consonants · greetings · 저는 ~예요: you introduce yourself with your name and country",
  "이게 뭐예요? · ¿Qué es esto?": "이게 뭐예요? · What is this?",
  "이거/그거/저거 · 이에요/예요 · preguntas y respondes qué es cualquier cosa": "이거/그거/저거 · 이에요/예요 · you ask and answer what anything is",
  "우리 엄마예요 · Mi familia": "우리 엄마예요 · My family",
  "Familia · el famoso 우리 · 누구예요? · números sino-coreanos": "Family · the famous 우리 · 누구예요? · Sino-Korean numbers",
  "집이 어디예요? · Lugares": "집이 어디예요? · Places",
  "어디 · N에 있어요 · dices dónde vives y dónde están las cosas": "어디 · N에 있어요 · you say where you live and where things are",
  "학교에 가요 · Mi día": "학교에 가요 · My day",
  "Presente -아/어요 · N에 가다 · cuentas a dónde vas cada día": "Present tense -아/어요 · N에 가다 · you talk about where you go every day",
  "Mi pieza y mis verbos": "My room and my verbs",
  "이/가 · 을/를 · 있다/없다 · describes tu pieza y qué haces": "이/가 · 을/를 · 있다/없다 · you describe your room and what you do",
  "사과를 좋아해요 + examen": "사과를 좋아해요 + exam",
  "Gustos · repaso integral · mini-presentación final · certificado": "Likes · full review · final mini-presentation · certificate",
  "Pasado, presente y futuro": "Past, present and future",
  "Básico 1 (A1.1) o el Nivel 1 de julio": "Basic 1 (A1.1) or Level 1 (July)",
  "Básico 2 · Pasado, presente y futuro": "Basic 2 · Past, present and future",
  "A1.2 · requiere Básico 1": "A1.2 · requires Basic 1",
  "Uso de la gramática coreana · Nivel inicial (Korean Grammar in Use en español)": "Korean Grammar in Use · Beginning level (Spanish edition)",
  "La continuación directa de Básico 1 (y del Nivel 1 de julio): del presente al pasado y al futuro. Cuentas lo que hiciste, planeas lo que harás y sumas las partículas que hacen sonar natural tu coreano. Termina con el examen A2 de la casa.": "The direct continuation of Basic 1 — and of Level 1 (July): from the present to the past and the future. You'll talk about what you did, plan what you'll do, and add the particles that make your Korean sound natural. Ends with our in-house A2 exam.",
  "Re-presentación + diagnóstico": "Re-introduction + diagnostic",
  "이다/있다 consolidados · repaso activo de Básico 1 · diagnóstico oral": "이다/있다 consolidated · active review of Basic 1 · oral diagnostic",
  "Números aplicados": "Numbers in action",
  "Sino y nativos en la vida real: edad, cumpleaños, hora (몇 시) y teléfono": "Sino-Korean and native numbers in real life: age, birthday, time (몇 시) and phone numbers",
  "Presente completo": "The full present tense",
  "-아/어요 + irregulares de uso diario · describes tu rutina con 10 verbos": "-아/어요 + everyday irregulars · describe your routine with 10 verbs",
  "El pasado · -았/었어요": "The past · -았/었어요",
  "부터~까지 · cuentas qué hiciste el fin de semana (mini-diario)": "부터~까지 · talk about what you did over the weekend (mini-diary)",
  "El futuro · -(으)ㄹ 거예요": "The future · -(으)ㄹ 거예요",
  "-거나 · planeas tus vacaciones soñadas": "-거나 · plan your dream vacation",
  "Negación y habilidad": "Negation and ability",
  "안 · 못 · -지 않아요 · -(으)ㄹ 수 있다/없다: qué no haces y qué sabes hacer": "안 · 못 · -지 않아요 · -(으)ㄹ 수 있다/없다: what you don't do and what you can do",
  "Partículas pro": "Pro particles",
  "의 · 도 · 만 · 쯤 · 처럼 · 보다 · 한테 · 밖에 · 마다 — precisión de nativo": "의 · 도 · 만 · 쯤 · 처럼 · 보다 · 한테 · 밖에 · 마다 — native-level precision",
  "Conectores + examen A2": "Connectors + A2 exam",
  "-고 · -지만 · conversas 5 minutos · examen A2 + oral · certificado": "-고 · -지만 · a 5-minute conversation · A2 exam + oral · certificate",
  "Corea que amas": "The Korea you love",
  "Básico 2 (A1.2) o test de nivel": "Basic 2 (A1.2) or placement test",
  "Conversacional 1 · Corea que amas": "Conversational 1 · The Korea you love",
  "A2.1 · requiere Básico 2 o test de nivel": "A2.1 · requires Basic 2 or placement test",
  "Módulos conversacionales propios (K-pop, viajes, comida…) · con profesora nativa": "Our own conversation modules (K-pop, travel, food…) · with a native teacher",
  "Puro hablar: cada semana un tema de la Corea que amas — K-pop, Jeju, comida, hanbok, e-sports — con una profesora coreana nativa y grupos pequeños. La mitad de las sesiones son laboratorio oral.": "Pure speaking: each week a topic from the Korea you love — K-pop, Jeju, food, hanbok, e-sports — with a native Korean teacher and small groups. Half of the sessions are speaking labs.",
  "Orientación + diagnóstico oral": "Orientation + oral diagnostic",
  "Romper el hielo · fijar tus metas personales de conversación": "Break the ice · set your personal conversation goals",
  "K-pop y cultura fan": "K-pop and fan culture",
  "Hablar de tu grupo, tu bias y los conciertos": "Talk about your group, your bias and concerts",
  "Viajes: Jeju y Seúl": "Travel: Jeju and Seoul",
  "Planear y contar viajes por Corea": "Plan and talk about trips around Korea",
  "Cultura gastronómica": "Food culture",
  "Pedir, recomendar y describir sabores": "Order, recommend and describe flavors",
  "Lab de conversación 1": "Conversation Lab 1",
  "Práctica oral pura en grupos pequeños (módulos 1–3)": "Pure speaking practice in small groups (modules 1–3)",
  "Hanbok y estética": "Hanbok and aesthetics",
  "Describir y opinar": "Describe and give opinions",
  "PC방 y e-sports": "PC방 and e-sports",
  "La Corea gamer": "Gamer Korea",
  "Lab 2 + evaluación oral": "Lab 2 + oral assessment",
  "Evaluación de etapa · certificado A2.1 · invitación a Conversacional 2 (enero)": "Stage assessment · A2.1 certificate · invitation to Conversational 2 (January)",
  "Estrategia de examen": "Exam strategy",
  "Nivel intermedio (B1)": "Intermediate level (B1)",
  "Preparación TOPIK II": "TOPIK II Prep",
  "B1+ · examen oficial": "B1+ · official exam",
  "Exámenes TOPIK oficiales + material de estrategia propio": "Official TOPIK exams + our own strategy material",
  "Grupo chico (máx. 8) enfocado 100% en el examen oficial: estrategia por sección, corrección personalizada de escritura (쓰기) y simulacros cronometrados. Ideal si apuntas al TOPIK de abril 2027.": "Small group (max 8) focused 100% on the official exam: section-by-section strategy, personalized writing (쓰기) correction and timed mock exams. Ideal if you're aiming for the April 2027 TOPIK.",
  "Diagnóstico + radiografía del TOPIK II": "Diagnostic + anatomy of the TOPIK II",
  "Simulacro diagnóstico · cómo se puntúa · tu nivel de partida": "Diagnostic mock exam · how it's scored · your starting level",
  "읽기 I · Lectura": "읽기 I · Reading",
  "Preguntas 1–20: tipos, trampas y manejo del tiempo": "Questions 1–20: question types, traps and time management",
  "듣기 I · Escucha": "듣기 I · Listening",
  "Dictado activo · preguntas 1–20 · notas mientras escuchas": "Active dictation · questions 1–20 · note-taking while you listen",
  "Completar oraciones: los puntos más rentables del examen": "Sentence completion: the best-value points on the exam",
  "쓰기 53 · El gráfico": "쓰기 53 · The graph",
  "Describir datos en 200–300 caracteres con la plantilla que funciona": "Describe data in 200–300 characters with the template that works",
  "읽기/듣기 II · Nivel 4–6": "읽기/듣기 II · Level 4–6",
  "Las preguntas difíciles: inferencia, orden y actitud del hablante": "The hard questions: inference, ordering and the speaker's attitude",
  "쓰기 54 · El ensayo": "쓰기 54 · The essay",
  "Opinión en 600–700 caracteres · estructura + corrección personal": "Opinion essay in 600–700 characters · structure + personal correction",
  "Simulacro final + plan personal": "Final mock exam + personal plan",
  "Examen completo cronometrado · análisis · tu plan hasta el TOPIK real": "Full timed exam · analysis · your plan up to the real TOPIK",
  "8–12 años": "Ages 8–12",
  "Juega y aprende": "Play and learn",
  "8–12 años · desde cero": "Ages 8–12 · from scratch",
  "Material propio Academia Seúl + Lector de Hangul": "Academia Seúl's own material + Hangul Reader",
  "Coreano desde cero para niños y niñas, con juegos, canciones y dibujos. Aprenden a leer el alfabeto, presentarse y decir sus primeras frases — y terminan con un mini-show para la familia.": "Korean from scratch for kids, with games, songs and drawings. They learn to read the alphabet, introduce themselves and say their first sentences — and finish with a mini-show for the family.",
  "¡Hola, Corea! · 안녕하세요": "Hello, Korea! · 안녕하세요",
  "Saludos con canciones + primeras vocales jugando": "Greetings through songs + first vowels through play",
  "Mi nombre en coreano": "My name in Korean",
  "Consonantes básicas + cada uno escribe su nombre en 한글": "Basic consonants + everyone writes their name in 한글",
  "La fábrica de sílabas": "The syllable factory",
  "Armar y leer sílabas + bingo de lectura": "Build and read syllables + reading bingo",
  "Los animales · 동물": "Animals · 동물",
  "10 animales + '¡es un…!' (이에요/예요) con dibujos": "10 animals + 'it's a…!' (이에요/예요) with drawings",
  "Mi familia · 가족": "My family · 가족",
  "엄마, 아빠, 할머니… presentar a la familia con una foto o dibujo": "엄마, 아빠, 할머니… introduce the family with a photo or drawing",
  "Los números mágicos": "The magic numbers",
  "Contar del 1 al 10 + decir la edad": "Count from 1 to 10 + say your age",
  "¡Ñam! Comida coreana": "Yum! Korean food",
  "김밥, 라면, 불고기 + 'me gusta' (좋아해요)": "김밥, 라면, 불고기 + 'I like it' (좋아해요)",
  "🎤 Show final + certificado": "🎤 Final show + certificate",
  "Mini-presentación en coreano para las familias + certificado": "Mini-presentation in Korean for the families + certificate",
  "Corea por dentro": "Korea from the inside",
  "Leer cualquier sílaba en coreano (Hangul completo + batchim)": "Read any Korean syllable (full Hangul + batchim)",
  "Presentarte y presentar a tu familia": "Introduce yourself and your family",
  "Contar en los dos sistemas de números y decir la hora": "Count in both number systems and tell the time",
  "Decir a dónde vas, qué haces y qué te gusta": "Say where you're going, what you do and what you like",
  "Hablar en pasado, presente y futuro": "Speak in the past, present and future",
  "Decir qué no haces, qué no puedes y qué sabes hacer": "Say what you don't do, what you can't do and what you know how to do",
  "Comparar y precisar con 보다, 처럼, 마다, 밖에…": "Compare and be precise with 보다, 처럼, 마다, 밖에…",
  "Conversar 5 minutos seguidos en coreano": "Hold a 5-minute conversation in Korean",
  "Conversar sobre tus temas favoritos de Corea": "Chat about the Korea topics you love",
  "Planear y contar un viaje": "Plan and talk about a trip",
  "Pedir y recomendar comida como local": "Order and recommend food like a local",
  "Perder el miedo a hablar con una nativa": "Lose your fear of speaking with a native speaker",
  "Dominar la estrategia de cada sección del examen": "Master the strategy for each section of the exam",
  "Escribir los formatos 51–54 con corrección personal": "Write question formats 51–54 with personal correction",
  "Rendir un simulacro completo cronometrado": "Take a full timed mock exam",
  "Salir con un plan de estudio personal hasta tu examen": "Leave with a personal study plan up to your exam",
  "Leer sus primeras palabras en coreano": "Read their first words in Korean",
  "Presentarse: nombre y edad": "Introduce themselves: name and age",
  "Contar del 1 al 10 y nombrar animales y comidas": "Count from 1 to 10 and name animals and foods",
  "Octubre 2026": "October 2026",
  "Semana del 5 de octubre de 2026": "Week of October 5, 2026",
  "la semana del 5 de octubre": "the week of October 5",
  "Semana del 23 de noviembre de 2026": "Week of November 23, 2026",
  "domingo 4 de octubre (o hasta llenar los cupos)": "Sunday, October 4 (or until spots fill up)",
  "España cambia de hora el 25 de octubre y EE.UU. el 1 de noviembre (se muestra antes → después). Chile, Argentina, México, Colombia, Perú y Corea no cambian durante el curso.": "Spain changes its clocks on October 25 and the USA on November 1 (shown as before → after). Chile, Argentina, Mexico, Colombia, Peru and Korea don't change during the course.",
  "US$150 el curso completo · o 2 cuotas de US$75": "US$150 for the full course · or 2 payments of US$75",
  "US$150 · o 2 × US$75": "US$150 · or 2 × US$75",
  "(día sig.)": "(next day)",
};
