// 한국어 사전: 키 = 스페인어 원문 (gettext). Generado con scratchpad/i18n_build_dict.js; edita i18n_ko.json y regenera.
// Si falta una clave se muestra el español.
import type { Dict } from "../i18n";

export const KO: Dict = {
  // ── app/nivel-1/page.tsx
  "US${p} pago único": "US${p} 일시불",
  "{n} cuotas de US${m}": "US${m} × {n}회 분납",
  "¿Qué curso tomo?": "어떤 과정을 들을까요?",
  "Las 8 semanas": "8주 커리큘럼",
  "Profesores": "선생님",
  "Inscripción": "등록",
  "Pago": "결제",
  "Preguntas frecuentes": "자주 묻는 질문",
  "nombre del niño/a": "아이 이름",
  "nombre": "이름",
  "correo": "이메일",
  "edad": "나이",
  "país": "국가",
  "nivel": "레벨",
  "cómo nos conociste": "알게 된 경로",
  "nombre del apoderado/a": "보호자 이름",
  "Falta: {campos}.": "누락된 항목: {campos}.",
  "Hubo un problema al enviar. Intenta de nuevo o escríbenos por WhatsApp.": "전송 중 문제가 발생했어요. 다시 시도하거나 WhatsApp으로 연락해 주세요.",
  "Primero completa tus datos arriba para reservar tu cupo.": "자리를 예약하려면 먼저 위의 정보를 입력해 주세요.",
  "Hola Jay! Quiero pagar con tarjeta mi cupo en {curso} ({plan}) y el pago online no cargó.": "안녕하세요 Jay! {curso} ({plan}) 자리를 카드로 결제하고 싶은데 온라인 결제 페이지가 열리지 않아요.",
  "inscribir a mi hijo/a": "아이를 등록하고",
  "inscribirme": "등록하고",
  "Hola Jay! Quiero {verbo} en {curso} ({dia} {hora} Chile) con {plan}. ¿Me pasas los datos para la transferencia?": "안녕하세요 Jay! {curso} ({dia} {hora} 칠레 시간)에 {plan} 방식으로 {verbo} 싶어요. 계좌이체 정보를 보내 주실 수 있나요?",
  "Hola Jay! Estoy fuera de Chile y quiero pagar {curso} en {n} cuotas de US${m}. ¿Me envías el link de PayPal?": "안녕하세요 Jay! 저는 칠레 밖에 있는데 {curso} 과정을 US${m} × {n}회 분납으로 결제하고 싶어요. PayPal 링크를 보내 주실 수 있나요?",
  "${clp} CLP aprox.": "약 ${clp} CLP",
  "¿Las clases son en vivo o grabadas?": "수업은 실시간인가요, 녹화인가요?",
  "En vivo por Zoom (60 min cada una). Si te pierdes alguna, recibes la grabación dentro de las 24 horas y puedes escribirnos para resolver dudas de esa clase.": "줌(Zoom)으로 진행하는 실시간 수업이에요 (회당 60분). 수업을 놓치면 24시간 안에 녹화본을 받을 수 있고, 그 수업에 대한 질문은 언제든 저희에게 물어보셔도 돼요.",
  "¿Cuánto dura cada curso y cuándo empieza?": "과정은 얼마나 걸리고 언제 시작하나요?",
  "Todos los cursos duran 8 semanas (2 meses), con 1 clase en vivo por semana. La cohorte arranca {inicio} y termina la semana del 23 de noviembre. Matrícula abierta hasta el {cierre}.": "모든 과정은 8주(2개월) 과정으로, 주 1회 실시간 수업이 있어요. 이번 기수는 {inicio}에 시작해 11월 23일 주에 끝나요. 등록 마감: {cierre}.",
  "¿Cuánto cuesta y cómo pago?": "수강료는 얼마이고 어떻게 결제하나요?",
  "{precio} — mismo precio en todos los cursos. Aceptamos transferencia bancaria en Chile (sin comisión), tarjeta de crédito/débito vía Mercado Pago (se cobra en pesos chilenos) y PayPal en dólares (también con tarjeta, sin cuenta PayPal).": "{precio} — 모든 과정이 동일한 가격이에요. 칠레 내 계좌이체(수수료 없음), Mercado Pago를 통한 신용/체크카드 결제(칠레 페소로 청구), 그리고 달러 결제는 PayPal(PayPal 계정 없이 카드로도 가능)을 받아요.",
  "¿Necesito experiencia previa?": "사전 지식이 필요한가요?",
  "Para Básico 1 (A1.1) y Coreano para Niños: cero, empezamos desde el alfabeto. Básico 2 (A1.2) requiere Básico 1 (o el Nivel 1 de julio). Conversacional 1 (A2.1) requiere Básico 2 o el test de nivel. TOPIK II es para nivel intermedio.": "기초 1 (A1.1)과 어린이 한국어는 사전 지식이 전혀 필요 없어요 — 한글부터 시작하거든요. 기초 2 (A1.2)는 기초 1(또는 7월 레벨 1) 수료가 필요하고, 회화 1 (A2.1)은 기초 2 수료 또는 레벨 테스트가 필요해요. TOPIK II는 중급 학습자를 위한 과정이에요.",
  "Fui alumno/a del Nivel 1 en julio, ¿qué curso sigo?": "레벨 1 (7월) 수강생이었는데, 다음은 어떤 과정을 들어야 하나요?",
  "Ese curso hoy se llama Básico 1 (A1.1) y tu certificado equivale a A1.1. Tu siguiente paso es Básico 2 (A1.2) · miércoles 21:00 Chile · con Jay. Si lo que quieres es hablar, también puedes entrar a Conversacional 1 con test de nivel.": "그 과정은 지금 기초 1 (A1.1)이라는 이름으로 운영되고, 수료증은 A1.1에 해당해요. 다음 단계는 기초 2 (A1.2) · 수요일 21:00 칠레 시간 · Jay 선생님이에요. 말하기가 목표라면 레벨 테스트를 거쳐 회화 1에 들어갈 수도 있어요.",
  "¿Cuántas personas hay por clase?": "한 반에 몇 명인가요?",
  "Máximo 15 alumnos por clase (8 en TOPIK II y 12 en Niños). Grupos chicos para que el profesor corrija tu pronunciación personalmente.": "한 반 최대 15명이에요 (TOPIK II는 8명, 어린이 반은 12명). 선생님이 발음을 한 명 한 명 직접 교정해 줄 수 있도록 소규모로 운영해요.",
  "¿Recibo certificado?": "수료증을 받을 수 있나요?",
  "Sí, está incluido en todos los cursos. Al completar tu curso recibes el certificado de Academia Seúl del nivel correspondiente, en base a tu asistencia y participación.": "네, 모든 과정에 포함되어 있어요. 과정을 마치면 출석과 참여도를 바탕으로 해당 레벨의 아카데미아 서울 수료증을 받아요.",
  "¿Cómo es la clase de Niños?": "어린이 수업은 어떻게 진행되나요?",
  "60 minutos divididos en bloques de 10–15 min (canción · juego · lectura · dibujo) con un grupo de máximo 12. Las grabaciones son privadas, solo para las familias del grupo, y el apoderado recibe un grupo de WhatsApp propio. Tu hijo/a solo necesita un computador o tablet con cámara y ganas de jugar.": "60분을 10–15분 블록(노래 · 게임 · 읽기 · 그리기)으로 나눠 최대 12명 그룹으로 진행해요. 녹화본은 비공개로 반 가족들에게만 제공되고, 보호자를 위한 별도 WhatsApp 그룹도 있어요. 아이에게 필요한 건 카메라가 있는 컴퓨터나 태블릿, 그리고 놀고 싶은 마음뿐이에요.",
  "¿En qué hora llegan las clases a mi país?": "제가 있는 나라에서는 몇 시에 수업하나요?",
  "Elige tu país en la grilla de horarios de esta página y verás la hora exacta. Las clases de 20:00 y 21:00 Chile caen de madrugada en España; la de Niños (18:00 Chile) llega a las 23:00 / 22:00 en España.": "이 페이지의 시간표에서 국가를 선택하면 정확한 시간을 볼 수 있어요. 칠레 시간 20:00 및 21:00 수업은 스페인에서는 새벽이고, 어린이 수업(칠레 시간 18:00)은 스페인 시간으로 23:00 / 22:00에 해당해요.",
  "Cursos en vivo": "실시간 과정",
  "Esta cohorte ya está en marcha": "이번 기수는 이미 진행 중이에요",
  "Anótate en la lista de espera y te avisamos apenas se abran los cupos de la próxima cohorte ({cohorte}) — con acceso prioritario a horarios y precio.": "대기 명단에 등록하면 다음 기수({cohorte}) 정원이 열리는 즉시 알려 드려요 — 시간표와 가격을 우선적으로 안내받을 수 있어요.",
  "Anotarme en la lista de espera →": "대기 명단에 등록하기 →",
  "✅ ¡Pago recibido! Tu cupo en {curso} está confirmado. Te escribimos por correo/WhatsApp con los siguientes pasos. 🎉": "✅ 결제가 확인되었어요! {curso} 자리가 확정되었어요. 다음 단계는 이메일/WhatsApp으로 안내해 드릴게요. 🎉",
  "⏳ Tu pago quedó pendiente. Apenas se acredite, confirmamos tu cupo y te avisamos.": "⏳ 결제가 대기 중이에요. 입금이 확인되는 즉시 자리를 확정하고 알려 드릴게요.",
  "No se completó el pago. Puedes intentar de nuevo abajo o escribirnos por WhatsApp.": "결제가 완료되지 않았어요. 아래에서 다시 시도하거나 WhatsApp으로 연락해 주세요.",
  "TODOS LOS NIVELES · COHORTE OCTUBRE 2026": "전 레벨 · 2026년 10월 기수",
  "Matrícula octubre 2026": "2026년 10월 등록",
  "De Básico 1 a TOPIK II, y Coreano para Niños de 8 a 12 — elige tu clase.": "기초 1부터 TOPIK II까지, 그리고 8–12세 어린이 한국어까지 — 원하는 수업을 선택하세요.",
  "8 semanas desde {inicio} · 1 clase en vivo por semana · 60 min · {precio} · certificado incluido": "{inicio}부터 8주 · 주 1회 실시간 수업 · 60분 · {precio} · 수료증 포함",
  "⏰ LAS CLASES EMPIEZAN EN": "⏰ 수업 시작까지",
  "DÍAS": "일",
  "HORAS": "시간",
  "MIN": "분",
  "SEG": "초",
  "Matrícula abierta hasta el {cierre}": "{cierre}까지 등록 접수 중",
  "Elegir mi clase": "수업 선택하기",
  "Ver syllabus completo": "전체 강의계획서 보기",
  "Inscribir a mi hijo/a →": "우리 아이 등록하기 →",
  "Reservar mi cupo →": "자리 예약하기 →",
  "Toca tu caso y te decimos tu peldaño — o elige directo en el horario.": "해당하는 상황을 누르면 맞는 단계를 알려 드려요 — 아니면 시간표에서 바로 선택하세요.",
  "Elige tu clase": "수업을 선택하세요",
  "5 cursos · 6 horarios (Básico 1 se dicta martes y jueves: elige uno)": "5개 과정 · 6개 시간대 (기초 1은 화요일과 목요일에 열려요: 하나를 선택하세요)",
  "Tu selección": "선택한 수업",
  "Requiere:": "선수 과정:",
  "Antes se llamaba:": "이전 이름:",
  "📄 Programa PDF": "📄 프로그램 PDF",
  "Ver syllabus semana a semana": "주차별 커리큘럼 보기",
  "Las 8 semanas de {curso}": "{curso}의 8주 커리큘럼",
  "Requiere {req}": "{req} 필요",
  "desde cero": "완전 처음부터",
  "🧒 En Niños la hora se divide en bloques de 10–15 min (canción · juego · lectura · dibujo) y la tarea es breve, para hacer con el apoderado.": "🧒 어린이 과정은 한 시간을 10–15분 블록(노래 · 게임 · 읽기 · 그리기)으로 나눠 진행하고, 숙제는 보호자와 함께 할 수 있도록 짧게 내드려요.",
  "Tu equipo de profesores": "여러분의 선생님 팀",
  "Nativos y bilingües, con años de experiencia enseñando coreano a hispanohablantes.": "한국인 원어민이자 이중언어 구사자로, 스페인어권 학습자에게 한국어를 가르쳐 온 경력이 풍부해요.",
  "Regístrate": "등록",
  "Paga": "결제",
  "Confirma tu pago": "결제 확인",
  "PASO 1 · FORMULARIO DE INSCRIPCIÓN": "1단계 · 등록 신청서",
  "Reserva el cupo de tu hijo/a": "아이의 자리를 예약하세요",
  "Reserva tu cupo": "자리를 예약하세요",
  "Datos del apoderado/a": "보호자 정보",
  "Nombre del apoderado/a *": "보호자 이름 *",
  "Tu nombre y apellido": "이름과 성",
  "Correo *": "이메일 *",
  "tucorreo@email.com": "example@email.com",
  "+56 9 1234 5678 (con código de país)": "+56 9 1234 5678 (국가 번호 포함)",
  "País y ciudad *": "국가와 도시 *",
  "Ej: Chile, Santiago": "예: 칠레, 산티아고",
  "Ej: {pais}, ciudad": "예: {pais}, 도시",
  "Datos del alumno/a": "학생 정보",
  "Nombre del niño/a *": "아이 이름 *",
  "Nombre completo *": "성명 *",
  "Nombre y apellido del niño/a": "아이의 이름과 성",
  "Edad del niño/a *": "아이 나이 *",
  "Edad *": "나이 *",
  "Ej: 10": "예: 10",
  "Ej: 24": "예: 24",
  "Documento de identidad": "신분증 번호",
  "(opcional)": "(선택)",
  "RUT o ID — lo pediremos al emitir el certificado": "RUT 또는 신분증 번호 — 수료증 발급 시 요청드려요",
  "¿Qué nivel de coreano tiene tu hijo/a? *": "아이의 한국어 레벨은 어느 정도인가요? *",
  "¿Cuál es tu nivel de coreano? *": "한국어 레벨은 어느 정도인가요? *",
  "Selecciona un nivel": "레벨을 선택하세요",
  "Fui alumno/a del Nivel 1 (julio 2026) — quiero seguir con Básico 2": "레벨 1 (2026년 7월) 수강생이었어요 — 기초 2로 이어가고 싶어요",
  "Desde cero (no sabe nada) 🐣": "완전 처음 (전혀 몰라요) 🐣",
  "Lee algo del alfabeto (한글)": "한글을 조금 읽을 수 있어요",
  "Terminó Básico 1 o equivalente (lee 한글 y se presenta)": "기초 1 또는 동등 과정을 마쳤어요 (한글을 읽고 자기소개를 해요)",
  "Intermedio — va por el TOPIK II": "중급 — TOPIK II를 목표로 해요",
  "¿Cómo nos conociste? *": "어떻게 알게 되셨나요? *",
  "Selecciona una opción": "옵션을 선택하세요",
  "El Lector de Hangul": "한글 리더",
  "Recomendación de un amigo": "친구 추천",
  "Google / búsqueda": "Google / 검색",
  "Ya fui alumno/a": "이전 수강생이에요",
  "Otro": "기타",
  "¿Por qué quiere aprender coreano?": "아이는 왜 한국어를 배우고 싶어 하나요?",
  "¿Por qué quieres aprender coreano?": "왜 한국어를 배우고 싶으세요?",
  "K-pop, K-drama, un viaje, trabajo, la cultura... ¡Nos ayuda a conocerte! 💜": "K-pop, K-드라마, 여행, 일, 문화... 여러분을 더 잘 알 수 있게 도와줘요! 💜",
  "Enviando...": "보내는 중...",
  "Reservar cupo en {curso} →": "{curso} 자리 예약하기 →",
  "🔒 Tus datos están protegidos y no se comparten.": "🔒 개인정보는 안전하게 보호되며 공유되지 않아요.",
  "¡Cupo reservado para {nombre}!": "{nombre}님의 자리가 예약되었어요!",
  "ti": "회원",
  "Ir a pagar ↓": "결제하러 가기 ↓",
  "PASO 2 · PAGO": "2단계 · 결제",
  "Completa tu pago": "결제를 완료하세요",
  "MISMO PRECIO EN TODOS LOS CURSOS": "모든 과정 동일 가격",
  "PAGO ÚNICO": "일시불",
  "El curso completo de 8 semanas": "8주 전체 과정",
  "✓ Seleccionado": "✓ 선택됨",
  "{n} CUOTAS": "{n}회 분납",
  "Una al inscribirte y otra al inicio del mes 2": "등록 시 1회, 2개월 차 시작 시 1회",
  "c/u": "(1회분)",
  "Fuera de Chile se coordina por WhatsApp": "칠레 밖에서는 WhatsApp으로 안내해 드려요",
  "Incluye:": "포함 내역:",
  "8 clases en vivo por Zoom (60 min c/u)": "줌(Zoom) 실시간 수업 8회 (회당 60분)",
  "Certificado de Academia Seúl al terminar": "수료 시 아카데미아 서울 수료증",
  "Grabaciones privadas, solo para las familias del grupo": "비공개 녹화본, 우리 반 가족만 볼 수 있어요",
  "Grabaciones de cada clase (24 h después)": "매 수업 녹화본 (24시간 후 제공)",
  "Slides + hojas de actividad por sesión": "회차별 슬라이드 + 활동지",
  "Lector de Hangul con audio nativo (tarea gamificada)": "원어민 음성 한글 리더 (게임형 과제)",
  "Pronunciación corregida personalmente": "개인별 발음 교정",
  "Grupo chico (máx. {n})": "소규모 그룹 (최대 {n}명)",
  "Grupo de WhatsApp solo para apoderados": "보호자 전용 WhatsApp 그룹",
  "Comunidad de alumnos por WhatsApp/Discord": "WhatsApp/Discord 수강생 커뮤니티",
  "¿Desde dónde pagas?": "어디에서 결제하시나요?",
  "🇨🇱 Chile": "🇨🇱 칠레",
  "🌎 Otro país": "🌎 다른 나라",
  "ELIGE CÓMO PAGAR": "결제 방법을 선택하세요",
  "🏦 Transferencia bancaria · Chile": "🏦 계좌이체 · 칠레",
  "RECOMENDADO · SIN COMISIÓN": "추천 · 수수료 없음",
  "Sin comisión: el monto llega completo ({monto} — te confirmamos el monto exacto). Escríbenos y te enviamos los datos.": "수수료 없이 금액이 그대로 입금돼요 ({monto} — 정확한 금액은 따로 확인해 드려요). 연락 주시면 계좌 정보를 보내 드릴게요.",
  "{clp} por cuota": "분납 1회당 {clp}",
  "📲 Pedir datos por WhatsApp": "📲 WhatsApp으로 계좌 정보 받기",
  "o paga al instante con": "또는 다음 방법으로 바로 결제",
  "Abriendo pago seguro…": "안전 결제 창을 여는 중…",
  "💳 Tarjeta de crédito / débito · Mercado Pago ({plan})": "💳 신용/체크카드 · Mercado Pago ({plan})",
  "Visa, Mastercard y débito · se cobra el equivalente en CLP. Reserva tu cupo arriba antes de pagar.": "Visa, Mastercard, 체크카드 · CLP 환산 금액으로 결제돼요. 결제 전에 위에서 먼저 자리를 예약해 주세요.",
  "🌐 Tarjeta en tu moneda (USD/EUR/local) · Hotmart": "🌐 내 통화로 카드 결제 (USD/EUR/현지 통화) · Hotmart",
  "💳 Mercado Pago ({plan})": "💳 Mercado Pago ({plan})",
  "Se cobra en pesos chilenos; tu banco puede cobrar comisión por cambio de moneda.": "칠레 페소로 결제되며, 은행에 따라 환전 수수료가 붙을 수 있어요.",
  "¿Prefieres transferencia internacional?": "해외 송금을 원하시나요?",
  "Escríbenos por WhatsApp": "WhatsApp으로 문의하기",
  "PASO 3 · CONFIRMA": "3단계 · 확인하기",
  "¿Ya hiciste tu pago?": "결제를 완료하셨나요?",
  "Mercado Pago (tarjeta)": "Mercado Pago (카드)",
  "Transferencia bancaria": "계좌이체",
  "Ya pagué con {metodo}": "{metodo}로 결제했어요",
  "Enviando confirmación…": "확인 내용을 보내는 중…",
  "¡Gracias, {nombre}! Registramos tu pago.": "{nombre}님, 감사해요! 결제가 접수되었어요.",
  "¡Gracias! Registramos tu pago.": "감사해요! 결제가 접수되었어요.",
  "Verificamos y te confirmamos el cupo por correo/WhatsApp en las próximas horas. 화이팅!": "확인 후 몇 시간 안에 이메일/WhatsApp으로 자리를 확정해 드릴게요. 화이팅!",
  "🔒 Certificado incluido · Grabaciones incluidas · Tu información está protegida": "🔒 수료증 포함 · 녹화본 포함 · 개인정보는 안전하게 보호돼요",
  "¿Listo para empezar?": "시작할 준비 되셨나요?",
  "Las clases arrancan {inicio} — {precio}. Certificado incluido.": "수업은 {inicio}에 시작해요 — {precio}. 수료증 포함.",
  "Hola Jay! Tengo una duda sobre los cursos de octubre.": "안녕하세요 Jay! 10월 과정에 대해 궁금한 점이 있어요.",
  "💬 Hablar con Jay primero": "💬 먼저 Jay와 이야기하기",
  "화이팅 chingu! Nos vemos {inicio}.": "화이팅 친구! {inicio}에 만나요.",
  "🌍 PayPal · en dólares ({monto})": "🌍 PayPal · 달러 결제 ({monto})",
  "US${m} por cuota": "분납 1회당 US${m}",
  "🌍 PayPal en {n} cuotas · te enviamos el link por WhatsApp": "🌍 PayPal {n}회 분납 · WhatsApp으로 링크를 보내 드려요",
  "{curso} · {dia} {hora} Chile. Te escribimos a **{correo}**. Ahora elige cómo pagar abajo para confirmar el lugar.": "{curso} · {dia} {hora} 칠레 시간. **{correo}**로 연락드릴게요. 이제 아래에서 결제 방법을 골라 자리를 확정해 주세요.",
  "Recomendado fuera de Chile · pagas en dólares con cualquier tarjeta, **sin cuenta PayPal** (opción “Pagar con tarjeta”).": "칠레 외 지역 추천 · 어떤 카드로든 달러로 결제할 수 있고, **PayPal 계정 없이도** 가능해요 (“카드로 결제” 옵션).",
  "Cuando termines en PayPal, vuelve a esta pestaña y toca **“Ya pagué con PayPal”** para que reservemos tu cupo.": "PayPal 결제를 마치면 이 탭으로 돌아와 **“PayPal로 결제했어요”**를 눌러 주세요. 그래야 자리를 예약해 드릴 수 있어요.",
  "Confírmalo aquí y reservamos el cupo en **{curso}**. Te escribimos por correo/WhatsApp para darte la bienvenida.": "여기서 확인해 주시면 **{curso}** 자리를 예약해 드려요. 이메일/WhatsApp으로 환영 인사를 보내 드릴게요.",
  // ── app/notificarme/page.tsx
  "Básico 1 (A1.1)": "기초 1 (A1.1)",
  "Básico 2 (A1.2)": "기초 2 (A1.2)",
  "Conversacional 1 (A2.1)": "회화 1 (A2.1)",
  "Coreano para Niños (8–12)": "어린이 한국어 (8–12세)",
  "TOPIK II (B1+)": "TOPIK II (B1+)",
  "Conversacional 2 (A2.2)": "회화 2 (A2.2)",
  "los próximos cursos": "다음 과정",
  "Argentina": "아르헨티나",
  "Bolivia": "볼리비아",
  "Chile": "칠레",
  "Colombia": "콜롬비아",
  "Costa Rica": "코스타리카",
  "Cuba": "쿠바",
  "Ecuador": "에콰도르",
  "El Salvador": "엘살바도르",
  "España": "스페인",
  "Estados Unidos": "미국",
  "Guatemala": "과테말라",
  "Honduras": "온두라스",
  "México": "멕시코",
  "Nicaragua": "니카라과",
  "Panamá": "파나마",
  "Paraguay": "파라과이",
  "Perú": "페루",
  "Puerto Rico": "푸에르토리코",
  "República Dominicana": "도미니카공화국",
  "Uruguay": "우루과이",
  "Venezuela": "베네수엘라",
  "Cero, nunca estudié": "전혀 없음, 배운 적 없어요",
  "Sé leer el alfabeto (한글)": "한글을 읽을 수 있어요",
  "Nivel A1 básico": "A1 기초 레벨",
  "Terminé Básico 1 o equivalente": "기초 1 또는 동급 과정을 마쳤어요",
  "Nivel A2 o intermedio": "A2 또는 중급 레벨",
  "Nivel B1 o superior": "B1 이상 레벨",
  "K-pop / K-dramas": "K-pop / K-드라마",
  "Viajar a Corea": "한국 여행",
  "Trabajo o negocios": "업무 또는 비즈니스",
  "Pareja o familia coreana": "한국인 파트너 또는 가족",
  "Cultura coreana en general": "한국 문화 전반",
  "Estudiar en Corea (TOPIK)": "한국 유학 (TOPIK)",
  "Hubo un problema al enviarte. Intenta nuevamente.": "전송 중 문제가 발생했어요. 다시 시도해 주세요.",
  "¡Listo, {nombre}!": "완료됐어요, {nombre}!",
  "Te aviso apenas abramos cupos de": "자리가 열리면 바로 알려 드릴게요 —",
  "Recibirás un email con acceso prioritario a horarios y cupos.": "시간표와 자리에 우선 접근할 수 있는 이메일을 보내 드릴게요.",
  "← Volver al inicio": "← 홈으로 돌아가기",
  "🎓 ¡Buenas noticias! {curso} ya tiene matrícula abierta.": "🎓 좋은 소식이에요! {curso} 등록 접수 중이에요.",
  "Las clases empiezan {inicio} de 2026 — 8 semanas, certificado incluido, {precio}. No necesitas lista de espera: elige tu horario y reserva tu cupo.": "수업은 2026년 {inicio}에 시작해요 — 8주, 수료증 포함, {precio}. 대기 명단은 필요 없어요: 시간을 고르고 자리를 예약하세요.",
  "Inscribirme · Octubre 2026 →": "등록하기 · 2026년 10월 →",
  "¿Prefieres que te avisemos para una cohorte futura? Deja tus datos abajo.": "다음 기수 알림을 받고 싶으세요? 아래에 정보를 남겨 주세요.",
  "Lista de espera": "대기 명단",
  "Te avisamos cuando lance": "오픈되면 바로 알려 드릴게요 —",
  "Sé el/la primer/a en saber cuando abramos cupos. Los miembros de la lista de espera tienen acceso prioritario a horarios y cupos.": "자리가 열리면 가장 먼저 소식을 받아 보세요. 대기 명단에 계신 분들은 시간표와 자리에 우선 접근할 수 있어요.",
  "Tu nombre": "이름",
  "Cómo te llamamos": "어떻게 불러 드릴까요?",
  "Tu email": "이메일",
  "donde te avisamos": "알림을 받을 이메일",
  "Tu teléfono / WhatsApp": "전화번호 / WhatsApp",
  "Tu país": "국가",
  "Selecciona tu país": "국가를 선택하세요",
  "¿Cuál es tu nivel de coreano?": "한국어 레벨이 어떻게 되세요?",
  "Selecciona tu nivel": "레벨을 선택하세요",
  "Mensaje adicional": "추가 메시지",
  "Cuéntanos algo más, si quieres": "더 하고 싶은 말이 있다면 적어 주세요",
  "💌 Apúntame a la lista de espera": "💌 대기 명단에 등록하기",
  "Sin spam. Sin cargos. Solo te avisamos cuando lancemos.": "스팸 없음. 비용 없음. 오픈할 때만 알려 드려요.",
  "¿Prefieres hablar directo? Escríbele a Jay por WhatsApp:": "직접 이야기하고 싶으세요? WhatsApp으로 Jay에게 메시지를 보내세요:",
  "Hola Jay! Quiero más información sobre {curso}.": "안녕하세요 Jay! {curso}에 대해 더 알고 싶어요.",
  "💬 Hablar con Jay por WhatsApp": "💬 WhatsApp으로 Jay와 이야기하기",
  "¿Quieres empezar YA? Aprende a leer coreano gratis con el Lector de Hangul:": "지금 바로 시작하고 싶으세요? 한글 리더로 무료로 한국어 읽기를 배워 보세요:",
  "🐯 Lector de Hangul — gratis con audio nativo →": "🐯 한글 리더 — 원어민 음성 포함, 무료 →",
  "Cargando...": "로딩 중...",
  // ── app/test-nivel/page.tsx
  "¿Puedes leer esto?": "이걸 읽을 수 있나요?",
  "Ni idea, son dibujitos para mí": "전혀요, 제 눈엔 그냥 그림이에요",
  "Reconozco alguna letra": "몇 글자는 알아보겠어요",
  "Sí, dice \"annyeong\"": "네, \"annyeong\"이라고 읽어요",
  "¿Sabes qué es el 한글 (hangul)?": "한글 (hangul)이 뭔지 아세요?",
  "No": "아니요",
  "He oído el término": "들어 본 적은 있어요",
  "Es el alfabeto coreano, claro": "당연히 알죠, 한국어 문자예요",
  "¿Has estudiado coreano antes?": "한국어를 배운 적이 있나요?",
  "Nunca, parto de cero": "아니요, 완전 처음이에요",
  "Por mi cuenta (apps, videos)": "혼자서 (앱, 영상으로)",
  "En clases o academia": "수업이나 학원에서",
  "La partícula 은/는, ¿para qué sirve?": "은/는 조사는 어떤 역할을 하나요?",
  "No tengo idea": "전혀 모르겠어요",
  "Creo que marca el tema de la frase": "문장의 주제를 표시하는 것 같아요",
  "Sí, marca el tema/sujeto": "네, 주제/주어를 표시해요",
  "¿Puedes presentarte en coreano? (저는 ...이에요)": "한국어로 자기소개를 할 수 있나요? (저는 ...이에요)",
  "Para nada": "전혀요",
  "Más o menos, con ayuda": "도움이 있으면 어느 정도",
  "Sí, sin problema": "네, 문제없어요",
  "🎵 Entender K-pop y K-dramas": "🎵 K-pop과 K-드라마 이해하기",
  "✈️ Viajar o vivir en Corea": "✈️ 한국 여행 또는 한국 생활",
  "📜 Dar el examen TOPIK": "📜 TOPIK 시험 보기",
  "💜 Hobby y cultura": "💜 취미와 문화",
  "Principiante total": "완전 초보",
  "Estás partiendo desde cero — el lugar perfecto para empezar bien. Básico 1 (A1.1) te enseña a leer hangul en la primera semana y a construir tus primeras frases. Martes o jueves 20:00 (Chile), desde la semana del 5 de octubre.": "완전히 처음부터 시작하시네요 — 제대로 시작하기에 딱 좋은 자리예요. 기초 1 (A1.1)에서는 첫 주에 한글 읽는 법을 배우고 첫 문장을 만들어요. 화요일 또는 목요일 20:00 (칠레 시간), 10월 5일 주부터.",
  "Básico 1 (A1.1) · desde cero": "기초 1 (A1.1) · 처음부터",
  "Falso principiante": "왕초보는 아닌 초보",
  "Ya tienes contacto con el idioma, pero te faltan bases ordenadas. Básico 1 te llena los huecos y te da estructura para avanzar de verdad — y si ya lees hangul con soltura, Básico 2 (miércoles 21:00) es tu curso.": "이미 한국어를 접해 봤지만 체계적인 기초가 부족해요. 기초 1이 빈틈을 메우고 제대로 나아갈 구조를 잡아 줘요 — 이미 한글을 술술 읽는다면 기초 2 (수요일 21:00)가 딱이에요.",
  "Básico 1 (A1.1) · o Básico 2 si ya lees hangul": "기초 1 (A1.1) · 또는 한글을 읽을 수 있다면 기초 2",
  "Tienes bases": "기초가 있어요",
  "Vas bien. Básico 2 (A1.2, miércoles 21:00) te lleva al pasado y al futuro; si ya conversas, Conversacional 1 (A2.1) con profesora nativa (martes 21:00) es para ti. ¿Vas por el examen? TOPIK II (B1+), jueves 21:00.": "잘하고 계세요. 기초 2 (A1.2, 수요일 21:00)에서는 과거와 미래를 배워요. 이미 대화가 된다면 원어민 선생님과 함께하는 회화 1 (A2.1) (화요일 21:00)이 딱이에요. 시험이 목표라면? TOPIK II (B1+), 목요일 21:00.",
  "Básico 2 (A1.2) · Conversacional 1 (A2.1) · o TOPIK II (B1+)": "기초 2 (A1.2) · 회화 1 (A2.1) · 또는 TOPIK II (B1+)",
  "Test de nivel": "레벨 테스트",
  "¿Qué nivel de coreano": "내 한국어 레벨은",
  "tienes": "어디쯤",
  "5 preguntas rápidas. Te decimos por dónde empezar (y te mandamos tu guía gratis).": "빠른 질문 5개. 어디서 시작하면 좋을지 알려 드려요 (무료 가이드도 보내 드릴게요).",
  "Pregunta {n} de {total}": "질문 {n} / {total}",
  "Última: ¿cuál es tu meta principal?": "마지막: 가장 중요한 목표는 뭐예요?",
  "¡Listo! Tu resultado está calculado.": "완료! 결과가 계산되었어요.",
  "Tu correo": "이메일",
  "Calculando…": "계산 중…",
  "Ver mi resultado →": "내 결과 보기 →",
  "🔒 Sin spam. Solo tu resultado y tips de coreano.": "🔒 스팸 없음. 결과와 한국어 팁만 보내 드려요.",
  "Tu resultado · {score}/10": "내 결과 · {score}/10",
  "Recomendado para ti": "추천 과정",
  "Tu meta: {goal}": "내 목표: {goal}",
  "Descargar mi guía": "가이드 다운로드",
  "Déjanos dónde enviarte tu resultado + la **guía del alfabeto gratis** y lo ves al instante.": "결과와 **무료 한글 가이드**를 받을 곳을 남겨 주시면 바로 확인할 수 있어요.",
  // ── components/About.tsx
  "Nativo de Seúl": "서울 출신",
  "Bilingüe español": "스페인어 이중언어",
  "8+ años enseñando": "8년 이상 교육 경력",
  "Tu chingu coreano": "당신의 한국인 친구",
  "Un profe de Seúl que llegó a Chile a los 10": "10살에 칠레로 온 서울 출신 선생님이",
  "y te explica el coreano desde tu español.": "당신의 스페인어를 바탕으로 한국어를 설명합니다.",
  "Jay se presenta": "Jay의 자기소개",
  "▶ Conóceme en video": "▶ 영상으로 만나보세요",
  ", soy": ", 저는",
  "— mejor conocido como Jay. Nací en Seúl, llegué a Chile a los 10 años, y crecí entre kimchi y empanadas — entre": "— 다들 Jay라고 불러요. 서울에서 태어나 10살에 칠레로 왔고, 김치와 엠파나다 사이에서 자랐어요 —",
  "y español.": "그리고 스페인어 사이에서요.",
  "De día soy gerente en una empresa coreana de genómica en Las Condes. De noche hago lo que más amo: enseñar mi idioma a quienes lo aprenden por amor a la cultura. Academia Seúl nació para construir el puente que yo no tuve a los 10.": "낮에는 라스콘데스에 있는 한국 유전체 기업에서 매니저로 일해요. 밤에는 가장 사랑하는 일을 해요: 문화를 사랑해서 한국어를 배우는 분들에게 제 언어를 가르치는 일이요. 아카데미아 서울은 제가 10살 때 갖지 못했던 그 다리를 놓기 위해 태어났어요.",
  "En clase también te acompañan Guiran, profesora coreana criada en Argentina, y Abby, profesora nativa que enseña en vivo desde Corea.": "수업에는 아르헨티나에서 자란 한국인 선생님 기란과 한국에서 실시간으로 가르치는 원어민 선생님 Abby도 함께합니다.",
  "Conoce nuestra historia": "우리 이야기 보기",
  "años enseñando coreano\na hispanohablantes": "년간 스페인어권 학습자에게\n한국어를 가르쳐 온 경력",
  // ── components/Benefits.tsx
  "Profesores coreanos nativos": "한국인 원어민 선생님",
  "Aprende la pronunciación y el acento real desde el primer día. Nuestros profesores son coreanos nativos y bilingües, y traen la cultura viva al aula.": "첫날부터 진짜 발음과 억양을 배워요. 우리 선생님들은 한국인 원어민이자 이중언어 사용자로, 살아 있는 문화를 교실로 가져와요.",
  "Grupos reducidos": "소규모 그룹",
  "Máximo 15 estudiantes por clase (8 en TOPIK II, 12 en Niños). Más tiempo de práctica oral, más feedback personalizado y un ambiente donde realmente puedes equivocarte y aprender.": "수업당 최대 15명 (TOPIK II는 8명, 어린이는 12명). 더 많은 말하기 연습 시간, 더 많은 맞춤 피드백, 그리고 마음 놓고 틀리면서 배울 수 있는 분위기.",
  "Metodología innovadora": "혁신적인 교수법",
  "Combinamos comunicación oral, gramática funcional y cultura contemporánea. Sin aburrimiento. Sin memorizar tablas interminables.": "말하기 소통, 실용 문법, 현대 문화를 결합했어요. 지루함 없이. 끝없는 표 암기 없이.",
  "TOPIK II (B1+): preparación oficial": "TOPIK II (B1+): 공식 시험 대비",
  "Somos tu puerta al certificado internacional TOPIK I y TOPIK II. Te preparamos con simulacros, estrategias y material oficial.": "TOPIK I과 TOPIK II 국제 공인 자격증으로 가는 관문이에요. 모의고사, 전략, 공식 자료로 함께 준비해요.",
  "Grabaciones incluidas": "녹화본 포함",
  "¿Te pierdes una clase? Recibes la grabación en 24 horas. Todas las clases son 100% online en vivo por Zoom.": "수업을 놓쳤나요? 24시간 안에 녹화본을 받아요. 모든 수업은 100% 온라인 줌(Zoom) 실시간 수업이에요.",
  "Materiales incluidos": "교재 포함",
  "Slides, hojas de actividad y el Lector de Hangul con audio nativo, incluidos en cada curso. Sin comprar libros.": "슬라이드, 활동지, 원어민 음성이 담긴 한글 리더가 모든 과정에 포함돼요. 책을 살 필요 없어요.",
  "Comunidad vibrante": "활기찬 커뮤니티",
  "Sé parte de la comunidad Chingu: alumnos de toda Latinoamérica y España aprendiendo coreano juntos.": "친구 커뮤니티의 일원이 되세요: 라틴아메리카 전역과 스페인의 학생들이 함께 한국어를 배워요.",
  "Certificado por participación": "참여 수료증",
  "Al completar tu curso recibes el certificado de Academia Seúl de tu nivel (A1.1, A1.2, A2.1, TOPIK II o Niños). Tu avance queda respaldado peldaño a peldaño.": "과정을 마치면 해당 레벨(A1.1, A1.2, A2.1, TOPIK II 또는 어린이)의 아카데미아 서울 수료증을 받아요. 한 단계 한 단계 실력이 증명돼요.",
  "¿Por qué elegirnos?": "왜 아카데미아 서울일까요?",
  "Todo lo que necesitas": "한국어로 말하는 데",
  "para": "필요한",
  "hablar coreano": "모든 것",
  "No somos una academia más. Una nueva forma de aprender coreano desde Latinoamérica, diseñada para hispanohablantes.": "흔한 학원이 아니에요. 라틴아메리카에서 한국어를 배우는 새로운 방식, 스페인어권 학습자를 위해 설계했어요.",
  // ── components/CTASection.tsx
  "Hacer el test de nivel gratis": "무료 레벨 테스트 하기",
  "¿Listo para hablar": "말할 준비 됐나요,",
  "coreano de verdad?": "진짜 한국어로?",
  "Clases en vivo desde la semana del 5 de octubre · 8 semanas · certificado incluido. US$150 el curso completo · o 2 cuotas de US$75.": "10월 5일 주부터 실시간 수업 · 8주 · 수료증 포함. 전체 과정 US$150 · 또는 US$75씩 2회 분납.",
  "La matrícula cierra el domingo 4 de octubre.": "등록은 10월 4일(일)에 마감됩니다.",
  "✓ Grabación de cada clase en 24 h": "✓ 24시간 내 수업 녹화본 제공",
  "✓ Máx. 15 alumnos (8 en TOPIK II · 12 en Niños)": "✓ 최대 15명 (TOPIK II 8명 · 어린이 12명)",
  "✓ Certificado incluido": "✓ 수료증 포함",
  // ── components/Contact.tsx
  "Desde cero (nunca estudié)": "완전 처음 (배운 적 없음)",
  "Leo Hangul y me presento (Básico 1 hecho)": "한글을 읽고 자기소개를 해요 (기초 1 수료)",
  "Fui alumno/a del Nivel 1 de julio": "레벨 1 (7월) 수강생이었어요",
  "Converso algo (A2)": "간단한 대화가 돼요 (A2)",
  "Intermedio · voy por el TOPIK II": "중급 · TOPIK II 준비 중",
  "No sé mi nivel": "제 레벨을 모르겠어요",
  "K-pop / K-drama": "K-pop / K-드라마",
  "Viaje a Corea": "한국 여행",
  "No sé, ayúdenme a elegir": "모르겠어요, 골라 주세요",
  "Hola Jay! Vi academiaseul.com y quiero información sobre los cursos de coreano.": "안녕하세요 Jay! academiaseul.com을 보고 한국어 과정 정보를 알고 싶어서 연락드려요.",
  "Hubo un problema al enviar tu mensaje. Por favor intenta nuevamente.": "메시지 전송 중 문제가 발생했어요. 다시 시도해 주세요.",
  "Contáctanos": "문의하기",
  "¿Quieres hablar": "선생님과",
  "con un profesor?": "직접 이야기해 볼래요?",
  "¿Tienes dudas o quieres saber qué curso te conviene? Lo más rápido es escribirle a Jay por WhatsApp — o déjanos el formulario y te respondemos en menos de 24 h.": "궁금한 점이 있거나 어떤 과정이 맞는지 알고 싶나요? 가장 빠른 방법은 Jay에게 WhatsApp으로 연락하는 거예요 — 아니면 양식을 남겨 주시면 24시간 안에 답해 드려요.",
  "¡Mensaje recibido!": "메시지를 받았어요!",
  "Te escribimos en las próximas 24 h con toda la información. ¡Hasta pronto!": "24시간 안에 자세한 정보를 담아 연락드릴게요. 곧 만나요!",
  "Ej. María González": "예: 김민지",
  "Teléfono / WhatsApp": "전화 / WhatsApp",
  "Correo electrónico *": "이메일 *",
  "Nivel actual": "현재 레벨",
  "Me interesa": "관심 분야",
  "Selecciona un interés": "관심 분야를 선택하세요",
  "Mensaje (opcional)": "메시지 (선택)",
  "Cuéntanos sobre tus objetivos, disponibilidad o cualquier pregunta...": "목표, 가능한 시간, 궁금한 점 등을 알려 주세요...",
  "Hablar con un profesor →": "선생님과 이야기하기 →",
  "Al enviar aceptas ser contactado por Academia Seúl. No compartimos tus datos.": "전송하면 아카데미아 서울의 연락을 받는 데 동의하는 거예요. 개인정보는 공유하지 않아요.",
  "Información de contacto": "연락처 정보",
  "Email": "이메일",
  "Dirección": "주소",
  "Síguenos": "팔로우하기",
  "Horarios de atención": "상담 시간",
  "Lunes – Viernes": "월요일 – 금요일",
  "Sábados": "토요일",
  "Domingos": "일요일",
  "Cerrado": "휴무",
  "Escribirle a Jay por WhatsApp · +56 9 4211 5562": "Jay에게 WhatsApp 보내기 · +56 9 4211 5562",
  // ── components/Courses.tsx
  "Niños 8–12": "어린이 8–12세",
  "Paso {n} · {cefr}": "{n}단계 · {cefr}",
  "antes: {alias}": "이전 명칭: {alias}",
  "Horario": "수업 시간",
  "Profe": "선생님",
  "Duración": "기간",
  "8 semanas · 60 min": "8주 · 60분",
  "Precio": "가격",
  "Inscribir a mi hijo/a": "우리 아이 등록하기",
  "Inscribirme en {curso}": "{curso} 등록하기",
  "Cohorte octubre 2026": "2026년 10월 기수",
  "Matrícula abierta · cierra el 4 de octubre": "등록 접수 중 · 10월 4일 마감",
  "Encuentra tu": "나에게 맞는",
  "peldaño": "단계 찾기",
  "5 cursos · 6 horarios · 8 semanas desde la semana del 5 de octubre.": "5개 과정 · 6개 시간대 · 10월 5일 주부터 8주.",
  "— mismo precio en todos los cursos.": "— 모든 과정 동일 가격.",
  "Adultos · la escalera": "성인 · 레벨 사다리",
  "Niños 8–12 · ruta propia": "어린이 8–12세 · 전용 코스",
  "Todo incluido en tu curso": "수강료에 모두 포함",
  "🎥 8 semanas en vivo por Zoom · 60 min por clase": "🎥 Zoom 실시간 수업 8주 · 회당 60분",
  "⏺ Grabación de cada clase en 24 h": "⏺ 24시간 내 수업 녹화본 제공",
  "📚 Slides, hojas de actividad y Lector de Hangul": "📚 슬라이드, 활동지, 한글 리더",
  "🎓 Certificado de Academia Seúl al terminar": "🎓 수료 시 아카데미아 서울 수료증",
  "Próximamente · enero 2027": "오픈 예정 · 2027년 1월",
  "Avísame cuando abra": "오픈하면 알려주세요",
  "Elegir mi clase →": "내 수업 선택하기 →",
  "Ver el programa completo y los horarios →": "전체 커리큘럼과 시간표 보기 →",
  "¿Nunca estudiaste coreano? Tu curso es **Básico 1**. ¿Ya sabes algo? Haz el test de nivel.": "한국어가 처음이세요? 당신의 과정은 **기초 1**이에요. 이미 조금 아시나요? 레벨 테스트를 해보세요.",
  // ── components/EquipoProfes.tsx
  "tu profe": "담당 선생님",
  // ── components/Escalera.tsx
  "Nunca estudié coreano": "한국어를 배운 적이 없어요",
  "Tu curso es Básico 1 (A1.1): empiezas leyendo el alfabeto y terminas presentándote.": "당신의 과정은 기초 1 (A1.1): 한글 읽기로 시작해서 자기소개로 마무리해요.",
  "Ya leo Hangul": "한글을 읽을 수 있어요",
  "Si ya lees 한글 y te presentas, tu curso es Básico 2 (A1.2): del presente al pasado y al futuro.": "이미 한글을 읽고 자기소개를 할 수 있다면, 당신의 과정은 기초 2 (A1.2): 현재에서 과거와 미래로 나아가요.",
  "Terminé el Nivel 1 de julio": "7월 레벨 1을 마쳤어요",
  "¿Fuiste alumno/a del Nivel 1 en julio? Ese curso hoy se llama Básico 1 (A1.1). Tu siguiente paso es Básico 2 (A1.2) · miércoles 21:00 Chile · con Jay.": "7월 레벨 1 수강생이었나요? 그 과정은 이제 기초 1 (A1.1)이라고 불러요. 다음 단계는 기초 2 (A1.2) · 수요일 21:00 칠레 시간 · Jay 선생님과 함께.",
  "Quiero hablar": "말하고 싶어요",
  "Con Básico 2 terminado (o test de nivel), Conversacional 1 (A2.1) con la Prof.ª Abby: puro hablar con una nativa.": "기초 2를 마쳤다면 (또는 레벨 테스트 후), Abby 선생님과 함께하는 회화 1 (A2.1): 원어민과 오직 말하기만 해요.",
  "Voy por el TOPIK": "TOPIK을 준비해요",
  "Grupo de máximo 8 enfocado 100% en el examen oficial: TOPIK II (B1+) · jueves 21:00 Chile · con Jay.": "최대 8명, 공식 시험에 100% 집중하는 그룹: TOPIK II (B1+) · 목요일 21:00 칠레 시간 · Jay 선생님과 함께.",
  "Es para mi hijo/a": "우리 아이를 위한 거예요",
  "Coreano para Niños (8–12): lunes 18:00 Chile, juegos, canciones y un show final para la familia.": "어린이 한국어 (8–12세): 월요일 18:00 칠레 시간, 게임과 노래, 그리고 가족을 위한 마지막 발표회까지.",
  "Abre en {cuando}": "{cuando} 오픈",
  "¿Cuál es tu caso?": "당신은 어떤 경우인가요?",
  "Ir a {curso} →": "{curso} 보러 가기 →",
  "enero 2027": "2027년 1월",
  "paso {n}": "{n}단계",
  "tu curso": "당신의 과정",
  "carril propio para niños y niñas": "어린이 전용 코스",
  // ── components/FAQ.tsx
  "¿Necesito saber algo de coreano para empezar?": "시작하려면 한국어를 좀 알아야 하나요?",
  "No. Básico 1 (A1.1) y Coreano para Niños están pensados para empezar desde cero: lo primero que aprendes es a leer el alfabeto (한글). Si ya sabes algo, tienes Básico 2 (A1.2), Conversacional 1 (A2.1) y TOPIK II — haz el test de nivel gratuito o escríbenos y te ayudamos a elegir tu curso.": "아니요. 기초 1 (A1.1)과 어린이 한국어는 완전 처음부터 시작하도록 만들어졌어요: 가장 먼저 배우는 건 알파벳(한글) 읽기예요. 이미 조금 아신다면 기초 2 (A1.2), 회화 1 (A2.1), TOPIK II가 있어요 — 무료 레벨 테스트를 해 보거나 연락 주시면 딱 맞는 반을 골라 드려요.",
  "¿Cuánto cuesta y qué incluye?": "비용은 얼마이고 무엇이 포함되나요?",
  "Mismo precio en todos los cursos: US$150 el curso completo o 2 cuotas de US$75. Incluye las 8 clases en vivo (60 min), grabaciones, material de estudio, el Lector de Hangul, certificado de Academia Seúl y acceso a la comunidad. El programa completo está en /programa.": "모든 과정이 같은 가격이에요: 전체 과정 US$150 또는 US$75 × 2회 분납. 실시간 수업 8회(60분), 녹화본, 학습 자료, 한글 리더, 아카데미아 서울 수료증, 커뮤니티 이용이 포함돼요. 전체 프로그램은 /programa에서 확인하세요.",
  "¿Qué horarios y fechas hay?": "수업 시간과 일정은 어떻게 되나요?",
  "La cohorte parte la semana del 5 de octubre de 2026 y dura 8 semanas (una clase por semana, hora de Chile): Coreano para Niños lunes 18:00 · Básico 1 martes 20:00 o jueves 20:00 · Conversacional 1 martes 21:00 · Básico 2 miércoles 21:00 · TOPIK II jueves 21:00. Conversión rápida: 20:00 Chile = 18:00 Colombia/Perú · 17:00 México · 20:00 Argentina · 19:00 EE.UU. Este (18:00 desde el 1 de noviembre) · 01:00 España (00:00 desde el 25 de octubre). En la página de inscripción eliges tu país y ves la hora exacta.": "이번 기수는 2026년 10월 5일 주에 시작해 8주간 진행돼요(주 1회 수업, 칠레 시간 기준): 어린이 한국어 월요일 18:00 · 기초 1 화요일 20:00 또는 목요일 20:00 · 회화 1 화요일 21:00 · 기초 2 수요일 21:00 · TOPIK II 목요일 21:00. 빠른 환산: 칠레 20:00 = 콜롬비아/페루 18:00 · 멕시코 17:00 · 아르헨티나 20:00 · 미국 동부 19:00 (11월 1일부터 18:00) · 스페인 01:00 (10월 25일부터 00:00). 등록 페이지에서 국가를 선택하면 정확한 시간을 볼 수 있어요.",
  "En vivo por Zoom, en grupos pequeños con cupos limitados. Así resolvemos dudas al momento y corregimos tu pronunciación en tiempo real. Si te pierdes alguna, recibes la grabación en 24 horas y puedes escribirnos para resolver dudas de esa clase.": "줌(Zoom)으로 진행하는 실시간 수업이고, 정원이 제한된 소규모 그룹이에요. 그래서 궁금한 점은 바로 해결하고 발음도 실시간으로 교정해 드려요. 수업을 놓치면 24시간 안에 녹화본을 받고, 그 수업에 대한 질문은 따로 연락 주셔도 돼요.",
  "¿Cómo puedo pagar?": "결제는 어떻게 하나요?",
  "Transferencia bancaria en Chile (sin comisión), tarjeta de crédito/débito vía Mercado Pago (se cobra en pesos chilenos) o PayPal en dólares — también con tarjeta, sin tener cuenta PayPal. Puedes pagar los US$150 de una vez o en 2 cuotas de US$75. Te confirmamos por correo apenas registramos tu pago.": "칠레 내 계좌이체(수수료 없음), Mercado Pago를 통한 신용/체크카드 결제(칠레 페소로 청구), 또는 달러로 PayPal 결제 — PayPal 계정 없이 카드로도 가능해요. US$150를 일시불로 내거나 US$75 × 2회로 분납할 수 있어요. 입금이 확인되는 대로 이메일로 알려 드려요.",
  "¿Recibo un certificado?": "수료증을 받을 수 있나요?",
  "Sí, está incluido en todos los cursos. Al completar tu curso recibes el certificado de Academia Seúl del nivel correspondiente (Básico 1 · A1.1, Básico 2 · A1.2, Conversacional 1 · A2.1, TOPIK II o Niños), en base a tu asistencia y participación. Si tienes el certificado Nivel 1 (cohorte julio 2026), equivale a Básico 1 (A1.1) y te habilita directo para Básico 2.": "네, 모든 과정에 포함돼 있어요. 과정을 마치면 출석과 참여를 바탕으로 해당 레벨의 아카데미아 서울 수료증(기초 1 · A1.1, 기초 2 · A1.2, 회화 1 · A2.1, TOPIK II 또는 어린이)을 받아요. 레벨 1 (2026년 7월 기수) 수료증이 있다면 기초 1 (A1.1)과 동등하며, 바로 기초 2에 등록할 수 있어요.",
  "¿Me sirve para el examen TOPIK?": "TOPIK 시험 준비에 도움이 되나요?",
  "Sí. Nuestra escalera está alineada con el marco CEFR y el TOPIK: Básico 1 y 2 te llevan al TOPIK I, y el grupo TOPIK II (jueves 21:00 Chile) está enfocado 100% en el examen oficial, con corrección de escritura y simulacros.": "네. 저희 레벨 사다리는 CEFR과 TOPIK 체계에 맞춰져 있어요: 기초 1과 2는 TOPIK I까지 이끌어 주고, TOPIK II 반(목요일 21:00 칠레 시간)은 쓰기 첨삭과 모의고사로 공식 시험에 100% 집중해요.",
  "¿Desde qué países puedo tomar las clases?": "어느 나라에서 수업을 들을 수 있나요?",
  "Desde toda Latinoamérica, España y EE.UU. Las clases son 100% online por Zoom; solo necesitas internet y ganas de aprender. Los horarios están en hora de Chile y en la página de inscripción los ves convertidos a tu país.": "라틴아메리카 전역, 스페인, 미국 어디서나 가능해요. 수업은 줌(Zoom)으로 100% 온라인이라 인터넷과 배우고 싶은 마음만 있으면 돼요. 시간표는 칠레 시간 기준이고, 등록 페이지에서 내 나라 시간으로 환산해서 볼 수 있어요.",
  "Ese curso hoy se llama Básico 1 (A1.1) y tu certificado equivale a A1.1. Tu siguiente paso es Básico 2 (A1.2) · miércoles 21:00 Chile · con Jay. Si lo que quieres es hablar, también puedes entrar a Conversacional 1 (A2.1) con el test de nivel.": "그 과정은 지금 기초 1 (A1.1)이라고 불리고, 받으신 수료증은 A1.1에 해당해요. 다음 단계는 기초 2 (A1.2) · 수요일 21:00 칠레 시간 · Jay 선생님이에요. 말하기가 목표라면 레벨 테스트를 거쳐 회화 1 (A2.1)에 들어갈 수도 있어요.",
  "FAQ · Preguntas frecuentes": "FAQ · 자주 묻는 질문",
  "Todo lo que": "알고 싶은",
  "quieres saber": "모든 것",
  "Ver todas las preguntas →": "모든 질문 보기 →",
  "Escríbenos por WhatsApp →": "WhatsApp으로 문의하기 →",
  "Cultura coreana en el blog →": "블로그에서 한국 문화 읽기 →",
  // ── components/FaqContent.tsx
  "Hola Jay! Vi academiaseul.com y tengo una duda sobre los cursos de coreano.": "안녕하세요 Jay! academiaseul.com을 보고 한국어 과정에 대해 궁금한 점이 있어요.",
  "질문 · Preguntas frecuentes": "질문 · 자주 묻는 질문",
  "Si después de leer esto te queda alguna duda, escríbenos: te respondemos personalmente.": "읽고 나서도 궁금한 점이 남는다면 연락 주세요. 직접 답변해 드릴게요.",
  "¿Tienes otra duda?": "다른 궁금한 점이 있으신가요?",
  // ── components/Footer.tsx
  "Cursos": "과정",
  "Coreano para Niños": "어린이 한국어",
  "Inscripción octubre 2026": "2026년 10월 등록",
  "Academia": "아카데미",
  "Sobre nosotros": "저희 소개",
  "Nuestro método": "우리의 교수법",
  "Estudiantes reales": "실제 학생들",
  "Blog": "블로그",
  "Programa y syllabus": "프로그램 및 강의 계획",
  "Legal": "법적 고지",
  "Política de privacidad": "개인정보 처리방침",
  "Términos y condiciones": "이용약관",
  "Aprende coreano con un": "한국어를 함께 배워요, 당신의",
  "Academia online de coreano para hispanohablantes. Profesores nativos, método Chingu y una comunidad apasionada por la cultura coreana.": "스페인어권 학습자를 위한 온라인 한국어 아카데미. 원어민 선생님, 친구 메소드, 그리고 한국 문화를 사랑하는 커뮤니티.",
  "Santiago, Chile · Clases online por Zoom": "칠레 산티아고 · 줌(Zoom) 온라인 수업",
  "© {y} Academia Seúl. Todos los derechos reservados.": "© {y} 아카데미아 서울. 모든 권리 보유.",
  "El futuro de la enseñanza del coreano": "한국어 교육의 미래",
  // ── components/Hero.tsx
  "🎥 En vivo por Zoom · 60 min": "🎥 Zoom 실시간 · 60분",
  "👥 Grupos de máx. 15": "👥 최대 15명 소그룹",
  "🎓 Certificado incluido": "🎓 수료증 포함",
  "Puerta Gwanghwamun del palacio Gyeongbokgung, Seúl": "서울 경복궁 광화문",
  "Academia online de coreano para hispanohablantes": "스페인어권 학습자를 위한 온라인 한국어 학원",
  "Aprende coreano.": "한국어를 배우세요.",
  "Entra en Corea.": "한국 속으로 들어가세요.",
  "Clases en vivo por Zoom con profesores coreanos nativos, para hispanohablantes de Latinoamérica y España. Gramática explicada desde tu español: lees": "라틴아메리카와 스페인의 스페인어 사용자를 위한, 한국인 원어민 선생님과 함께하는 Zoom 실시간 수업. 스페인어를 바탕으로 문법을 설명합니다: 첫 주에",
  "desde la primera semana y hablas desde el día uno.": "읽기를 익히고, 첫날부터 말합니다.",
  "Cohorte octubre 2026 · 8 semanas desde la semana del 5 de octubre · US$150 el curso completo · o 2 cuotas de US$75": "2026년 10월 기수 · 10월 5일 주부터 8주 · 전체 과정 US$150 · 또는 US$75씩 2회 분납",
  "¿Nunca estudiaste coreano?": "한국어를 처음 배우시나요?",
  "Empiezas en Básico 1 (A1.1) →": "기초 1 (A1.1)부터 시작하세요 →",
  "Ver los cursos": "과정 보기",
  // ── components/HomeBanners.tsx
  "Dubu · el puzzle del Hangul": "두부 · 한글 퍼즐",
  "Combina consonante + vocal y forma la palabra que lees o que escuchas. 30 niveles con voz nativa.": "자음 + 모음을 조합해 읽거나 들은 단어를 만드세요. 원어민 음성, 30개 레벨.",
  "Jugar a Dubu →": "두부 하러 가기 →",
  "Lector de Hangul": "한글 리더",
  "Aprende a leer 한글 con audio de voz nativa, directo en tu navegador.": "원어민 음성으로 한글 읽기를 배우세요. 브라우저에서 바로.",
  "Abrir el Lector →": "리더 열기 →",
  "Descubre en qué peldaño empiezas.": "어느 단계에서 시작할지 알아보세요.",
  "Hacer el test →": "테스트 하기 →",
  "Guía del alfabeto coreano (PDF)": "한글 가이드 (PDF)",
  "Descárgala y empieza a leer desde cero.": "다운로드해서 처음부터 읽기를 시작하세요.",
  "Ver recursos gratis →": "무료 자료 보기 →",
  "Gratis, sin inscribirte": "가입 없이 무료",
  "Empieza gratis hoy": "오늘 무료로 시작하세요",
  "Lee sobre cultura coreana en el blog →": "블로그에서 한국 문화 읽기 →",
  "¿Tienes dudas? Hablemos.": "궁금한 점이 있나요? 이야기해요.",
  "💬 Escribir a Jay por WhatsApp →": "💬 WhatsApp으로 Jay에게 메시지 보내기 →",
  // ── components/HorarioSemanal.tsx
  "Horarios en": "시간표 기준:",
  "convertidos desde hora de Chile": "칠레 시간 기준으로 변환됨",
  "Hora": "시간",
  "máx. {n}": "최대 {n}명",
  "✓ Seleccionada": "✓ 선택됨",
  "5 cursos · 6 horarios (Básico 1 se dicta martes y jueves: elige uno) · todas las clases parten la semana del 5 de octubre · 8 semanas · 60 min.": "5개 과정 · 6개 시간대 (기초 1은 화요일과 목요일에 열려요: 하나를 선택하세요) · 모든 수업은 10월 5일 주에 시작해요 · 8주 · 60분.",
  // ── components/KoreanCulture.tsx
  "Entiende cada diálogo sin subtítulos.": "자막 없이 모든 대사를 이해해요.",
  "Canta en coreano real, no en fonética.": "발음 표기가 아닌 진짜 한국어로 노래해요.",
  "Pide en coreano como un local.": "현지인처럼 한국어로 주문해요.",
  "Seúl": "서울",
  "Viaja a Corea sin barreras.": "언어 장벽 없이 한국을 여행해요.",
  "Cultura coreana": "한국 문화",
  "El idioma que abre": "언어 하나로 열리는",
  "un mundo entero": "온 세상",
  "K-drama, K-pop, gastronomía y Seúl. Aprender coreano es entrar a un universo cultural completo — y en el blog lo exploramos contigo.": "K-드라마, K-pop, 음식 그리고 서울. 한국어를 배운다는 건 하나의 온전한 문화 세계로 들어가는 일이에요 — 블로그에서 함께 탐험해요.",
  "Lee el blog de cultura coreana": "한국 문화 블로그 읽기",
  // ── components/MetodoChingu.tsx
  "Lee desde el principio": "처음부터 읽어요",
  "Nada de romanización eterna. Aprendes a leer 한글 desde tu primera semana, porque leer coreano de verdad cambia cómo aprendes todo lo demás.": "끝없는 로마자 표기는 없어요. 첫 주부터 한글을 읽는 법을 배워요. 한국어를 진짜로 읽을 수 있게 되면 나머지 모든 것을 배우는 방식이 달라지니까요.",
  "Habla desde el día uno": "첫날부터 말해요",
  "Cada clase tiene práctica oral real. Te equivocas, te corrigen, vuelves a intentar — así se aprende a hablar, no memorizando tablas.": "모든 수업에 실전 말하기 연습이 있어요. 틀리고, 교정받고, 다시 시도하고 — 말하기는 표를 외워서가 아니라 이렇게 배우는 거예요.",
  "Entiende Corea": "한국을 이해해요",
  "No solo qué se dice, sino por qué se dice así. Honoríficos, jerarquía, comida, K-drama: la cultura es parte de la gramática.": "무엇을 말하는지뿐 아니라 왜 그렇게 말하는지까지. 존댓말, 위계, 음식, K-드라마: 문화도 문법의 일부예요.",
  "Aprende con tus chingus": "친구들과 함께 배워요",
  "Grupos reducidos y una comunidad que sigue después de clase. Aprender un idioma acompañado es más rápido — y mucho más divertido.": "소규모 그룹, 그리고 수업이 끝나도 이어지는 커뮤니티. 함께 배우면 언어는 더 빨리 늘어요 — 그리고 훨씬 더 재미있어요.",
  "No aprendas coreano como un libro.": "교과서처럼 한국어를 배우지 마세요.",
  "Aprende como un chingu.": "친구처럼 배우세요.",
  "Cuatro pilares pensados desde el español: anticipamos los errores típicos de un hispanohablante en vez de traducir un programa coreano.": "스페인어를 바탕으로 설계한 네 가지 기둥: 한국 교재를 번역하는 대신 스페인어 사용자가 흔히 하는 실수를 미리 짚어 줍니다.",
  "Así se aplica el método en cada curso →": "각 과정에 적용되는 방법 보기 →",
  // ── components/Navigation.tsx
  "Inicio": "홈",
  "Inscripción octubre": "10월 등록",
  "Programa": "프로그램",
  "Sobre Jay": "Jay 소개",
  "Recursos": "학습 자료",
  "Lector de Hangul 🐯 (nuevo)": "한글 리더 🐯 (신규)",
  "Guías": "가이드",
  "Pronunciación coreana": "한국어 발음",
  "Tu nombre en coreano": "한국어로 내 이름 쓰기",
  "Hangul-dle (juego diario)": "Hangul-dle (데일리 게임)",
  "Preguntas (FAQ)": "자주 묻는 질문 (FAQ)",
  "Contacto": "문의하기",
  "Abrir menú": "메뉴 열기",
  "Contacto por WhatsApp": "WhatsApp으로 문의하기",
  // ── components/PrefsControls.tsx
  "Idioma": "언어",
  "Modo día": "라이트 모드",
  "Modo noche": "다크 모드",
  // ── components/ProgramaContent.tsx
  "La escalera": "레벨 사다리",
  "Horario semanal": "주간 시간표",
  "Cómo es una clase": "수업 진행 방식",
  "Equipo docente": "교사진",
  "Precio y pago": "가격 및 결제",
  "PROGRAMA OFICIAL · COHORTE OCTUBRE 2026": "공식 프로그램 · 2026년 10월 기수",
  "5 cursos · 6 horarios · 8 semanas · 1 clase de 60 min por semana · certificado incluido": "5개 과정 · 6개 시간대 · 8주 · 주 1회 60분 수업 · 수료증 포함",
  "Inscribirme →": "등록하기 →",
  "📄 Descargar programa (PDF)": "📄 프로그램 다운로드 (PDF)",
  "¿Quieres el detalle semana a semana?": "주차별 상세 내용이 궁금하신가요?",
  "Programa completo de estudios (PDF, español)": "전체 교육과정 (PDF, 스페인어)",
  "Complete program (PDF, English)": "전체 교육과정 (PDF, 영어)",
  "La escalera de Academia Seúl": "아카데미아 서울의 레벨 사다리",
  "Todos los cursos duran 8 semanas y cuestan lo mismo. Cada peldaño te deja listo para el siguiente. Toca tu caso y te decimos dónde entrar.": "모든 과정은 8주 과정이고 가격도 같아요. 각 단계를 마치면 다음 단계로 갈 준비가 돼요. 내 상황을 누르면 어디서 시작하면 좋을지 알려드려요.",
  "Todas las clases parten {inicio} · toca tu país para ver tu hora": "모든 수업은 {inicio}에 시작해요 · 내 나라를 눌러 현지 시간을 확인하세요",
  "CÓMO ES UNA CLASE": "수업 진행 방식",
  "60 minutos que rinden": "알차게 쓰는 60분",
  "El drilling pesado (leer sílabas, memorizar números) vive en el Lector de Hangul como tarea con audio nativo. La hora en vivo se reserva para lo que solo la clase en vivo da: hablar y ser corregido.": "반복 훈련(음절 읽기, 숫자 외우기)은 원어민 음성이 담긴 한글 리더 숙제로 해요. 실시간 수업의 한 시간은 실시간 수업에서만 할 수 있는 것, 즉 말하고 교정받는 데 온전히 써요.",
  "Quiz de la clase anterior": "지난 수업 퀴즈",
  "Activar lo aprendido": "배운 내용 되살리기",
  "Lección con el deck": "슬라이드 수업",
  "Gramática con dibujos y ejemplos reales": "그림과 실제 예문으로 배우는 문법",
  "Práctica oral en pares": "짝과 함께하는 말하기 연습",
  "Role-play y corrección de pronunciación": "롤플레이와 발음 교정",
  "Cierre y tarea": "마무리와 숙제",
  "Lector de Hangul + hoja de la sesión": "한글 리더 + 수업 활동지",
  "Ruta Niños": "어린이 코스",
  "Paso {n} de la escalera": "레벨 사다리 {n}단계",
  "{hora} Chile · primera clase {fecha}": "칠레 시간 {hora} · 첫 수업 {fecha}",
  "Profesor/a": "선생님",
  "Requiere": "선수 조건",
  "Nada — desde cero": "없음 — 처음부터 시작",
  "Material": "교재",
  "US${p} · o {n} × US${m}": "US${p} · 또는 US${m} × {n}회",
  "Al terminar vas a poder:": "과정을 마치면 할 수 있는 것:",
  "Inscribirme en {curso} →": "{curso} 등록하기 →",
  "Semana a semana": "주차별 커리큘럼",
  "Un solo precio para todos los cursos": "모든 과정 단일 가격",
  "{precio} — sin importar el nivel.": "{precio} — 레벨에 상관없이 동일해요.",
  "Una al inscribirte, otra al inicio del mes 2": "등록할 때 1회, 두 번째 달 시작 시 1회",
  "8 clases en vivo por Zoom de 60 min": "줌(Zoom) 실시간 수업 8회 (60분)",
  "Certificado de Academia Seúl incluido": "아카데미아 서울 수료증 포함",
  "Grabación de cada clase": "매 수업 녹화본",
  "Slides + hojas de actividad": "슬라이드 + 활동지",
  "Lector de Hangul con audio nativo": "원어민 음성 한글 리더",
  "Grupos chicos con corrección personal": "개별 교정이 가능한 소규모 그룹",
  "Hola Jay! Vi el programa de octubre y tengo una duda sobre qué curso me conviene.": "안녕하세요 Jay! 10월 프로그램을 봤는데, 어떤 과정이 저에게 맞을지 궁금해요.",
  "💬 ¿Qué nivel me conviene?": "💬 어떤 레벨이 나에게 맞을까요?",
  // ── components/PromoBar.tsx
  "Matrícula abierta hasta el 4 de octubre": "10월 4일까지 등록 접수",
  "clases desde la semana del 5 de octubre": "10월 5일 주부터 수업 시작",
  "Cerrar": "닫기",
  // ── components/RecursosContent.tsx
  "Combina consonante + vocal en un tablero de 2×2 o 3×3 y forma la palabra que lees o que escuchas. 30 niveles, 6 barrios de Seúl, voz nativa y entrenamiento del oído.": "2×2 또는 3×3 판에서 자음 + 모음을 조합해 읽거나 들은 단어를 만드세요. 30개 레벨, 서울의 6개 동네, 원어민 음성과 듣기 훈련.",
  "Jugar a Dubu": "두부 하기",
  "Aprende a leer el alfabeto coreano con la lógica del 훈민정음: lecciones interactivas, constructor de sílabas y práctica con audio de voz nativa que cambia en cada ronda.": "훈민정음의 원리로 한글 읽는 법을 배워요: 인터랙티브 레슨, 음절 조립기, 그리고 매 라운드마다 바뀌는 원어민 음성 연습까지.",
  "Aprender a leer": "읽기 배우기",
  "Descarga gratis la Guía del Alfabeto (한글) y la Guía de Pronunciación coreana. PDFs listos para imprimir y estudiar.": "알파벳 가이드 (한글)와 한국어 발음 가이드를 무료로 다운로드하세요. 바로 인쇄해서 공부할 수 있는 PDF예요.",
  "Ver guías": "가이드 보기",
  "Tablero interactivo: haz clic en cada consonante, vocal y palabra para escuchar su sonido en coreano. Gratis y desde el navegador.": "인터랙티브 보드: 자음, 모음, 단어를 하나씩 클릭해 한국어 소리를 들어 보세요. 무료이고 브라우저에서 바로 돼요.",
  "Practicar pronunciación": "발음 연습하기",
  "Escribe tu nombre, míralo en hangul y escúchalo con voz coreana. Descárgalo como imagen para compartir.": "이름을 입력하고 한글로 확인한 뒤 한국어 음성으로 들어 보세요. 이미지로 다운로드해 공유할 수도 있어요.",
  "Crear mi nombre": "내 이름 만들기",
  "Torpedo Coreano": "한국어 커닝 페이퍼",
  "Un juego rápido de vocabulario y gramática de Básico 1 (A1.1): saludos, partículas, familia y más. Ocho preguntas para poner a prueba lo que ya sabes.": "기초 1 (A1.1)의 어휘와 문법을 담은 빠른 게임: 인사, 조사, 가족 등. 8문제로 지금 아는 만큼을 테스트해 보세요.",
  "Jugar ahora": "지금 플레이",
  "Nuestro Wordle coreano: adivina la palabra del día en 6 intentos. Una palabra nueva cada 24 horas, con racha incluida.": "우리만의 한국어 Wordle: 6번 안에 오늘의 단어를 맞혀 보세요. 24시간마다 새 단어가 나오고, 연속 기록도 쌓여요.",
  "Jugar hoy": "오늘 플레이",
  "Recursos gratis": "무료 학습 자료",
  "Aprende coreano": "한국어 배우기",
  "Todo gratis para empezar hoy: guías descargables, pronunciación con audio y tu nombre en coreano.": "오늘 바로 시작할 수 있는 무료 자료: 다운로드 가이드, 음성 발음 연습, 그리고 한글로 쓴 내 이름.",
  // ── components/ResumenReserva.tsx
  "{dia} {hora} Chile": "{dia} {hora} 칠레 시간",
  "{dia} {hora} {pais} ({horaChile} Chile)": "{dia} {hora} {pais} 시간 (칠레 {horaChile})",
  "Cambiar": "변경",
  "Cambiar clase": "수업 변경",
  "primera clase **{fecha}**": "첫 수업 **{fecha}**",
  // ── components/SidebarCursos.tsx
  "Clases de octubre": "10월 수업",
  "En esta página": "이 페이지에서",
  "Navegación de cursos": "과정 내비게이션",
  // ── components/SobreContent.tsx
  "이야기 · Mi historia": "이야기 · 나의 이야기",
  "Hola, soy": "안녕하세요, 저는",
  "Fundador y profesor · Academia Seúl": "설립자이자 선생님 · 아카데미아 서울",
  "Nací como": "저는 서울에서 태어난",
  "en Seúl, entre kimchi y una educación coreana de la dura — esa que te enseña a esforzarte y a no rendirte nunca.": "— 김치, 그리고 노력하고 절대 포기하지 않는 법을 가르치는 그 혹독한 한국식 교육 속에서 자란 아이였어요.",
  "Tenía 10 años cuando crucé medio mundo y llegué a Chile. Fue increíble… y durísimo. En el colegio americano me tocaba hacer malabares con el español y el inglés al mismo tiempo, sin red. Aprender a": "열 살 때 지구 반 바퀴를 건너 칠레에 왔어요. 놀라웠고… 정말 힘들었죠. 미국계 학교에서 스페인어와 영어를 동시에, 아무 안전망 없이 저글링해야 했거든요. 어딘가에",
  "pertenecer": "속하는 법을 배우는 것",
  "fue mi primera gran lección — y nadie me dio un mapa.": "— 그것이 제 첫 번째 큰 교훈이었어요. 그런데 아무도 지도를 주지 않았죠.",
  "Pero Chile me adoptó. Me enamoré de los asados, las empanadas y los zapateos de norte a sur. Sin darme cuenta, me convertí en las dos cosas a la vez: coreano y latino.": "하지만 칠레는 저를 품어 줬어요. 아사도, 엠파나다, 그리고 북에서 남까지 이어지는 사파테오 춤에 푹 빠졌죠. 어느새 저는 두 가지가 동시에 되어 있었어요. 한국인이자 라티노.",
  "Una conexión para el mundo. Un puente con piernas.": "세상을 잇는 연결고리. 두 발로 걷는 다리.",
  "Después me fui a estudiar a Michigan y me hice economista. Pero si miro hacia atrás, toda mi vida hice lo mismo: enseñar y ayudar. Mi mamá fue profesora universitaria, y de ella heredé la fascinación por aprender. Estudiar no es mi obligación; es mi pasión.": "그 뒤 미시간으로 유학을 가서 경제학자가 됐어요. 하지만 돌아보면 저는 평생 같은 일을 해 왔더라고요. 가르치고, 돕는 일이요. 어머니는 대학 교수셨고, 배움에 대한 매혹은 어머니에게서 물려받았어요. 공부는 제 의무가 아니라, 제 열정이에요.",
  "De ahí nació Academia Seúl. Quiero compartir lo que amo —el idioma, la cultura, la música, el K-pop, la comida— con quienes lo aman desde lejos, igual que yo amé a Chile desde el primer asado.": "그렇게 아카데미아 서울이 태어났어요. 제가 사랑하는 것들 — 언어, 문화, 음악, K-pop, 음식 — 을 멀리서 사랑하는 분들과 나누고 싶어요. 제가 첫 아사도부터 칠레를 사랑했던 것처럼요.",
  "Gracias por estar aquí, justo al inicio de este viaje. Este puente lo cruzamos juntos.": "이 여정의 바로 첫걸음에 함께해 주셔서 고마워요. 이 다리, 같이 건너요.",
  "Empieza desde cero conmigo y el equipo. Clases en vivo, grupos pequeños.": "저와 우리 팀과 함께 처음부터 시작해 보세요. 실시간 수업, 소규모 그룹.",
  "Ver cursos de octubre →": "10월 과정 보기 →",
  "Y en el camino descubrí algo que me dolió: casi todo el material para aprender coreano está hecho **para nativos**, o **en inglés**. No existe contenido —ni un libro de verdad— pensado para hispanohablantes. Seré su **profesor Kim**, y un buen": "그리고 그 길에서 마음 아픈 사실을 하나 발견했어요. 한국어 학습 자료의 거의 전부가 **원어민을 위해**, 아니면 **영어로** 만들어져 있다는 거예요. 스페인어권 학습자를 위해 만든 콘텐츠는 — 제대로 된 책 한 권조차 — 없어요. 저는 여러분의 **김 선생님**이 될게요. 그리고 좋은",
  "Por eso voy a escribirlo junto al gran equipo de profesores que he formado — ya puedes conocerlos en el programa de octubre. **Para ustedes.**": "그래서 제가 꾸린 멋진 선생님 팀과 함께 직접 쓰려고 해요 — 10월 프로그램에서 이미 만나 보실 수 있어요. **여러분을 위해서요.**",
  // ── components/Testimonials.tsx
  "Nivel A1": "A1 레벨",
  "Coreano Básico": "기초 한국어",
  "Para mí fue un gran profesor. Le entendí muy bien y era bueno explicando. Si alguien no entendía, volvía a explicar. Sus clases eran muy divertidas y aprendimos muchas cosas sobre la cultura coreana.": "저에게는 정말 훌륭한 선생님이었어요. 설명을 아주 잘하셔서 이해가 잘 됐고, 누군가 이해하지 못하면 다시 설명해 주셨어요. 수업이 정말 재미있었고 한국 문화에 대해서도 많이 배웠어요.",
  "Las clases son bastante entretenidas porque, más que pasar solo contenido, también nos enseña otras cosas. Cuando le preguntamos un concepto, nos cuenta una pequeña historia relacionada — así lo recuerdo más fácilmente.": "수업이 꽤 재미있어요. 그냥 진도만 나가는 게 아니라 다른 것들도 가르쳐 주시거든요. 어떤 개념을 물어보면 관련된 짧은 이야기를 들려주셔서 — 그래서 더 쉽게 기억에 남아요.",
  "Nivel B1": "B1 레벨",
  "Coreano Intermedio": "중급 한국어",
  "Excelente profesor. Siempre disponible para responder dudas dentro y fuera del horario de clases, además de explicar hasta que se entienda. Las clases son divertidas y entendibles. ¡Gracias, profesor!": "최고의 선생님이에요. 수업 시간 안팎으로 언제나 질문에 답해 주시고, 이해될 때까지 설명해 주세요. 수업은 재미있고 이해하기 쉬워요. 감사합니다, 선생님!",
  "Muy buen profesor, sus explicaciones son muy claras y siempre da distintos ejemplos. Además nos enseña sobre cultura y cosas típicas de Corea. También enseña con música, lo cual facilita mucho el oído y la pronunciación correcta.": "정말 좋은 선생님이에요. 설명이 아주 명확하고 항상 다양한 예를 들어 주세요. 그리고 한국 문화와 한국 특유의 것들도 가르쳐 주시고요. 음악으로도 가르쳐 주시는데, 듣기와 정확한 발음에 큰 도움이 돼요.",
  "Clases claras y didácticas, con entrega de material adecuado para el estudio. Se agradece el esfuerzo para fomentar la participación en clases y explicar reiteradamente en caso de dudas, además de la disposición para resolver dudas fuera del horario.": "명확하고 알기 쉬운 수업에, 공부에 적합한 자료도 제공해 주세요. 수업 참여를 이끌어 주시고 궁금한 게 있으면 몇 번이고 설명해 주시는 노력, 그리고 수업 시간 외에도 질문을 받아 주시는 마음에 감사드려요.",
  "Jae Hee tiene muy buena disposición cuando alguien tiene una duda, complementa sus clases con cultura general y se dan espacios de confianza donde se pueden compartir experiencias.": "재희 선생님은 누군가 궁금한 게 있을 때 정말 친절하게 대해 주시고, 수업에 문화 전반의 이야기를 곁들여 주세요. 경험을 나눌 수 있는 편안한 분위기도 만들어져요.",
  "Fue entretenido y entendí muy bien las clases. Tiene mucha paciencia y hace agradable el aprender.": "재미있었고 수업 내용도 아주 잘 이해했어요. 인내심이 많으셔서 배우는 게 즐거워요.",
  "Anterior": "이전",
  "Siguiente": "다음",
  "Testimonio {n}": "후기 {n}",
  "Lo que dicen": "직접 들어보는",
  "mis chingus": "제 친구들의 이야기",
  "Testimonios reales de estudiantes que tomé en mis clases anteriores. La misma energía y metodología llega ahora a Academia Seúl.": "이전 수업에서 제가 가르쳤던 학생들의 실제 후기예요. 같은 에너지와 교수법이 이제 아카데미아 서울로 이어져요.",
  "La mejor forma de conocer nuestro método: una clase en vivo.": "우리 메소드를 알아보는 가장 좋은 방법: 실시간 수업 한 번.",
  "¿Prefieres preguntar primero? Escríbele a Jay por WhatsApp →": "먼저 물어보고 싶으신가요? Jay에게 WhatsApp으로 문의하세요 →",
  // ── components/VideoIntro.tsx
  "Conoce a tu chingu coreano": "당신의 한국인 친구를 만나보세요",
  // ── components/WhatsAppFloat.tsx
  "Hola Jay! Vi tu sitio Academia Seul y tengo una consulta sobre tus cursos de coreano.": "안녕하세요 Jay! 아카데미아 서울 사이트를 보고 한국어 과정에 대해 문의드려요.",
  "Quiero inscribirme (clases desde la semana del 5 de octubre)": "등록하고 싶어요 (10월 5일 주부터 수업)",
  "Hola Jay! Quiero inscribirme en la cohorte de octubre. ¿Me ayudas a elegir el curso y el método de pago?": "안녕하세요 Jay! 10월 기수에 등록하고 싶어요. 과정과 결제 방법 고르는 걸 도와주실 수 있나요?",
  "¿Qué nivel me conviene?": "어떤 레벨이 맞을까요?",
  "Hola Jay! No sé si me conviene Básico 1, Básico 2, Conversacional o TOPIK II. ¿Me orientas?": "안녕하세요 Jay! 기초 1, 기초 2, 회화, TOPIK II 중 어떤 게 맞을지 모르겠어요. 안내해 주실 수 있나요?",
  "Consulta personalizada": "맞춤 상담",
  "Hola Jay! Tengo una consulta sobre tus cursos de coreano.": "안녕하세요 Jay! 한국어 과정에 대해 문의드려요.",
  "Te respondo en horas": "몇 시간 안에 답해 드려요",
  "Empieza la conversacion": "대화 시작하기",
  "Abre WhatsApp con mensaje listo. 100% sin compromiso.": "메시지가 준비된 WhatsApp이 열려요. 100% 부담 없이.",
  "Abrir WhatsApp": "WhatsApp 열기",
  // ── components/WordGame.tsx
  "Básico": "기초",
  "¿Qué significa este saludo?": "이 인사말은 무슨 뜻일까요?",
  "Adiós": "안녕히 가세요",
  "Hola": "안녕하세요",
  "Gracias": "감사합니다",
  "Lo siento": "죄송합니다",
  "¿Qué significa esta frase?": "이 표현은 무슨 뜻일까요?",
  "Por favor": "부탁합니다",
  "De nada": "천만에요",
  "Perdón": "미안합니다",
  "Gramática: ¿qué partícula completa \"Yo soy estudiante\"?": "문법: \"저 __ 학생이에요\"의 빈칸에 들어갈 조사는 무엇일까요?",
  "¿Qué significa esta palabra?": "이 단어는 무슨 뜻일까요?",
  "Amigo": "친구",
  "Familia": "가족",
  "Escuela": "학교",
  "Trabajo": "직장",
  "Intermedio": "중급",
  "\"¿No te gusta el café?\" — si es cierto que NO te gusta, ¿cómo respondes en coreano?": "\"커피 안 좋아해요?\" — 정말로 안 좋아한다면, 한국어로 어떻게 대답할까요?",
  "¿Qué significa esta pregunta?": "이 질문은 무슨 뜻일까요?",
  "¿Quién es?": "누구예요?",
  "¿Dónde está?": "어디에 있어요?",
  "¿Qué es esto?": "이게 뭐예요?",
  "¿Cómo estás?": "잘 지내요?",
  "Gramática: ¿qué partícula completa \"Bebo café\"?": "문법: \"커피 __ 마셔요\"의 빈칸에 들어갈 조사는 무엇일까요?",
  "Un coreano dice esto para referirse a...": "한국 사람이 이 말로 가리키는 사람은...",
  "Nuestra mamá (de todos)": "우리 모두의 엄마",
  "Mi mamá": "내 엄마",
  "La mamá de otro": "다른 사람의 엄마",
  "Su abuela": "그 사람의 할머니",
  "Pruébalo tú mismo": "직접 해 보세요",
  "¿Cuánto coreano": "한국어를",
  "ya sabes?": "얼마나 알고 있나요?",
  "8 preguntas rápidas de vocabulario y gramática, sacadas directo de nuestras clases de Básico 1 (A1.1).": "기초 1 (A1.1) 수업에서 그대로 가져온 어휘·문법 스피드 퀴즈 8문제예요.",
  "Mezcla de vocabulario y partículas — nivel básico a intermedio.": "어휘와 조사가 섞여 있어요 — 기초에서 중급 수준까지.",
  "Empezar el juego": "게임 시작하기",
  "Pregunta": "문제",
  "de {total}": "/ {total}",
  "Puntaje:": "점수:",
  "Resultado": "결과",
  "¡Puntaje perfecto! Ya tienes una base sólida — Básico 2 (A1.2) o Conversacional 1 (A2.1) son tu siguiente paso.": "만점이에요! 이미 탄탄한 기초가 있네요 — 다음 단계는 기초 2 (A1.2) 또는 회화 1 (A2.1)이에요.",
  "Nada mal para una probadita. En Básico 1 vemos todo esto (y mucho más) con calma, paso a paso.": "맛보기치고는 나쁘지 않아요. 기초 1에서는 이 모든 내용을 (그리고 훨씬 더 많은 것을) 차근차근, 한 걸음씩 배워요.",
  "Así arrancamos todos. En Básico 1 (A1.1) empezamos desde cero, sin apuro y con clases en vivo.": "누구나 이렇게 시작해요. 기초 1 (A1.1)에서는 서두르지 않고, 실시간 수업으로 처음부터 시작해요.",
  "Jugar de nuevo": "다시 하기",
  // ── lib/nivel1.ts
  "Jay Kim · 김재희": "Jay Kim · 김재희",
  "Fundador · Básico 2 y TOPIK II": "설립자 · 기초 2 및 TOPIK II",
  "Coreano nativo radicado en Chile. Creador del Método Chingu™ y del Lector de Hangul. 8+ años enseñando a hispanohablantes.": "칠레에 거주하는 한국인. 친구 메소드™와 한글 리더를 만들었어요. 스페인어권 학습자를 8년 넘게 가르쳐 왔어요.",
  "Guiran · 기란": "Guiran · 기란",
  "Básico 1 (martes y jueves)": "기초 1 (화요일·목요일)",
  "Profesora coreana criada en Argentina — bilingüe perfecta. Años de experiencia enseñando coreano en español.": "아르헨티나에서 자란 한국인 선생님 — 완벽한 이중언어 구사자예요. 스페인어로 한국어를 가르친 경력이 오래됐어요.",
  "Abby · 홍미영": "Abby · 홍미영",
  "Conversacional 1": "회화 1",
  "Profesora coreana nativa, pedagoga (MSU). Dicta el conversacional desde Corea — clases donde solo se habla.": "한국인 원어민 선생님, 교육학 전공 (MSU). 한국에서 회화 수업을 진행해요 — 오직 말하기만 하는 수업이에요.",
  "Jay y Abby · 김재희 · 홍미영": "Jay & Abby · 김재희 · 홍미영",
  "Jay y Abby": "Jay & Abby",
  "Dos profes coreanos nativos para la clase de niños: Jay (fundador, criado en Chile) y Abby (pedagoga). Juegos, canciones y dibujos en un grupo de máximo 12.": "어린이반을 맡는 두 명의 한국인 원어민 선생님: Jay(설립자, 칠레에서 자람)와 Abby(교육 전문가). 최대 12명 그룹에서 놀이·노래·그림으로 배워요.",
  "Básico 1 (A1.1) · Martes 20:00 Chile · Guiran": "기초 1 (A1.1) · 화요일 20:00 칠레 시간 · Guiran",
  "Martes": "화요일",
  "martes 6 de octubre": "10월 6일 (화)",
  "Básico 1 (A1.1) · Jueves 20:00 Chile · Guiran": "기초 1 (A1.1) · 목요일 20:00 칠레 시간 · Guiran",
  "Jueves": "목요일",
  "jueves 8 de octubre": "10월 8일 (목)",
  "Básico 2 (A1.2) · Miércoles 21:00 Chile · Jay": "기초 2 (A1.2) · 수요일 21:00 칠레 시간 · Jay",
  "Miércoles": "수요일",
  "miércoles 7 de octubre": "10월 7일 (수)",
  "Conversacional 1 (A2.1) · Martes 21:00 Chile · Abby": "회화 1 (A2.1) · 화요일 21:00 칠레 시간 · Abby",
  "TOPIK II (B1+) · Jueves 21:00 Chile · Jay": "TOPIK II (B1+) · 목요일 21:00 칠레 시간 · Jay",
  "Coreano para Niños (8–12) · Lunes 18:00 Chile · Jay y Abby": "어린이 한국어 (8–12세) · 월요일 18:00 칠레 시간 · Jay & Abby",
  "Lunes": "월요일",
  "lunes 5 de octubre": "10월 5일 (월)",
  "Argentina / Uruguay / Brasil": "아르헨티나 / 우루과이 / 브라질",
  "Colombia / Perú / Ecuador": "콜롬비아 / 페루 / 에콰도르",
  "Col/Perú": "콜롬비아/페루",
  "México (CDMX)": "멕시코 (멕시코시티)",
  "EE.UU. (hora del Este)": "미국 (동부 시간)",
  "EE.UU. Este": "미국 동부",
  "En EE.UU. la hora cambia el 1 de noviembre (se muestra antes → después).": "미국은 11월 1일에 시간이 바뀌어요 (변경 전 → 후로 표시).",
  "En España la hora cambia el 25 de octubre (se muestra antes → después).": "스페인은 10월 25일에 시간이 바뀌어요 (변경 전 → 후로 표시).",
  "Corea": "한국",
  "Para Corea, las clases caen a la mañana del día siguiente.": "한국에서는 수업이 다음 날 아침 시간이에요.",
  "Primeras Palabras": "첫 단어",
  "Nivel 1 · julio 2026": "레벨 1 · 2026년 7월",
  "Básico 1 · Primeras Palabras": "기초 1 · 첫 단어",
  "A1.1 · desde cero": "A1.1 · 완전 처음부터",
  "한글학교 한국어 1 + Lector de Hangul (tarea con audio nativo)": "한글학교 한국어 1 + 한글 리더 (원어민 음성 과제)",
  "El punto de partida: aprender a leer el alfabeto coreano y decir tus primeras frases reales. El drilling de lectura vive en el Lector de Hangul como tarea gamificada, así la hora en vivo se usa para hablar y ser corregido.": "출발점: 한글 읽는 법을 배우고 진짜 첫 문장을 말해 봐요. 읽기 반복 연습은 한글 리더에서 게임형 과제로 진행되니, 실시간 수업 시간은 말하고 교정받는 데 온전히 써요.",
  "가나다라 I · La sílaba": "가나다라 I · 음절",
  "Vocales y consonantes básicas — lees tus primeras sílabas en voz alta": "기본 모음과 자음 — 첫 음절을 소리 내어 읽어요",
  "Batchim y dobles · saludos · 저는 ~예요: te presentas con nombre y país": "받침과 쌍자음 · 인사 · 저는 ~예요: 이름과 나라로 자기소개를 해요",
  "이게 뭐예요? · ¿Qué es esto?": "이게 뭐예요? · 사물 묻기",
  "이거/그거/저거 · 이에요/예요 · preguntas y respondes qué es cualquier cosa": "이거/그거/저거 · 이에요/예요 · 무엇이든 그게 뭔지 묻고 답해요",
  "우리 엄마예요 · Mi familia": "우리 엄마예요 · 우리 가족",
  "Familia · el famoso 우리 · 누구예요? · números sino-coreanos": "가족 · 그 유명한 우리 · 누구예요? · 한자어 숫자",
  "집이 어디예요? · Lugares": "집이 어디예요? · 장소",
  "어디 · N에 있어요 · dices dónde vives y dónde están las cosas": "어디 · N에 있어요 · 어디 사는지, 물건이 어디 있는지 말해요",
  "학교에 가요 · Mi día": "학교에 가요 · 나의 하루",
  "Presente -아/어요 · N에 가다 · cuentas a dónde vas cada día": "현재형 -아/어요 · N에 가다 · 매일 어디에 가는지 이야기해요",
  "Mi pieza y mis verbos": "내 방과 동사들",
  "이/가 · 을/를 · 있다/없다 · describes tu pieza y qué haces": "이/가 · 을/를 · 있다/없다 · 내 방과 내가 하는 일을 말해요",
  "사과를 좋아해요 + examen": "사과를 좋아해요 + 시험",
  "Gustos · repaso integral · mini-presentación final · certificado": "좋아하는 것 · 종합 복습 · 마지막 미니 발표 · 수료증",
  "Pasado, presente y futuro": "과거·현재·미래",
  "Básico 1 (A1.1) o el Nivel 1 de julio": "기초 1 (A1.1) 또는 레벨 1 (7월)",
  "Básico 2 · Pasado, presente y futuro": "기초 2 · 과거·현재·미래",
  "A1.2 · requiere Básico 1": "A1.2 · 기초 1 수료 필요",
  "Uso de la gramática coreana · Nivel inicial (Korean Grammar in Use en español)": "Korean Grammar in Use · 초급 (스페인어판 Uso de la gramática coreana)",
  "La continuación directa de Básico 1 (y del Nivel 1 de julio): del presente al pasado y al futuro. Cuentas lo que hiciste, planeas lo que harás y sumas las partículas que hacen sonar natural tu coreano. Termina con el examen A2 de la casa.": "기초 1 (그리고 7월 레벨 1)에서 바로 이어지는 과정: 현재에서 과거와 미래로 나아가요. 무엇을 했는지 이야기하고, 무엇을 할지 계획하고, 한국어를 자연스럽게 들리게 하는 조사들을 더해요. 아카데미아 서울 자체 A2 시험으로 마무리해요.",
  "Re-presentación + diagnóstico": "다시 자기소개 + 진단",
  "이다/있다 consolidados · repaso activo de Básico 1 · diagnóstico oral": "이다/있다 다지기 · 기초 1 능동 복습 · 말하기 진단",
  "Números aplicados": "실생활 숫자",
  "Sino y nativos en la vida real: edad, cumpleaños, hora (몇 시) y teléfono": "한자어·고유어 숫자를 실생활에서: 나이, 생일, 시간 (몇 시), 전화번호",
  "Presente completo": "현재형 완성",
  "-아/어요 + irregulares de uso diario · describes tu rutina con 10 verbos": "-아/어요 + 자주 쓰는 불규칙 동사 · 동사 10개로 하루 일과를 말해요",
  "El pasado · -았/었어요": "과거형 · -았/었어요",
  "부터~까지 · cuentas qué hiciste el fin de semana (mini-diario)": "부터~까지 · 주말에 한 일을 이야기해요 (미니 일기)",
  "El futuro · -(으)ㄹ 거예요": "미래형 · -(으)ㄹ 거예요",
  "-거나 · planeas tus vacaciones soñadas": "-거나 · 꿈꾸던 휴가를 계획해요",
  "Negación y habilidad": "부정과 능력",
  "안 · 못 · -지 않아요 · -(으)ㄹ 수 있다/없다: qué no haces y qué sabes hacer": "안 · 못 · -지 않아요 · -(으)ㄹ 수 있다/없다: 안 하는 것과 할 줄 아는 것",
  "Partículas pro": "조사 마스터",
  "의 · 도 · 만 · 쯤 · 처럼 · 보다 · 한테 · 밖에 · 마다 — precisión de nativo": "의 · 도 · 만 · 쯤 · 처럼 · 보다 · 한테 · 밖에 · 마다 — 원어민 같은 정확함",
  "Conectores + examen A2": "연결어미 + A2 시험",
  "-고 · -지만 · conversas 5 minutos · examen A2 + oral · certificado": "-고 · -지만 · 5분 대화 · A2 시험 + 말하기 시험 · 수료증",
  "Corea que amas": "당신이 사랑하는 한국",
  "Básico 2 (A1.2) o test de nivel": "기초 2 (A1.2) 또는 레벨 테스트",
  "Conversacional 1 · Corea que amas": "회화 1 · 당신이 사랑하는 한국",
  "A2.1 · requiere Básico 2 o test de nivel": "A2.1 · 기초 2 수료 또는 레벨 테스트 필요",
  "Módulos conversacionales propios (K-pop, viajes, comida…) · con profesora nativa": "자체 제작 회화 모듈 (K-pop, 여행, 음식…) · 원어민 선생님과 함께",
  "Puro hablar: cada semana un tema de la Corea que amas — K-pop, Jeju, comida, hanbok, e-sports — con una profesora coreana nativa y grupos pequeños. La mitad de las sesiones son laboratorio oral.": "오직 말하기: 매주 당신이 사랑하는 한국의 주제 하나 — K-pop, 제주, 음식, 한복, e스포츠 — 한국인 원어민 선생님과 소규모 그룹으로 진행해요. 수업의 절반은 말하기 랩이에요.",
  "Orientación + diagnóstico oral": "오리엔테이션 + 말하기 진단",
  "Romper el hielo · fijar tus metas personales de conversación": "아이스브레이킹 · 나만의 회화 목표 정하기",
  "K-pop y cultura fan": "K-pop과 팬 문화",
  "Hablar de tu grupo, tu bias y los conciertos": "내 그룹, 내 최애, 콘서트 이야기하기",
  "Viajes: Jeju y Seúl": "여행: 제주와 서울",
  "Planear y contar viajes por Corea": "한국 여행 계획하고 이야기하기",
  "Cultura gastronómica": "음식 문화",
  "Pedir, recomendar y describir sabores": "주문하고, 추천하고, 맛 표현하기",
  "Lab de conversación 1": "회화 랩 1",
  "Práctica oral pura en grupos pequeños (módulos 1–3)": "소규모 그룹 순수 말하기 연습 (모듈 1–3)",
  "Hanbok y estética": "한복과 미학",
  "Describir y opinar": "묘사하고 의견 말하기",
  "PC방 y e-sports": "PC방과 e스포츠",
  "La Corea gamer": "게이머들의 한국",
  "Lab 2 + evaluación oral": "랩 2 + 말하기 평가",
  "Evaluación de etapa · certificado A2.1 · invitación a Conversacional 2 (enero)": "단계 평가 · A2.1 수료증 · 회화 2 (1월) 초대",
  "Estrategia de examen": "시험 전략",
  "Nivel intermedio (B1)": "중급 (B1)",
  "Preparación TOPIK II": "TOPIK II 대비",
  "B1+ · examen oficial": "B1+ · 공식 시험",
  "Exámenes TOPIK oficiales + material de estrategia propio": "TOPIK 공식 기출문제 + 자체 전략 교재",
  "Grupo chico (máx. 8) enfocado 100% en el examen oficial: estrategia por sección, corrección personalizada de escritura (쓰기) y simulacros cronometrados. Ideal si apuntas al TOPIK de abril 2027.": "공식 시험에 100% 집중하는 소규모 그룹 (최대 8명): 영역별 전략, 쓰기 개별 첨삭, 시간 제한 모의고사. 2027년 4월 TOPIK을 목표로 한다면 딱이에요.",
  "Diagnóstico + radiografía del TOPIK II": "진단 + TOPIK II 완전 해부",
  "Simulacro diagnóstico · cómo se puntúa · tu nivel de partida": "진단 모의고사 · 채점 방식 · 나의 출발 레벨",
  "읽기 I · Lectura": "읽기 I · 독해",
  "Preguntas 1–20: tipos, trampas y manejo del tiempo": "1–20번 문항: 유형, 함정, 시간 관리",
  "듣기 I · Escucha": "듣기 I · 청해",
  "Dictado activo · preguntas 1–20 · notas mientras escuchas": "능동 받아쓰기 · 1–20번 문항 · 들으면서 메모하기",
  "Completar oraciones: los puntos más rentables del examen": "문장 완성하기: 시험에서 가장 점수 따기 좋은 문항",
  "쓰기 53 · El gráfico": "쓰기 53 · 도표",
  "Describir datos en 200–300 caracteres con la plantilla que funciona": "효과가 검증된 템플릿으로 200–300자 자료 설명하기",
  "읽기/듣기 II · Nivel 4–6": "읽기/듣기 II · 4–6급",
  "Las preguntas difíciles: inferencia, orden y actitud del hablante": "어려운 문항: 추론, 순서 배열, 화자의 태도",
  "쓰기 54 · El ensayo": "쓰기 54 · 논술",
  "Opinión en 600–700 caracteres · estructura + corrección personal": "600–700자 의견 쓰기 · 구조 + 개별 첨삭",
  "Simulacro final + plan personal": "최종 모의고사 + 개인 맞춤 계획",
  "Examen completo cronometrado · análisis · tu plan hasta el TOPIK real": "시간 제한 전체 모의고사 · 분석 · 실제 TOPIK까지의 나만의 계획",
  "8–12 años": "8–12세",
  "Juega y aprende": "놀면서 배워요",
  "8–12 años · desde cero": "8–12세 · 처음부터",
  "Material propio Academia Seúl + Lector de Hangul": "아카데미아 서울 자체 교재 + 한글 리더",
  "Coreano desde cero para niños y niñas, con juegos, canciones y dibujos. Aprenden a leer el alfabeto, presentarse y decir sus primeras frases — y terminan con un mini-show para la familia.": "놀이, 노래, 그림으로 처음부터 배우는 어린이 한국어. 한글 읽기, 자기소개, 첫 문장 말하기를 배우고 — 가족 앞에서 미니 쇼로 마무리해요.",
  "¡Hola, Corea! · 안녕하세요": "안녕, 한국! · 안녕하세요",
  "Saludos con canciones + primeras vocales jugando": "노래로 배우는 인사 + 놀면서 배우는 첫 모음",
  "Mi nombre en coreano": "한국어로 쓰는 내 이름",
  "Consonantes básicas + cada uno escribe su nombre en 한글": "기본 자음 + 내 이름을 한글로 써 보기",
  "La fábrica de sílabas": "음절 공장",
  "Armar y leer sílabas + bingo de lectura": "음절 만들고 읽기 + 읽기 빙고",
  "Los animales · 동물": "동물 친구들 · 동물",
  "10 animales + '¡es un…!' (이에요/예요) con dibujos": "동물 10마리 + 그림으로 '…이에요!' (이에요/예요)",
  "Mi familia · 가족": "우리 가족 · 가족",
  "엄마, 아빠, 할머니… presentar a la familia con una foto o dibujo": "엄마, 아빠, 할머니… 사진이나 그림으로 가족 소개하기",
  "Los números mágicos": "마법의 숫자",
  "Contar del 1 al 10 + decir la edad": "1부터 10까지 세기 + 나이 말하기",
  "¡Ñam! Comida coreana": "냠냠! 한국 음식",
  "김밥, 라면, 불고기 + 'me gusta' (좋아해요)": "김밥, 라면, 불고기 + 좋아하는 음식 말하기 (좋아해요)",
  "🎤 Show final + certificado": "🎤 마지막 쇼 + 수료증",
  "Mini-presentación en coreano para las familias + certificado": "가족 앞에서 하는 한국어 미니 발표 + 수료증",
  "Corea por dentro": "한국 속으로",
  "Leer cualquier sílaba en coreano (Hangul completo + batchim)": "한국어 음절은 무엇이든 읽기 (한글 전체 + 받침)",
  "Presentarte y presentar a tu familia": "나와 우리 가족 소개하기",
  "Contar en los dos sistemas de números y decir la hora": "두 가지 숫자 체계로 세고 시간 말하기",
  "Decir a dónde vas, qué haces y qué te gusta": "어디에 가는지, 무엇을 하는지, 무엇을 좋아하는지 말하기",
  "Hablar en pasado, presente y futuro": "과거·현재·미래로 말하기",
  "Decir qué no haces, qué no puedes y qué sabes hacer": "안 하는 것, 못 하는 것, 할 줄 아는 것 말하기",
  "Comparar y precisar con 보다, 처럼, 마다, 밖에…": "보다, 처럼, 마다, 밖에…로 비교하고 정확하게 표현하기",
  "Conversar 5 minutos seguidos en coreano": "한국어로 5분 동안 쉬지 않고 대화하기",
  "Conversar sobre tus temas favoritos de Corea": "한국에 관한 좋아하는 주제로 대화하기",
  "Planear y contar un viaje": "여행 계획하고 이야기하기",
  "Pedir y recomendar comida como local": "현지인처럼 음식 주문하고 추천하기",
  "Perder el miedo a hablar con una nativa": "원어민과 말하는 두려움 없애기",
  "Dominar la estrategia de cada sección del examen": "시험 영역별 전략 마스터하기",
  "Escribir los formatos 51–54 con corrección personal": "51–54번 유형 쓰기 + 개별 첨삭",
  "Rendir un simulacro completo cronometrado": "시간 제한 전체 모의고사 치르기",
  "Salir con un plan de estudio personal hasta tu examen": "시험 날까지 이어갈 나만의 학습 계획 세우기",
  "Leer sus primeras palabras en coreano": "한국어로 첫 단어 읽기",
  "Presentarse: nombre y edad": "자기소개하기: 이름과 나이",
  "Contar del 1 al 10 y nombrar animales y comidas": "1부터 10까지 세고 동물과 음식 이름 말하기",
  "Octubre 2026": "2026년 10월",
  "Semana del 5 de octubre de 2026": "2026년 10월 5일 주",
  "la semana del 5 de octubre": "10월 5일 주",
  "Semana del 23 de noviembre de 2026": "2026년 11월 23일 주",
  "domingo 4 de octubre (o hasta llenar los cupos)": "10월 4일 (일) 또는 정원 마감 시",
  "España cambia de hora el 25 de octubre y EE.UU. el 1 de noviembre (se muestra antes → después). Chile, Argentina, México, Colombia, Perú y Corea no cambian durante el curso.": "스페인은 10월 25일, 미국은 11월 1일에 시간이 바뀌어요 (변경 전 → 후로 표시). 칠레, 아르헨티나, 멕시코, 콜롬비아, 페루, 한국은 과정 중에 시간이 바뀌지 않아요.",
  "US$150 el curso completo · o 2 cuotas de US$75": "전체 과정 US$150 · 또는 US$75 × 2회 분납",
  "US$150 · o 2 × US$75": "US$150 · 또는 US$75 × 2회",
  "(día sig.)": "(다음 날)",
};
